import { describe, it, expect } from 'vitest'
import { SCOPE_MAPS } from './scope-maps'

// The user-lane rows of the platform proxy's X route table
// (platform apps/proxy/src/services/x.ts), one "METHOD pattern" per row with
// every id segment as "*". A row missing here is a call the platform would
// 404; a row present here but not in the scope map is a call the host would
// send to the policy layer with no scope. Update both when the platform
// table changes.
const PLATFORM_USER_LANE_ROWS = [
  'GET /2/tweets/search/recent',
  'GET /2/tweets',
  'GET /2/tweets/*',
  'GET /2/tweets/counts/recent',
  'GET /2/tweets/*/quote_tweets',
  'GET /2/tweets/*/retweets',
  'GET /2/tweets/*/retweeted_by',
  'GET /2/users',
  'GET /2/users/*',
  'GET /2/users/by',
  'GET /2/users/by/username/*',
  'GET /2/users/*/tweets',
  'GET /2/users/by/username/*/tweets',
  'GET /2/users/*/mentions',
  'GET /2/users/*/followers',
  'GET /2/users/*/following',
  'GET /2/users/*/affiliates',
  'GET /2/lists/*',
  'GET /2/lists/*/tweets',
  'GET /2/lists/*/followers',
  'GET /2/lists/*/members',
  'GET /2/users/*/owned_lists',
  'GET /2/users/*/followed_lists',
  'GET /2/users/*/list_memberships',
  'GET /2/spaces',
  'GET /2/spaces/by/creator_ids',
  'GET /2/spaces/search',
  'GET /2/spaces/*',
  'GET /2/spaces/*/tweets',
  'GET /2/communities/*',
  'GET /2/trends/by/woeid/*',
  'GET /2/media',
  'GET /2/media/*',
  'GET /2/news/search',
  'GET /2/news/*',
  'GET /2/users/me',
  'GET /2/users/search',
  'GET /2/users/reposts_of_me',
  'GET /2/users/*/timelines/reverse_chronological',
  'GET /2/users/*/bookmarks',
  'GET /2/users/*/bookmarks/folders',
  'GET /2/users/*/bookmarks/folders/*',
  'GET /2/users/*/liked_tweets',
  'GET /2/tweets/*/liking_users',
  'GET /2/users/*/muting',
  'GET /2/users/*/blocking',
  'GET /2/users/*/pinned_lists',
  'GET /2/communities/search',
  'GET /2/users/personalized_trends',
  'GET /2/dm_events',
  'GET /2/dm_events/*',
  'GET /2/dm_conversations/*/dm_events',
  'GET /2/dm_conversations/with/*/dm_events',
  'POST /2/tweets',
  'DELETE /2/tweets/*',
  'POST /2/users/*/retweets',
  'DELETE /2/users/*/retweets/*',
  'POST /2/dm_conversations',
  'POST /2/dm_conversations/with/*/messages',
  'POST /2/dm_conversations/*/messages',
  'DELETE /2/dm_events/*',
  'POST /2/users/*/bookmarks',
  'POST /2/users/*/bookmarks/folders',
  'DELETE /2/users/*/bookmarks/*',
  'POST /2/users/*/likes',
  'DELETE /2/users/*/likes/*',
  'POST /2/users/*/following',
  'DELETE /2/users/*/following/*',
  'POST /2/users/*/muting',
  'DELETE /2/users/*/muting/*',
  'POST /2/lists',
  'PUT /2/lists/*',
  'DELETE /2/lists/*',
  'POST /2/lists/*/members',
  'DELETE /2/lists/*/members/*',
  'POST /2/users/*/followed_lists',
  'DELETE /2/users/*/followed_lists/*',
  'POST /2/users/*/pinned_lists',
  'DELETE /2/users/*/pinned_lists/*',
  'POST /2/media/upload',
  'POST /2/media/upload/initialize',
  'POST /2/media/upload/*/append',
  'POST /2/media/upload/*/finalize',
  'GET /2/media/upload',
  'POST /2/media/metadata',
]

describe('twitter scope map', () => {
  it('matches the platform user-lane rows in both directions', () => {
    const host = SCOPE_MAPS.twitter.scopeMap.map((e) => `${e.method} ${e.pathPattern}`)
    expect(new Set(host).size).toBe(host.length)
    expect([...host].sort()).toEqual([...PLATFORM_USER_LANE_ROWS].sort())
  })
})
