/**
 * Per-provider OAuth scope descriptions.
 *
 * These describe what each scope GRANTS the calling app, in language suitable
 * for end-user consent prompts. Sourced from each provider's official OAuth
 * scope reference docs where available; a few are inferred where the provider
 * does not publish per-scope descriptions.
 *
 * Used by scope-matcher (proxy review prompts) and scope-policy-editor
 * (settings dialog) — both prefer values here over per-endpoint descriptions
 * from scope-maps.ts, which describe individual API calls rather than scopes.
 */

export const SCOPE_DESCRIPTIONS: Record<string, Record<string, string>> = {
  "airtable": {
    "airtable.public": "Access basic public Airtable information",
    "block:manage": "Manage extension installations and configurations",
    "data.recordComments:read": "View comments on records",
    "data.recordComments:write": "Create, update, and delete comments on records",
    "data.records:read": "View records in bases",
    "data.records:write": "Create, update, and delete records in bases",
    "enterprise.account:read": "View enterprise account information",
    "enterprise.changeEvents:read": "View enterprise audit log change events",
    "enterprise.groups:read": "View enterprise user groups",
    "enterprise.groups:write": "Create, update, and delete enterprise user groups",
    "enterprise.user:read": "View enterprise user information",
    "enterprise.user:write": "Manage enterprise user information",
    "schema.bases:read": "View base schema (tables, fields, views)",
    "schema.bases:write": "Modify base schema (create or update tables, fields, views)",
    "user.email:read": "View the user's email address",
    "webhook:manage": "Create, modify, and delete webhooks",
  },
  "asana": {
    "goals.read": "View goal information and progress",
    "goals.write": "Create or modify goals",
    "portfolios.read": "View portfolio information and contents",
    "portfolios.write": "Create or modify portfolios",
    "projects.read": "View project information and details",
    "projects.write": "Create or modify projects",
    "sections.read": "View project sections and their contents",
    "sections.write": "Create or modify project sections",
    "tags.read": "View tags and tag information",
    "tags.write": "Create or modify tags",
    "tasks.read": "View basic task information like name and assignee",
    "tasks.write": "Create or modify tasks",
    "teams.read": "View team information and members",
    "users.read": "Access user information like email and profile picture",
    "workspaces.read": "Access workspace information and configuration",
    "workspaces.write": "Modify workspace settings and configuration",
  },
  "bitbucket": {
    "account": "View account information including email addresses, language, location, full name, SSH keys, and user groups",
    "account:write": "Modify account properties including group management, email manipulation, and profile changes",
    "email": "View the user's primary email address",
    "issue": "Interact with issue trackers: view, list, search, create, comment, watch, and vote",
    "issue:write": "Transition and delete issues (in addition to issue scope)",
    "pipeline": "View Bitbucket Pipelines configuration and run history",
    "pipeline:write": "Modify and trigger Bitbucket Pipelines",
    "pullrequest": "Read pull requests, comment, approve, and create tasks (implies repository)",
    "pullrequest:write": "Create, merge, and decline pull requests (implies pullrequest and repository:write)",
    "repository": "Read access to repositories: source code, HTTPS clone, file browsing, issue tracker, and wiki",
    "repository:admin": "Admin access to repositories: committer mappings, deploy keys, permissions, branch settings, webhooks, and ownership transfer",
    "repository:delete": "Delete repositories the user has admin access to",
    "repository:write": "Write access to repositories: push over HTTPS and fork (implies repository)",
    "runner": "View Pipelines runners",
    "runner:write": "Create, modify, and delete Pipelines runners",
    "snippet": "Read snippets and create snippet comments",
    "snippet:write": "Edit and delete snippets (implies snippet)",
    "team": "View information about teams the user belongs to",
    "team:write": "Modify teams the user has access to",
    "webhook": "Read and manage webhook subscriptions across accessible repositories, users, teams, and snippets",
    "wiki": "View, create, edit, push, and clone wikis",
  },
  "box": {
    "ai.readwrite": "Send requests to the Box AI API.",
    "annotation_edit": "Edit and delete annotations.",
    "annotation_view_all": "View annotations by all users.",
    "annotation_view_self": "View only your own annotations.",
    "base_explorer": "Access content in the folder tree based on user/file/token permissions.",
    "base_picker": "Access content in the folder tree based on user/file/token permissions.",
    "base_preview": "Preview the file (no other actions).",
    "base_sidebar": "Get basic file info needed for the sidebar UI.",
    "base_upload": "Upload into the folder specified by the downscoped token.",
    "collaborations.read": "Read collaborations on files and folders.",
    "collaborations.write": "Create and modify collaborations on files and folders.",
    "comments.read": "Read comments on files and folders.",
    "comments.write": "Create and modify comments on files and folders.",
    "events.read": "Read enterprise event stream.",
    "files.delete": "Delete files.",
    "files.read": "Read access to files.",
    "files.write": "Read and write access to files.",
    "folders.delete": "Delete folders.",
    "folders.read": "Read access to folders.",
    "folders.write": "Read and write access to folders.",
    "item_delete": "Delete files and folders.",
    "item_download": "Download files or a folder's content.",
    "item_preview": "Preview a file.",
    "item_rename": "Rename files and folders.",
    "item_share": "Share the item specified under resource of the token exchange.",
    "item_upload": "Upload in the content picker.",
    "manage_app_users": "Manage App Users (server-side JWT apps).",
    "manage_data_retention": "View and create retention policies (Box Governance).",
    "manage_enterprise_properties": "View enterprise event stream and edit enterprise attributes, reports, and device pins.",
    "manage_groups": "Manage enterprise groups: creation, updates, deletion, and membership.",
    "manage_legal_hold": "View and create legal hold policies (Box Governance).",
    "manage_managed_users": "Manage Managed Users, including login, password reset, and role changes.",
    "manage_triggers": "Get workflows and start flows of type WORKFLOW_MANUAL_START.",
    "manage_webhook": "Create and manage webhooks for a user.",
    "metadata.read": "Read file and folder metadata.",
    "metadata.write": "Create and modify file and folder metadata.",
    "retention.read": "Read retention policies.",
    "retention.write": "Create and modify retention policies.",
    "root_readonly": "Read all files and folders for the authenticated user.",
    "root_readwrite": "Write access for the authenticated user: upload, download, folder creation, and collaboration management.",
    "search": "Search content the user has access to.",
    "sharing.read": "View sharing settings and shared links.",
    "sharing.write": "Create and modify sharing settings and shared links.",
    "sign_requests.readwrite": "Get, create, cancel, and resend sign requests.",
    "tasks.read": "Read tasks assigned to files.",
    "tasks.write": "Create and modify tasks on files.",
    "users.read": "Read user information.",
    "users.write": "Create and modify users.",
    "webhooks.manage": "Create, modify, and delete webhooks.",
  },
  "calendly": {
    "availability.read": "View availability schedules",
    "availability.write": "Modify availability schedules",
    "events.read": "View scheduled events and event details",
    "events.write": "Create, modify, and cancel scheduled events",
    "invitees.read": "View invitee details for scheduled events",
    "organizations.read": "View organization information",
    "organizations.write": "Modify organization settings",
    "scheduling_links.read": "View one-off scheduling links",
    "scheduling_links.write": "Create and manage one-off scheduling links",
    "users.read": "View user profile information",
    "webhooks.read": "View webhook subscriptions",
    "webhooks.write": "Create and manage webhook subscriptions",
  },
  "clickup": {
    "comments.read": "View task and document comments",
    "comments.write": "Create and modify comments",
    "folders.read": "View folders and folder contents",
    "folders.write": "Create and modify folders",
    "goals.read": "View goals and targets",
    "goals.write": "Create and modify goals and targets",
    "lists.read": "View lists within workspaces",
    "lists.write": "Create and modify lists",
    "spaces.read": "View workspace spaces and their data",
    "spaces.write": "Create and modify workspace spaces",
    "tasks.read": "View tasks and task information",
    "tasks.write": "Create, update, and modify tasks",
    "teams.read": "View team and workspace information",
    "time_tracking.read": "View time tracking data",
    "time_tracking.write": "Create and modify time tracking entries",
    "webhooks.write": "Create and manage webhook subscriptions",
  },
  "confluence": {
    "manage:confluence-configuration": "Manage global Confluence settings",
    "read:confluence-content.all": "Read all content, including content body",
    "read:confluence-content.permission": "View content permissions in Confluence",
    "read:confluence-content.summary": "Read a summary of the content, without expansions",
    "read:confluence-groups": "Retrieve user groups",
    "read:confluence-props": "Read content properties",
    "read:confluence-space.summary": "Read a summary of space information",
    "read:confluence-user": "View user information including names, emails, and profile pictures",
    "readonly:content.attachment:confluence": "Download attachments from pages and blogposts",
    "search:confluence": "Search Confluence content",
    "write:confluence-content": "Create pages, blogs, comments, and questions",
    "write:confluence-groups": "Create, remove, and update user groups",
    "write:confluence-props": "Write content properties",
    "write:confluence-space": "Create, update, and delete space information",
    "write:confluence-user": "Modify user information in Confluence",
  },
  "discord": {
    "applications.commands": "Add slash commands to a guild",
    "applications.read": "Read application data and settings",
    "applications.write": "Modify application data and settings",
    "audit_log.read": "View server audit logs and moderation actions",
    "auto_moderation.read": "Read auto-moderation rules and settings",
    "auto_moderation.write": "Create and modify auto-moderation rules",
    "bans.read": "View server bans and banned members",
    "bans.write": "Ban and unban server members",
    "channels.read": "View server channels and their settings",
    "channels.write": "Create and modify server channels",
    "connections": "Access linked third-party accounts on the user's profile",
    "emojis.read": "View server emojis and stickers",
    "emojis.write": "Create and modify server emojis",
    "guilds": "Access basic information about the user's guilds",
    "guilds.members.read": "Read the user's member info in a guild",
    "guilds.read": "View guild information and details",
    "guilds.write": "Modify guild settings and configuration",
    "identify": "Access basic profile info (no email)",
    "interactions.read": "Read interaction and command data",
    "interactions.write": "Create and modify interactions",
    "invites.read": "View server invites and their details",
    "invites.write": "Create and revoke server invites",
    "members.read": "View server member information and roles",
    "members.write": "Modify member roles and server membership",
    "messages.read": "Read messages in client channels",
    "messages.write": "Send and manage messages in server channels",
    "reactions.read": "View message reactions",
    "reactions.write": "Add and remove reactions to messages",
    "role_connections.write": "Update the user's connection metadata for the app",
    "roles.read": "View server roles and their configurations",
    "roles.write": "Create and modify server roles",
    "stickers.read": "View server stickers and sticker packs",
    "stickers.write": "Create and manage server stickers",
    "voice.read": "View voice channel information and members",
    "voice.write": "Move and manage users in voice channels",
    "webhooks.read": "View webhook configurations",
    "webhooks.write": "Create and manage webhooks",
  },
  "dropbox": {
    "account_info.read": "View account information and user details",
    "account_info.write": "Modify account settings and user information",
    "contacts.read": "Read user contacts and contact information",
    "contacts.write": "Create and modify user contacts",
    "dropbox.public": "Access public Dropbox files and folders",
    "email": "Access the user's primary email address",
    "events.read": "Read event logs and activity records",
    "file_requests.read": "View file requests",
    "file_requests.write": "Create and manage file requests",
    "files.content.read": "Read and download file contents",
    "files.content.write": "Upload and modify file contents",
    "files.metadata.read": "Read file and folder metadata",
    "files.metadata.write": "Modify file and folder metadata",
    "files.permanent_delete": "Permanently delete files",
    "files.team_metadata.write": "Modify team file metadata",
    "groups.read": "View group information",
    "groups.write": "Create and modify groups",
    "members.delete": "Remove team members",
    "members.read": "View team member information",
    "members.write": "Manage team member accounts",
    "openid": "Sign in using OpenID Connect",
    "profile": "Access user profile information",
    "sessions.modify": "Manage user sessions",
    "sharing.read": "View sharing settings and links",
    "sharing.write": "Create and modify sharing settings",
    "team_data.content.write": "Write team data content",
    "team_data.governance.read": "Read team governance information",
    "team_data.governance.write": "Modify team governance settings",
    "team_data.member": "Access team member data",
    "team_info.read": "View team information",
  },
  "figma": {
    "current_user:read": "View information about the authenticated user",
    "file_comments:read": "View comments posted on Figma files",
    "file_comments:write": "Create and manage comments on Figma files",
    "file_content:read": "View objects, layers, and their properties in Figma files",
    "file_dev_resources:read": "View dev resources associated with files",
    "file_dev_resources:write": "Manage dev resources for files",
    "file_metadata:read": "Retrieve metadata about Figma files",
    "file_variables:read": "View variables defined within Figma files",
    "file_variables:write": "Create and modify variables in Figma files",
    "file_versions:read": "Access file version history",
    "library_analytics:read": "View analytics data about library usage",
    "library_assets:read": "Access published library assets and components",
    "org:manage_members": "Manage organization members and permissions",
    "org:read": "View organization information",
    "projects:read": "Access project information and structure",
    "webhooks:read": "View configured webhooks",
    "webhooks:write": "Create and manage webhooks",
  },
  "github": {
    "admin:gpg_key": "Fully manage GPG keys.",
    "admin:org": "Fully manage the organization and its teams, projects, and memberships.",
    "admin:org_hook": "Grants read, write, ping, and delete access to organization hooks.",
    "admin:public_key": "Fully manage public keys.",
    "admin:repo_hook": "Grants read, write, ping, and delete access to repository hooks.",
    "admin:ssh_signing_key": "Fully manage SSH signing keys.",
    "codespace": "Grants the ability to create and manage codespaces.",
    "delete:packages": "Grants access to delete packages from GitHub Packages.",
    "delete_repo": "Grants access to delete adminable repositories.",
    "gist": "Grants write access to gists.",
    "github.public": "Limit access to public repositories and public information only.",
    "notifications": "Grants access to notifications, thread subscriptions, and watched repositories.",
    "project": "Grants read/write access to user and organization projects.",
    "public_repo": "Limits access to public repositories: read/write code, statuses, projects, collaborators, and deployment statuses.",
    "read:discussion": "Grants read access to team discussions.",
    "read:gpg_key": "List and view details for GPG keys.",
    "read:org": "Read-only access to organization membership, organization projects, and team membership.",
    "read:packages": "Grants access to download or install packages from GitHub Packages.",
    "read:project": "Grants read-only access to user and organization projects.",
    "read:public_key": "List and view details for public keys.",
    "read:repo_hook": "Grants read and ping access to hooks in repositories.",
    "read:ssh_signing_key": "List and view details for SSH signing keys.",
    "read:user": "Grants access to read a user's profile data.",
    "repo": "Grants full access to public and private repositories: code, commit statuses, invitations, collaborators, deployments, and webhooks.",
    "repo:invite": "Grants accept/decline abilities for invitations to collaborate on a repository.",
    "repo:status": "Grants read/write access to commit statuses in public and private repositories.",
    "repo_deployment": "Grants access to deployment statuses for public and private repositories.",
    "security_events": "Grants read and write access to security events in the code scanning API.",
    "user": "Grants read/write access to profile info only.",
    "user:email": "Grants read access to a user's email addresses.",
    "user:follow": "Grants access to follow or unfollow other users.",
    "workflow": "Grants the ability to add and update GitHub Actions workflow files.",
    "write:discussion": "Grants read and write access to team discussions.",
    "write:gpg_key": "Create, list, and view details for GPG keys.",
    "write:org": "Read and write access to organization membership and organization projects.",
    "write:packages": "Grants access to upload or publish a package in GitHub Packages.",
    "write:public_key": "Create, list, and view details for public keys.",
    "write:repo_hook": "Grants read, write, and ping access to repository hooks.",
    "write:ssh_signing_key": "Create, list, and view details for SSH signing keys.",
  },
  "gitlab": {
    "admin_mode": "Grants permission to perform API actions as an administrator, when Admin Mode is enabled",
    "ai_features": "Grants permission to perform API actions for GitLab Duo",
    "api": "Grants complete read/write access to the API, including all groups and projects, the container registry, the dependency proxy, and the package registry",
    "create_runner": "Grants permission to create runners",
    "email": "Grants read-only access to the user's primary email address using OpenID Connect",
    "k8s_proxy": "Grants permission to perform Kubernetes API calls using the agent for Kubernetes",
    "manage_runner": "Grants permission to manage runners",
    "openid": "Grants permission to authenticate with GitLab using OpenID Connect",
    "profile": "Grants read-only access to the user's profile data using OpenID Connect",
    "read_api": "Grants read access to the API, including all groups and projects, the container registry, and the package registry",
    "read_registry": "Grants read-only access to container registry images on private projects",
    "read_repository": "Grants read-only access to repositories on private projects using Git-over-HTTP or the Repository Files API",
    "read_service_ping": "Grant access to read Service Ping payload through the API",
    "read_user": "Grants read-only access to the authenticated user's profile through the /user API endpoint",
    "sudo": "Grants permission to perform API actions as any user in the system, when authenticated as an administrator",
    "write_registry": "Grants read/write access (push) to container registry images on private projects",
    "write_repository": "Grants read/write access to repositories on private projects using Git-over-HTTP",
  },
  "gmail": {
    "gmail.addons.current.action.compose": "Manage drafts and send emails when you interact with the add-on",
    "gmail.addons.current.message.action": "View your email messages when you interact with the add-on",
    "gmail.addons.current.message.metadata": "View your email message metadata when the add-on is running",
    "gmail.addons.current.message.readonly": "View your email messages when the add-on is running",
    "gmail.compose": "Manage drafts and send emails",
    "gmail.full": "Read, compose, send, and permanently delete all your email from Gmail",
    "gmail.insert": "Add emails into your Gmail mailbox",
    "gmail.labels": "See and edit your email labels",
    "gmail.metadata": "View your email message metadata such as labels and headers, but not the email body",
    "gmail.modify": "Read, compose, and send emails from your Gmail account",
    "gmail.readonly": "View your email messages and settings",
    "gmail.send": "Send email on your behalf",
    "gmail.settings.basic": "See, edit, create, or change your email settings and filters in Gmail",
    "gmail.settings.sharing": "Manage your sensitive mail settings, including who can manage your mail",
  },
  "googlecalendar": {
    "calendar": "See, edit, share, and permanently delete all the calendars you can access using Google Calendar",
    "calendar.acls": "See and change the sharing permissions of Google calendars you own",
    "calendar.acls.readonly": "See the sharing permissions of Google calendars you own",
    "calendar.app.created": "Make secondary Google calendars, and see, create, change, and delete events on them",
    "calendar.calendarlist": "See, add, and remove Google calendars you're subscribed to",
    "calendar.calendarlist.readonly": "See the list of Google calendars you're subscribed to",
    "calendar.calendars": "See and change the properties of Google calendars you have access to, and create secondary calendars",
    "calendar.calendars.readonly": "See the title, description, default time zone, and other properties of Google calendars you have access to",
    "calendar.events": "View and edit events on all your calendars",
    "calendar.events.freebusy": "See the availability on Google calendars you have access to",
    "calendar.events.owned": "See, create, change, and delete events on Google calendars you own",
    "calendar.events.owned.readonly": "See the events on Google calendars you own",
    "calendar.events.public.readonly": "See the events on public calendars",
    "calendar.events.readonly": "View events on all your calendars",
    "calendar.freebusy": "View your availability in your calendars",
    "calendar.readonly": "See and download any calendar you can access using your Google Calendar",
    "calendar.settings.readonly": "View your Calendar settings",
  },
  "googledocs": {
    "documents": "See, edit, create, and delete all your Google Docs documents",
    "documents.readonly": "View your Google Docs documents",
    "drive": "See, edit, create, and delete all of your Google Drive files",
    "drive.file": "See, edit, create, and delete only the specific Google Drive files you use with this app",
    "drive.readonly": "View the files in your Google Drive",
  },
  "googledrive": {
    "drive": "See, edit, create, and delete all of your Google Drive files",
    "drive.appdata": "View and manage its own configuration data in your Google Drive",
    "drive.apps.readonly": "View your Google Drive apps",
    "drive.file": "See, edit, create, and delete only the specific Google Drive files you use with this app",
    "drive.meet.readonly": "View your Google Meet recordings in Google Drive",
    "drive.metadata": "View and manage metadata of files in your Google Drive",
    "drive.metadata.readonly": "View metadata for files in your Google Drive",
    "drive.photos.readonly": "View photos and videos in your Google Photos",
    "drive.readonly": "View the files in your Google Drive",
    "drive.scripts": "Modify your Google Apps Script projects' metadata",
  },
  "googlemeet": {
    "meetings.space.created": "View spaces created by this app in Google Meet",
    "meetings.space.readonly": "View your Google Meet spaces and their settings",
    "meetings.space.settings": "View and edit your Google Meet spaces and their settings",
  },
  "googlesheets": {
    "drive": "See, edit, create, and delete all of your Google Drive files",
    "drive.file": "See, edit, create, and delete only the specific Google Drive files you use with this app",
    "drive.readonly": "View the files in your Google Drive",
    "spreadsheets": "See, edit, create, and delete all your Google Sheets spreadsheets",
    "spreadsheets.readonly": "View your Google Sheets spreadsheets",
  },
  "googleslides": {
    "drive": "See, edit, create, and delete all of your Google Drive files",
    "drive.file": "See, edit, create, and delete only the specific Google Drive files you use with this app",
    "drive.readonly": "View the files in your Google Drive",
    "presentations": "See, edit, create, and delete all your Google Slides presentations",
    "presentations.readonly": "View your Google Slides presentations",
  },
  "googletasks": {
    "tasks": "Create and edit your tasks in Google Tasks",
    "tasks.readonly": "View your tasks in Google Tasks",
  },
  "hubspot": {
    "automation": "Access to workflows through the Automation API.",
    "content": "Access to sites, landing pages, email, blog, campaigns, and related endpoints.",
    "conversations.read": "View details about threads in the conversations inbox.",
    "conversations.write": "Send messages in conversations and create/update message threads.",
    "crm.lists.read": "View details about contact lists.",
    "crm.lists.write": "Create, delete, or make changes to contact lists.",
    "crm.objects.calls.read": "View call records and call data on CRM records.",
    "crm.objects.calls.write": "Create and modify call records on CRM records.",
    "crm.objects.companies.read": "View properties and other details about companies.",
    "crm.objects.companies.write": "View properties and create, delete, or make changes to companies.",
    "crm.objects.contacts.read": "View properties and other details about contacts.",
    "crm.objects.contacts.write": "View properties and create, delete, and make changes to contacts.",
    "crm.objects.deals.read": "View properties and other details about deals.",
    "crm.objects.deals.write": "View properties and create, delete, or make changes to deals.",
    "crm.objects.emails.read": "View email engagements on CRM records.",
    "crm.objects.emails.write": "Create and modify email engagements on CRM records.",
    "crm.objects.meetings.read": "View meeting records on CRM records.",
    "crm.objects.meetings.write": "Create and modify meeting records on CRM records.",
    "crm.objects.notes.read": "View notes attached to CRM records.",
    "crm.objects.notes.write": "Create and modify notes on CRM records.",
    "crm.objects.owners.read": "View details about users assigned to a CRM record.",
    "crm.objects.tasks.read": "View tasks on CRM records.",
    "crm.objects.tasks.write": "Create and modify tasks on CRM records.",
    "crm.schemas.companies.read": "View details about property settings for companies.",
    "crm.schemas.contacts.read": "View details about property settings for contacts.",
    "crm.schemas.contacts.write": "Create, delete, or make changes to property settings for contacts.",
    "crm.schemas.deals.read": "View details about property settings for deals.",
    "e-commerce": "Access to e-commerce features including products and line items.",
    "files": "Access to File Manager including files and file mapper endpoints.",
    "files.ui_hidden.read": "View details or download user files, attachments, and system files from HubSpot.",
    "forms": "Access to forms data and form submissions.",
    "forms-uploaded-files": "Access to files uploaded through forms.",
    "sales-email-read": "View sales emails sent from HubSpot.",
    "tickets": "Read and write access to tickets in the conversations and CRM tools.",
    "timeline": "Access to add events to the CRM activity timeline.",
  },
  "instagram": {
    "business_management": "Read and write Business Manager assets such as ad accounts",
    "instagram_basic": "Read an Instagram account profile's basic info and media",
    "instagram_content_publish": "Create organic feed photo and video posts on behalf of a business user",
    "instagram_manage_comments": "Create, delete, and hide comments on the linked Instagram account",
    "instagram_manage_insights": "Read insights for the linked Instagram Business account",
    "instagram_shopping_tag_products": "Tag Instagram media with product tags and appeal rejections",
    "pages_read_engagement": "Read Page content, follower data, and engagement metadata",
    "pages_show_list": "Access the list of Facebook Pages a person manages",
  },
  "intercom": {
    "admins.read": "List and view all admins",
    "articles.read": "List and view articles",
    "articles.write": "Create and update articles",
    "companies.read": "List and view companies",
    "companies.write": "Create and update companies",
    "contacts.read": "List and view contacts and users",
    "contacts.write": "Create and update users and contacts",
    "conversations.read": "View conversations",
    "conversations.write": "Reply to, mark as read, and close conversations",
    "data_attributes.read": "View custom data attributes",
    "data_attributes.write": "Create and update custom data attributes",
    "events.read": "List events belonging to a user",
    "events.write": "Submit events (user activity)",
    "help_center.read": "View help center collections and content",
    "help_center.write": "Create and modify help center content",
    "messages.write": "Send messages to users",
    "segments.read": "List and view segments",
    "tags.read": "List all tags",
    "tags.write": "Create, update, use, and delete tags",
    "teams.read": "List and view teams",
  },
  "linear": {
    "admin": "Full access to admin-level endpoints",
    "comments:create": "Create new issue comments",
    "customer:read": "View customer records",
    "customer:write": "Create and modify customer records",
    "initiative:read": "View initiatives and their contents",
    "initiative:write": "Create and modify initiatives",
    "issues:create": "Create new issues and their attachments",
    "read": "Read access to the user's account",
    "timeSchedule:write": "Create and modify time schedules",
    "write": "Write access to the user's account",
  },
  "linkedin": {
    "email": "Access the user's primary email address",
    "openid": "Sign in with LinkedIn using OpenID Connect",
    "profile": "Access basic profile information (name, photo, headline)",
    "r_1st_connections_size": "Read the size of the user's 1st-degree connections",
    "r_ads": "Read advertising account data",
    "r_ads_reporting": "Read advertising performance reports",
    "r_basicprofile": "Read basic profile information including headline and current position",
    "r_emailaddress": "Read the user's primary email address",
    "r_liteprofile": "Read basic profile information (name, photo)",
    "r_member_social": "Read the user's posts, comments, and likes",
    "r_organization_followers": "Read follower data for managed organizations",
    "r_organization_social": "Read posts, comments, and likes for managed organizations",
    "rw_ads": "Read and write advertising account data",
    "rw_organization_admin": "Read and write organization page admin data",
    "w_member_social": "Post, comment, and react on the user's behalf",
    "w_organization_social": "Post, comment, and react on behalf of managed organizations",
  },
  "mailchimp": {
    "accounts.read": "View account information and settings",
    "automations.read": "View automation workflows and settings",
    "automations.write": "Create and manage automated marketing workflows",
    "campaigns.read": "View campaign details and historical data",
    "campaigns.write": "Create, edit, and manage marketing campaigns",
    "files.read": "View uploaded files and assets",
    "files.write": "Upload and manage files and assets",
    "lists.read": "View audience lists and their configurations",
    "lists.write": "Create, modify, and manage audience lists",
    "members.read": "View contact and audience member information",
    "members.write": "Add, update, and manage audience member data",
    "reports.read": "View campaign performance and analytics reports",
    "segments.read": "View audience segments and filtering criteria",
    "segments.write": "Create and modify audience segments",
    "templates.read": "View email templates and designs",
    "templates.write": "Create and modify email templates",
  },
  "microsoft_teams": {
    "AppCatalog.Read.All": "Read all app catalogs",
    "AppCatalog.ReadWrite.All": "Read and write to all app catalogs",
    "Channel.Create": "Create channels",
    "Channel.Delete.All": "Delete channels",
    "Channel.ReadBasic.All": "Read the names and descriptions of channels",
    "ChannelMember.Read.All": "Read the members of channels",
    "ChannelMember.ReadWrite.All": "Add and remove members from channels",
    "ChannelMessage.Read.All": "Read user channel messages",
    "ChannelMessage.Send": "Send channel messages",
    "ChannelSettings.Read.All": "Read the names, descriptions, and settings of channels",
    "ChannelSettings.ReadWrite.All": "Read and write the names, descriptions, and settings of channels",
    "Chat.Create": "Create chats",
    "Chat.Read": "Read user chat messages",
    "Chat.ReadWrite": "Read and write user chat messages",
    "ChatMember.Read": "Read the members of chats",
    "ChatMember.ReadWrite": "Add and remove members from chats",
    "ChatMessage.Read": "Read user chat messages",
    "ChatMessage.Send": "Send user chat messages",
    "Files.Read.All": "Read files in all site collections",
    "Files.ReadWrite.All": "Read and write files in all site collections",
    "Group.ReadWrite.All": "Read and write all groups",
    "OnlineMeetingArtifact.Read.All": "Read online meeting artifacts",
    "OnlineMeetings.Read": "Read online meeting properties",
    "OnlineMeetings.ReadWrite": "Read and write online meetings",
    "Presence.Read": "Read user presence information",
    "Presence.Read.All": "Read presence information of all users",
    "Presence.ReadWrite": "Read and write user presence information",
    "Schedule.Read.All": "Read all shifts schedules",
    "Schedule.ReadWrite.All": "Read and write all shifts schedules",
    "Team.Create": "Create teams",
    "Team.ReadBasic.All": "Read basic properties of all teams",
    "TeamMember.Read.All": "Read members of all teams",
    "TeamMember.ReadWrite.All": "Add and remove members from all teams",
    "TeamSettings.Read.All": "Read all team settings",
    "TeamSettings.ReadWrite.All": "Read and write all team settings",
    "TeamsActivity.Send": "Send activity feed notifications to users",
    "TeamsAppInstallation.ReadForChat": "Read installed apps for chats",
    "TeamsAppInstallation.ReadForTeam": "Read installed apps for teams",
    "TeamsAppInstallation.ReadForUser": "Read installed apps for users",
    "TeamsAppInstallation.ReadWriteForChat": "Manage installed apps for chats",
    "TeamsAppInstallation.ReadWriteForTeam": "Manage installed apps for teams",
    "TeamsAppInstallation.ReadWriteForUser": "Manage installed apps for users",
    "TeamsTab.Read.All": "Read all teams tabs",
    "TeamsTab.ReadWrite.All": "Read and write all teams tabs",
    "Teamwork.Migrate.All": "Migrate team data to Microsoft Teams",
    "TeamworkTag.Read": "Read all teamwork tags",
    "TeamworkTag.ReadWrite": "Read and write all teamwork tags",
  },
  "monday": {
    "account:read": "Read general information about the account",
    "assets:read": "Read data from assets the user has access to",
    "boards:read": "Read the user's board data",
    "boards:write": "Modify the user's board data",
    "docs:read": "Read the user's docs",
    "docs:write": "Modify the user's docs",
    "me:read": "Read the user's profile information",
    "notifications:write": "Send notifications on behalf of the user",
    "tags:read": "Read the account's tags",
    "teams:read": "Read information about the account's teams",
    "teams:write": "Modify the account's teams",
    "updates:read": "Read updates and replies the user can see",
    "updates:write": "Post or edit updates on behalf of the user",
    "users:read": "Read profile information of the account's users",
    "users:write": "Modify profile information of the account's users",
    "webhooks:read": "Read existing webhooks configuration",
    "webhooks:write": "Create and modify webhooks",
    "workspaces:read": "Read the user's workspaces data",
    "workspaces:write": "Modify the user's workspaces data",
  },
  "notion": {
    "insert_comments": "Post new comments on pages and database items",
    "insert_content": "Create new pages and database entries in the workspace",
    "read_comments": "Read comments on pages and database items",
    "read_content": "Read pages, databases, and other content from the workspace",
    "read_user_information": "View workspace user profile information",
    "update_content": "Modify existing pages, databases, and content properties",
  },
  "outlook": {
    "Calendars.Read": "Read user calendars",
    "Calendars.ReadWrite": "Have full access to user calendars",
    "Contacts.Read": "Read user contacts",
    "Contacts.ReadWrite": "Have full access to user contacts",
    "Mail.Read": "Read user mail",
    "Mail.ReadBasic": "Read basic properties of user mailbox",
    "Mail.ReadWrite": "Read and write access to user mail",
    "Mail.Send": "Send mail as a user",
    "MailboxSettings.Read": "Read user mailbox settings",
    "MailboxSettings.ReadWrite": "Read and write user mailbox settings",
  },
  "quickbooks": {
    "accounting.read": "Read access to QuickBooks accounting data (customers, vendors, invoices, accounts)",
    "accounting.write": "Read and write access to QuickBooks accounting data",
    "payment.read": "Read access to QuickBooks Payments data (charges, refunds, tokens)",
    "payment.write": "Read and write access to QuickBooks Payments data",
  },
  "salesforce": {
    "analytics.read": "Read Analytics (Wave/CRM Analytics) data.",
    "api": "Access the current logged-in user's account using APIs, such as REST API and Bulk API 2.0.",
    "chatter.read": "Read Chatter feeds, comments, and posts.",
    "chatter.write": "Post and modify Chatter content.",
    "chatter_api": "Access Connect REST API resources on behalf of the user.",
    "content": "Access content child sessions for hybrid apps.",
    "custom_permissions": "Access custom permissions associated with the connected app.",
    "full": "Full access to all data accessible by the logged-in user.",
    "id": "Access the identity URL service.",
    "manage_user_data": "Manage user data on behalf of the user.",
    "metadata.read": "Read Salesforce metadata via the Metadata API.",
    "offline_access": "Receive a refresh token to access data while the user is offline.",
    "openid": "Access the current logged-in user's unique identifier for OpenID Connect apps.",
    "pardot_api": "Access Marketing Cloud Account Engagement (Pardot) API services on behalf of the user.",
    "query": "Run SOQL queries against Salesforce data.",
    "refresh_token": "Receive a refresh token to obtain new access tokens without re-login.",
    "search": "Run SOSL searches against Salesforce data.",
    "sobjects.delete": "Delete Salesforce objects (sObjects) via the REST API.",
    "sobjects.read": "Read Salesforce objects (sObjects) via the REST API.",
    "sobjects.write": "Create and update Salesforce objects (sObjects) via the REST API.",
    "visualforce": "Access customer-created Visualforce pages.",
    "wave_api": "Access the Analytics REST API resources.",
    "web": "Use the access_token on the web.",
  },
  "sentry": {
    "alerts:read": "Read alert rules and triggers",
    "alerts:write": "Create and modify alert rules",
    "event:admin": "Delete access for issues and events",
    "event:read": "Read access for issues and events",
    "event:write": "Update issues and events",
    "member:admin": "Delete organization members",
    "member:read": "Read organization members",
    "member:write": "Add or modify organization members",
    "org:admin": "Delete organizations",
    "org:read": "Read organization details",
    "org:write": "Modify organization details",
    "project:admin": "Delete projects",
    "project:read": "Read project details",
    "project:releases": "Read and write access for project and organization release endpoints",
    "project:write": "Modify project details",
    "release:admin": "Delete releases across the organization",
    "release:read": "Read release details",
    "release:write": "Create and modify releases",
    "team:admin": "Delete teams",
    "team:read": "Read team details",
    "team:write": "Modify team details",
  },
  "slack": {
    "admin": "Allows applications to perform administrative actions, requires the authed user to be an admin.",
    "authorizations:read": "View authorizations for an app",
    "bookmarks:read": "View bookmarks in a workspace",
    "bookmarks:write": "Manage bookmarks in a workspace",
    "calls:read": "View call information",
    "calls:write": "Manage calls",
    "canvases:read": "View canvases",
    "canvases:write": "Manage canvases",
    "channels:history": "View message history in public channels",
    "channels:join": "Join public channels",
    "channels:manage": "Manage public channels",
    "channels:read": "View information about public channels",
    "channels:write.invites": "Invite users to public channels",
    "chat:write": "Post messages to channels and direct messages",
    "chat:write.customize": "Send messages with a customized username and avatar",
    "chat:write.public": "Post messages in public channels without joining",
    "connections:write": "Manage app connections",
    "conversations:connect:manage": "Manage Slack Connect channels",
    "conversations:connect:read": "View Slack Connect channel information",
    "dnd:read": "View do not disturb status",
    "dnd:write": "Manage do not disturb status",
    "emoji:read": "View custom emoji",
    "files:read": "View files in a workspace",
    "files:write": "Manage files",
    "groups:history": "View message history in private channels",
    "groups:read": "View information about private channels",
    "groups:write": "Manage private channels",
    "groups:write.invites": "Invite users to private channels",
    "identity.basic": "View basic identity (name, ID) of the signed-in user",
    "im:history": "View message history in direct messages",
    "im:read": "View direct message information",
    "im:write": "Manage direct messages",
    "links:read": "View links shared in messages",
    "links:write": "Manage message unfurls",
    "metadata.message:read": "View message metadata",
    "mpim:history": "View message history in group direct messages",
    "mpim:read": "View group direct message information",
    "mpim:write": "Manage group direct messages",
    "openid": "Sign in with Slack using OpenID Connect",
    "pins:read": "View pinned messages",
    "pins:write": "Manage pinned messages",
    "reactions:read": "View emoji reactions",
    "reactions:write": "Manage emoji reactions",
    "reminders:read": "View reminders",
    "reminders:write": "Manage reminders",
    "remote_files:read": "View remote file information",
    "remote_files:share": "Share remote files",
    "remote_files:write": "Manage remote files",
    "rtm:stream": "Connect to the real-time messaging stream",
    "search:read": "Search messages and files",
    "slack.public": "Access public workspace data",
    "stars:read": "View starred items",
    "stars:write": "Manage starred items",
    "team:read": "View workspace information",
    "tokens.basic": "Basic token operations",
    "usergroups:read": "View user groups",
    "usergroups:write": "Manage user groups",
    "users.profile:read": "View user profiles",
    "users.profile:write": "Manage user profiles",
    "users:read": "View people in a workspace",
    "users:read.email": "View user email addresses",
    "users:write": "Manage user status",
  },
  "stripe": {
    "accounts.read": "Read connected account information",
    "accounts.write": "Create and modify connected accounts",
    "balance.read": "Read account balance information",
    "charges.read": "Read charge records",
    "charges.write": "Create and modify charges",
    "checkout_sessions.read": "Read Checkout sessions",
    "checkout_sessions.write": "Create Checkout sessions",
    "coupons.read": "Read coupon records",
    "coupons.write": "Create and modify coupons",
    "customers.read": "Read customer records",
    "customers.write": "Create and modify customers",
    "disputes.read": "Read dispute records",
    "disputes.write": "Respond to and modify disputes",
    "events.read": "Read event log",
    "files.read": "Read file records",
    "files.write": "Upload and modify files",
    "invoices.read": "Read invoice records",
    "invoices.write": "Create and modify invoices",
    "payment_intents.read": "Read payment intent records",
    "payment_intents.write": "Create and modify payment intents",
    "payment_methods.read": "Read payment method records",
    "payment_methods.write": "Create and modify payment methods",
    "payouts.read": "Read payout records",
    "payouts.write": "Create and modify payouts",
    "prices.read": "Read price records",
    "prices.write": "Create and modify prices",
    "products.read": "Read product records",
    "products.write": "Create and modify products",
    "refunds.read": "Read refund records",
    "refunds.write": "Create refunds",
    "setup_intents.read": "Read setup intent records",
    "setup_intents.write": "Create and modify setup intents",
    "subscriptions.read": "Read subscription records",
    "subscriptions.write": "Create and modify subscriptions",
    "transfers.read": "Read transfer records",
    "transfers.write": "Create and modify transfers",
    "webhook_endpoints.read": "Read webhook endpoints",
    "webhook_endpoints.write": "Create and modify webhook endpoints",
  },
  "trello": {
    "account": "Read member email, modify member info, and mark notifications read",
    "read": "Read boards, organizations, and other Trello resources on behalf of the user",
    "write": "Write boards, organizations, and other Trello resources on behalf of the user",
  },
  "typeform": {
    "accounts:read": "Retrieve basic information from your Typeform account",
    "forms:read": "Retrieve forms from your Typeform account",
    "forms:write": "Create, update, and delete forms",
    "images:read": "Retrieve images and image metadata",
    "images:write": "Upload and delete images",
    "offline": "Receive a refresh token for long-lived access",
    "responses:read": "Read form responses and submission information",
    "responses:write": "Delete form responses and submission information",
    "themes:read": "Retrieve themes",
    "themes:write": "Create, update, and delete themes",
    "webhooks:read": "Retrieve webhook configuration and delivery data",
    "webhooks:write": "Create, update, and delete webhooks",
    "workspaces:read": "Retrieve workspaces",
    "workspaces:write": "Create, update, and delete workspaces",
  },
  "xero": {
    "accounting.attachments": "Read and write attachments on accounting records",
    "accounting.attachments.read": "Read attachments on accounting records",
    "accounting.contacts": "Read and write contacts",
    "accounting.contacts.read": "Read contacts",
    "accounting.journals.read": "Read accounting journals",
    "accounting.reports.read": "Read accounting reports (P&L, balance sheet, etc.)",
    "accounting.settings": "Read and write organisation settings (chart of accounts, tax rates, tracking categories)",
    "accounting.settings.read": "Read organisation settings",
    "accounting.transactions": "Read and write business transactions (invoices, bank transactions, manual journals)",
    "accounting.transactions.read": "Read business transactions (invoices, bank transactions, manual journals)",
    "assets": "Read and write fixed assets",
    "assets.read": "Read fixed assets",
    "bankfeeds": "Read and write bankfeeds data",
    "email": "Access the user's email address",
    "files": "Read and write files in the Xero Files inbox",
    "files.read": "Read files in the Xero Files inbox",
    "openid": "Sign in to Xero using OpenID Connect",
    "payroll.employees": "Read and write payroll employee records",
    "payroll.employees.read": "Read payroll employee records",
    "payroll.payslip": "Read and write payslips",
    "payroll.payslip.read": "Read payslips",
    "payroll.timesheets": "Read and write payroll timesheets",
    "payroll.timesheets.read": "Read payroll timesheets",
    "profile": "Access user profile (name, surname)",
    "projects": "Read and write Xero Projects data",
    "projects.read": "Read Xero Projects data",
  },
  "youtube": {
    "youtube": "Manage your YouTube account",
    "youtube.channel-memberships.creator": "See a list of your YouTube channel members",
    "youtube.force-ssl": "View and manage your YouTube account",
    "youtube.public": "View your YouTube account",
    "youtube.readonly": "View your YouTube account",
    "youtube.upload": "Upload videos to your YouTube channel",
    "youtubepartner": "View and manage your YouTube content and account",
    "youtubepartner-channel-audit": "View YouTube Analytics and reporting information",
  },
  "zendesk": {
    "hc:read": "Provides read-only access to help center resources",
    "hc:write": "Enables creation, modification, and deletion of help center content",
    "impersonate": "Allows Zendesk Support admins to make requests on behalf of end users",
    "organizations:read": "Provides read-only access to organization resources",
    "organizations:write": "Enables creation, modification, and deletion of organizations",
    "read": "Gives access to GET endpoints. Includes permission to sideload related resources",
    "tickets:read": "Provides read-only access to ticket resources",
    "tickets:write": "Enables creation, modification, and deletion of tickets",
    "users:read": "Provides read-only access to user resources",
    "users:write": "Enables creation, modification, and deletion of user records",
    "write": "Gives access to POST, PUT, and DELETE endpoints",
  },
  "zoom": {
    "account:read": "View account information",
    "account:write": "Modify account settings",
    "chat_channel:read": "View chat channels",
    "chat_channel:write": "Create and manage chat channels",
    "chat_message:read": "View chat messages",
    "chat_message:write": "Send and manage chat messages",
    "contact:read": "View contact information",
    "contact:write": "Manage contacts",
    "dashboard:read": "Access dashboard data and metrics",
    "group:read": "View group information",
    "group:write": "Create and manage groups",
    "meeting:read": "View meeting information and details",
    "meeting:write": "Create, modify, and manage meetings",
    "phone:read": "View Zoom Phone information",
    "phone:write": "Manage Zoom Phone settings and configuration",
    "recording:read": "Access cloud recordings",
    "recording:write": "Manage and delete cloud recordings",
    "report:read": "View reports and analytics",
    "user:read": "View user profile and account information",
    "user:write": "Modify user profile and account settings",
    "webinar:read": "View webinar information and details",
    "webinar:write": "Create, modify, and manage webinars",
  },
}
