import { BrowserWindow, session, type WebContents } from 'electron'
import { buildDashboardViewUrl } from '@shared/lib/dashboard-url'
import { safeOpenExternal } from './safe-open-external'

// Open dashboard popouts, keyed by API base URL + `${agentSlug}/${dashboardSlug}`.
// The base URL is part of the identity, not decoration: two deployments can hold
// an agent of the same slug, and reusing a window across them would show the
// wrong one's dashboard under the right one's name. The raw join is fine as a
// dedup key — only the loaded URL needs per-segment encoding.
const dashboardWindows: Map<string, BrowserWindow> = new Map()

/**
 * Deny-and-route popup policy for a window's webContents.
 *
 * Applied to both the main window and the agent-generated dashboard popouts so
 * untrusted dashboard content cannot spawn arbitrary child windows via
 * window.open(). File-download URLs are streamed via downloadURL; other URLs go
 * to the system browser via safeOpenExternal, which scheme-validates first so a
 * popup can't ask the OS shell to launch file:/javascript:/custom-protocol
 * handlers (SUP-214). The popup itself is always denied (SUP-219).
 */
export function installPopupHandler(webContents: WebContents) {
  webContents.setWindowOpenHandler(({ url }) => {
    // Handle file download URLs - download directly without opening a popup
    if (url.includes('/api/agents/') && url.includes('/files/')) {
      webContents.downloadURL(url)
      return { action: 'deny' }
    }
    // For other URLs (OAuth, external links), open in the system browser after
    // scheme validation (SUP-214). Fire-and-forget; the popup is denied either way.
    void safeOpenExternal(url)
    return { action: 'deny' }
  })
}

/**
 * The origin and the path a cloud base URL adds ahead of `/api/…`, or null for
 * a local base URL (a bare origin, so nothing to add) and for anything
 * unparseable.
 */
function proxyRouteOf(apiBaseUrl: string): { origin: string; prefix: string } | null {
  try {
    const url = new URL(apiBaseUrl)
    const prefix = url.pathname.replace(/\/+$/, '')
    return prefix ? { origin: url.origin, prefix } : null
  } catch {
    return null
  }
}

/**
 * Keep every request this window makes inside the cloud proxy.
 *
 * Only the document URL we hand to `loadURL` carries the proxy prefix. The
 * wrapper the deployment serves back builds its own calls from a root-relative
 * `basePath` (`/api/agents/{slug}`, see the `/view` route in api/routes/agents.ts),
 * and its iframe from the same — so its status poll, its start-the-agent POST
 * and the dashboard itself would resolve against the laptop's own API. That is
 * the original wrong-deployment bug, one layer in: the popout window looks
 * right and drives the local Superagent.
 *
 * Rewriting here rather than in the wrapper is deliberate. The wrapper is
 * generated by the *deployment*, so a fix there only reaches workspaces new
 * enough to have it, and this has to hold against whatever version an
 * organization is running. It also catches URLs however the document builds
 * them, without anyone parsing agent-generated HTML.
 *
 * The listener goes on a per-window partition. On the default session it would
 * rewrite the main window's requests too.
 */
function confineToProxy(partition: string, { origin, prefix }: { origin: string; prefix: string }): void {
  session.fromPartition(partition).webRequest.onBeforeRequest(
    { urls: [`${origin}/*`] },
    (details, callback) => {
      const rest = details.url.slice(origin.length)
      // Already inside the proxy, or not an API call at all: leave it alone.
      // The prefix check keeps this idempotent, including across redirects.
      if (rest.startsWith(`${prefix}/`) || !rest.startsWith('/api/')) {
        callback({})
        return
      }
      callback({ redirectURL: `${origin}${prefix}${rest}` })
    },
  )
}

/**
 * `apiBaseUrl` is the base of whichever Superagent the app is currently
 * driving — the local API, or the cloud proxy prefix on it. Popouts are built
 * in main, so they have to be told; a hard-coded local origin opens a dashboard
 * belonging to a different deployment's agent of the same name.
 */
export function openDashboardWindow(agentSlug: string, dashboardSlug: string, apiBaseUrl: string) {
  const key = `${apiBaseUrl}|${agentSlug}/${dashboardSlug}`

  // Focus existing window if already open
  const existing = dashboardWindows.get(key)
  if (existing && !existing.isDestroyed()) {
    existing.show()
    existing.focus()
    return
  }

  // Cloud popouts get their own session so the request rewrite above cannot
  // touch anything else. Local ones keep the default session, exactly as before.
  const route = proxyRouteOf(apiBaseUrl)
  const partition = route ? `cloud-dashboard:${route.prefix}` : undefined
  if (route && partition) confineToProxy(partition, route)

  const url = buildDashboardViewUrl(apiBaseUrl, agentSlug, dashboardSlug)
  const win = new BrowserWindow({
    width: 1000,
    height: 700,
    title: 'Gamut Dashboard',
    webPreferences: {
      contextIsolation: true,
      nodeIntegration: false,
      ...(partition ? { partition } : {}),
    },
  })
  // Dashboard content is agent-generated/untrusted — apply the same deny-and-route
  // popup policy as the main window so window.open() can't spawn child windows.
  installPopupHandler(win.webContents)
  // A cloud popout is otherwise indistinguishable from a local one: same chrome,
  // and the wrapper replaces the generic title with the dashboard's own name.
  // The title is the only surface main owns here — injecting a frame would mean
  // writing into an agent-generated document — so it carries the marker.
  if (route) {
    win.on('page-title-updated', (event, title) => {
      event.preventDefault()
      win.setTitle(`Cloud workspace — ${title}`)
    })
  }
  win.loadURL(url)
  dashboardWindows.set(key, win)
  win.on('closed', () => dashboardWindows.delete(key))
}

export function closeAllDashboardWindows() {
  for (const win of dashboardWindows.values()) {
    if (!win.isDestroyed()) win.close()
  }
  dashboardWindows.clear()
}
