/**
 * Common remote MCP servers directory.
 * This is the master list of well-known MCP servers that users can connect.
 */

export interface CommonMcpServer {
  slug: string
  displayName: string
  description: string
  url: string
  authType: 'none' | 'oauth' | 'bearer'
  category: string
}

export const COMMON_MCP_SERVERS: CommonMcpServer[] = [
  // CRM, Sales & Customer Support
  {
    slug: 'attio',
    displayName: 'Attio',
    description: 'AI-native CRM — deals, tasks, lists, people, companies',
    url: 'https://mcp.attio.com/mcp',
    authType: 'oauth',
    category: 'CRM & Sales',
  },
  {
    slug: 'close',
    displayName: 'Close CRM',
    description: 'Sales CRM — leads, contacts, opportunities, activities',
    url: 'https://mcp.close.com/mcp',
    authType: 'oauth',
    category: 'CRM & Sales',
  },
  {
    slug: 'intercom',
    displayName: 'Intercom',
    description: 'Customer support — conversations, contacts, tickets',
    url: 'https://mcp.intercom.com/mcp',
    authType: 'oauth',
    category: 'CRM & Sales',
  },

  // Project Management & Productivity
  {
    slug: 'linear',
    displayName: 'Linear',
    description: 'Engineering project management — issues, projects, milestones',
    url: 'https://mcp.linear.app/mcp',
    authType: 'oauth',
    category: 'Project Management',
  },
  {
    slug: 'atlassian',
    displayName: 'Atlassian (Jira/Confluence)',
    description: 'Jira issues, Confluence pages, JSM',
    url: 'https://mcp.atlassian.com/v1/mcp',
    authType: 'oauth',
    category: 'Project Management',
  },
  {
    slug: 'notion',
    displayName: 'Notion',
    description: 'Pages, docs, databases, tasks, universal search',
    url: 'https://mcp.notion.com/mcp',
    authType: 'oauth',
    category: 'Project Management',
  },
  {
    slug: 'clickup',
    displayName: 'ClickUp',
    description: 'Tasks, lists, folders, spaces, docs, time tracking',
    url: 'https://mcp.clickup.com/mcp',
    authType: 'oauth',
    category: 'Project Management',
  },
  {
    slug: 'monday',
    displayName: 'Monday.com',
    description: 'Board management, item operations, GraphQL access',
    url: 'https://mcp.monday.com/mcp',
    authType: 'oauth',
    category: 'Project Management',
  },
  {
    slug: 'airtable',
    displayName: 'Airtable',
    description: 'Record CRUD, base/table listing, search, schema inspection',
    url: 'https://mcp.airtable.com/mcp',
    authType: 'none',
    category: 'Project Management',
  },
  {
    slug: 'webflow',
    displayName: 'Webflow',
    description: 'CMS management, SEO, content localization, publishing',
    url: 'https://mcp.webflow.com/sse',
    authType: 'oauth',
    category: 'Project Management',
  },
  {
    slug: 'wix',
    displayName: 'Wix',
    description: 'Website builder and content management',
    url: 'https://mcp.wix.com/sse',
    authType: 'oauth',
    category: 'Project Management',
  },

  // Communication & Meetings
  {
    slug: 'granola',
    displayName: 'Granola',
    description: 'AI meeting notes — search meetings, topics, action items',
    url: 'https://mcp.granola.ai/mcp',
    authType: 'oauth',
    category: 'Communication',
  },
  {
    slug: 'telnyx',
    displayName: 'Telnyx',
    description: 'Communications API — voice, SMS, messaging',
    url: 'https://api.telnyx.com/v2/mcp',
    authType: 'bearer',
    category: 'Communication',
  },
  {
    slug: 'dialmcp',
    displayName: 'DialMCP',
    description: 'Place phone calls from your number with transcripts and recordings',
    url: 'https://mcp.dialmcp.com/mcp',
    authType: 'oauth',
    category: 'Communication',
  },
  {
    slug: 'dialer',
    displayName: 'Dialer',
    description: 'Outbound phone calls',
    url: 'https://getdialer.app/sse',
    authType: 'oauth',
    category: 'Communication',
  },

  // Developer Tools & Infrastructure
  {
    slug: 'sentry',
    displayName: 'Sentry',
    description: 'Error monitoring — issues, stack traces, AI analysis',
    url: 'https://mcp.sentry.dev/mcp',
    authType: 'oauth',
    category: 'Developer Tools',
  },
  {
    slug: 'vercel',
    displayName: 'Vercel',
    description: 'Deployments, environment variables, domains, project controls',
    url: 'https://mcp.vercel.com/',
    authType: 'oauth',
    category: 'Developer Tools',
  },
  {
    slug: 'cloudflare',
    displayName: 'Cloudflare API',
    description: 'Full Cloudflare API — 2,500+ endpoints via Code Mode',
    url: 'https://mcp.cloudflare.com/mcp',
    authType: 'oauth',
    category: 'Developer Tools',
  },
  {
    slug: 'cloudflare-workers',
    displayName: 'Cloudflare Workers',
    description: 'Build Workers apps with KV/R2/D1/AI',
    url: 'https://bindings.mcp.cloudflare.com/sse',
    authType: 'oauth',
    category: 'Developer Tools',
  },
  {
    slug: 'cloudflare-observability',
    displayName: 'Cloudflare Observability',
    description: 'Debug apps via logs and analytics',
    url: 'https://observability.mcp.cloudflare.com/sse',
    authType: 'oauth',
    category: 'Developer Tools',
  },
  {
    slug: 'cloudflare-radar',
    displayName: 'Cloudflare Radar',
    description: 'Global internet traffic insights',
    url: 'https://radar.mcp.cloudflare.com/mcp',
    authType: 'oauth',
    category: 'Developer Tools',
  },
  {
    slug: 'neon',
    displayName: 'Neon',
    description: 'Serverless PostgreSQL database management',
    url: 'https://mcp.neon.tech/sse',
    authType: 'oauth',
    category: 'Developer Tools',
  },
  {
    slug: 'supabase',
    displayName: 'Supabase',
    description: 'Database access and platform integration',
    url: 'https://mcp.supabase.com/mcp',
    authType: 'oauth',
    category: 'Developer Tools',
  },
  {
    slug: 'buildkite',
    displayName: 'Buildkite',
    description: 'CI/CD pipelines',
    url: 'https://mcp.buildkite.com/mcp',
    authType: 'oauth',
    category: 'Developer Tools',
  },
  {
    slug: 'prisma',
    displayName: 'Prisma',
    description: 'Database management via Prisma ORM',
    url: 'https://mcp.prisma.io/mcp',
    authType: 'oauth',
    category: 'Developer Tools',
  },
  {
    slug: 'figma',
    displayName: 'Figma',
    description: 'Design context extraction, code generation from frames',
    url: 'https://mcp.figma.com/mcp',
    authType: 'oauth',
    category: 'Developer Tools',
  },
  {
    slug: 'datadog',
    displayName: 'Datadog',
    description: 'Logs, traces, incidents, monitors, dashboards, metrics',
    url: 'https://mcp.datadoghq.com/api/unstable/mcp-server/mcp',
    authType: 'bearer',
    category: 'Developer Tools',
  },
  {
    slug: 'semgrep',
    displayName: 'Semgrep',
    description: 'Code vulnerability and security scanning',
    url: 'https://mcp.semgrep.ai/mcp',
    authType: 'oauth',
    category: 'Developer Tools',
  },
  {
    slug: 'jam',
    displayName: 'Jam',
    description: 'Bug reporting for dev teams',
    url: 'https://mcp.jam.dev/mcp',
    authType: 'oauth',
    category: 'Developer Tools',
  },
  {
    slug: 'grafbase',
    displayName: 'Grafbase',
    description: 'GraphQL API platform',
    url: 'https://api.grafbase.com/mcp',
    authType: 'oauth',
    category: 'Developer Tools',
  },
  {
    slug: 'cortex',
    displayName: 'Cortex',
    description: 'Internal developer portal',
    url: 'https://mcp.cortex.io/mcp',
    authType: 'bearer',
    category: 'Developer Tools',
  },
  {
    slug: 'stytch',
    displayName: 'Stytch',
    description: 'Authentication platform',
    url: 'http://mcp.stytch.dev/mcp',
    authType: 'oauth',
    category: 'Developer Tools',
  },

  // Payments, Finance & Commerce
  {
    slug: 'stripe',
    displayName: 'Stripe',
    description: 'Payments, customers, subscriptions, invoices, fraud detection',
    url: 'https://mcp.stripe.com/',
    authType: 'oauth',
    category: 'Payments & Finance',
  },
  {
    slug: 'paypal',
    displayName: 'PayPal',
    description: 'Commerce, payments, inventory, shipping, refunds',
    url: 'https://mcp.paypal.com/mcp',
    authType: 'oauth',
    category: 'Payments & Finance',
  },
  {
    slug: 'square',
    displayName: 'Square',
    description: 'Payments, orders, inventory, customer management',
    url: 'https://mcp.squareup.com/sse',
    authType: 'oauth',
    category: 'Payments & Finance',
  },
  {
    slug: 'plaid',
    displayName: 'Plaid',
    description: 'Financial data — Link analytics, usage metrics',
    url: 'https://api.dashboard.plaid.com/mcp/sse',
    authType: 'oauth',
    category: 'Payments & Finance',
  },
  {
    slug: 'ramp',
    displayName: 'Ramp',
    description: 'Corporate card and expense management',
    url: 'https://ramp-mcp-remote.ramp.com/mcp',
    authType: 'oauth',
    category: 'Payments & Finance',
  },
  {
    slug: 'morningstar',
    displayName: 'Morningstar',
    description: 'Financial data analysis and research',
    url: 'https://mcp.morningstar.com/mcp',
    authType: 'oauth',
    category: 'Payments & Finance',
  },
  {
    slug: 'dodo-payments',
    displayName: 'Dodo Payments',
    description: 'Payment processing',
    url: 'https://mcp.dodopayments.com/sse',
    authType: 'bearer',
    category: 'Payments & Finance',
  },
  {
    slug: 'mercadolibre',
    displayName: 'Mercado Libre',
    description: 'E-commerce marketplace (Latin America)',
    url: 'https://mcp.mercadolibre.com/mcp',
    authType: 'bearer',
    category: 'Payments & Finance',
  },
  {
    slug: 'mercadopago',
    displayName: 'Mercado Pago',
    description: 'Payment processing (Latin America)',
    url: 'https://mcp.mercadopago.com/mcp',
    authType: 'bearer',
    category: 'Payments & Finance',
  },

  // Analytics, Marketing & SEO
  {
    slug: 'amplitude',
    displayName: 'Amplitude',
    description: 'Charts, dashboards, experiments, feature flags, cohorts',
    url: 'https://mcp.amplitude.com/mcp',
    authType: 'oauth',
    category: 'Analytics & Marketing',
  },
  {
    slug: 'thoughtspot',
    displayName: 'ThoughtSpot',
    description: 'Data analytics and business intelligence',
    url: 'https://agent.thoughtspot.app/mcp',
    authType: 'oauth',
    category: 'Analytics & Marketing',
  },
  {
    slug: 'meta-ads',
    displayName: 'Meta Ads (Pipeboard)',
    description: 'Facebook/Instagram ad campaign management',
    url: 'https://mcp.pipeboard.co/meta-ads-mcp',
    authType: 'oauth',
    category: 'Analytics & Marketing',
  },

  // Document Management & Content
  {
    slug: 'dropbox',
    displayName: 'Dropbox',
    description: 'File operations — list, search, download, upload',
    url: 'https://mcp.dropbox.com/mcp',
    authType: 'oauth',
    category: 'Documents & Content',
  },
  {
    slug: 'egnyte',
    displayName: 'Egnyte',
    description: 'Enterprise content management — document Q&A, summarization',
    url: 'https://mcp-server.egnyte.com/sse',
    authType: 'oauth',
    category: 'Documents & Content',
  },
  {
    slug: 'canva',
    displayName: 'Canva',
    description: 'Design — search, create, autofill templates, export',
    url: 'https://mcp.canva.com/mcp',
    authType: 'oauth',
    category: 'Documents & Content',
  },
  {
    slug: 'cloudinary',
    displayName: 'Cloudinary',
    description: 'Digital asset management',
    url: 'https://asset-management.mcp.cloudinary.com/sse',
    authType: 'oauth',
    category: 'Documents & Content',
  },

  // Search, Web Data & AI Tools
  {
    slug: 'exa',
    displayName: 'Exa Search',
    description: 'AI-powered web search',
    url: 'https://mcp.exa.ai/mcp',
    authType: 'none',
    category: 'Search & AI',
  },
  {
    slug: 'jina',
    displayName: 'Jina AI',
    description: 'Web search, URL-to-markdown, embeddings, PDF extraction',
    url: 'https://mcp.jina.ai/v1',
    authType: 'none',
    category: 'Search & AI',
  },
  {
    slug: 'apify',
    displayName: 'Apify',
    description: '4,000+ web scraping and automation actors',
    url: 'https://mcp.apify.com',
    authType: 'bearer',
    category: 'Search & AI',
  },
  {
    slug: 'deepwiki',
    displayName: 'DeepWiki',
    description: 'AI-powered GitHub repo documentation search',
    url: 'https://mcp.deepwiki.com/mcp',
    authType: 'none',
    category: 'Search & AI',
  },
  {
    slug: 'huggingface',
    displayName: 'Hugging Face',
    description: 'ML models, datasets, Gradio apps from HF Hub',
    url: 'https://hf.co/mcp',
    authType: 'none',
    category: 'Search & AI',
  },
  {
    slug: 'context7',
    displayName: 'Context7',
    description: 'Up-to-date library/framework docs (9,000+ libraries)',
    url: 'https://mcp.context7.com/mcp',
    authType: 'none',
    category: 'Search & AI',
  },
  {
    slug: 'microsoft-learn',
    displayName: 'Microsoft Learn',
    description: 'Microsoft documentation search',
    url: 'https://learn.microsoft.com/api/mcp',
    authType: 'none',
    category: 'Search & AI',
  },
  {
    slug: 'tally',
    displayName: 'Tally',
    description: 'Form building via natural language',
    url: 'https://api.tally.so/mcp',
    authType: 'bearer',
    category: 'Search & AI',
  },

  // Aggregator Platforms
  {
    slug: 'zapier',
    displayName: 'Zapier',
    description: 'Workflow automation across 7,000+ apps',
    url: 'https://mcp.zapier.com/api/mcp/mcp',
    authType: 'bearer',
    category: 'Aggregators',
  },
  {
    slug: 'waystation',
    displayName: 'WayStation',
    description: 'Universal connector for Notion, Slack, Monday, Airtable',
    url: 'https://waystation.ai/mcp',
    authType: 'oauth',
    category: 'Aggregators',
  },

  // Other
  {
    slug: 'indeed',
    displayName: 'Indeed',
    description: 'Job board — search and access job listings',
    url: 'https://mcp.indeed.com/claude/mcp',
    authType: 'oauth',
    category: 'Other',
  },
  {
    slug: 'backdocket',
    displayName: 'Backdocket',
    description: 'Legal data — claims, matters, contacts, tasks',
    url: 'https://ai.backdocket.com/mcp',
    authType: 'oauth',
    category: 'Other',
  },
  {
    slug: 'peek',
    displayName: 'Peek.com',
    description: 'Activities and tours booking',
    url: 'https://mcp.peek.com',
    authType: 'none',
    category: 'Other',
  },
  {
    slug: 'ean-search',
    displayName: 'EAN-Search',
    description: 'Product barcode and data lookup',
    url: 'https://www.ean-search.org/mcp',
    authType: 'oauth',
    category: 'Other',
  },
  {
    slug: 'globalping',
    displayName: 'Globalping',
    description: 'Network diagnostics from 500+ locations',
    url: 'https://mcp.globalping.dev/sse',
    authType: 'oauth',
    category: 'Other',
  },
  {
    slug: 'short-io',
    displayName: 'Short.io',
    description: 'Link shortening service',
    url: 'https://ai-assistant.short.io/mcp',
    authType: 'bearer',
    category: 'Other',
  },

  // ---- Added 2026-06-23: verified new MCP servers (workflow batch) ----
  {
    slug: 'apideck',
    displayName: 'Apideck',
    description: 'Unified API — one integration for CRM, accounting, HR, and file storage',
    url: 'https://mcp.apideck.dev/mcp',
    authType: 'bearer',
    category: 'Aggregators',
  },
  {
    slug: 'grafana',
    displayName: 'Grafana',
    description: 'Observability platform — dashboards, metrics, logs, alerts across Grafana Cloud',
    url: 'https://mcp.grafana.com/mcp',
    authType: 'oauth',
    category: 'Analytics & Marketing',
  },
  {
    slug: 'new-relic',
    displayName: 'New Relic',
    description: 'Observability and APM — query telemetry, errors, alerts, and dashboards',
    url: 'https://mcp.newrelic.com/mcp/',
    authType: 'oauth',
    category: 'Analytics & Marketing',
  },
  {
    slug: 'posthog',
    displayName: 'PostHog',
    description: 'Product analytics — events, funnels, insights, feature flags, session replay',
    url: 'https://mcp.posthog.com/mcp',
    authType: 'oauth',
    category: 'Analytics & Marketing',
  },
  {
    slug: 'mixpanel',
    displayName: 'Mixpanel',
    description: 'Product analytics — events, funnels, retention, cohorts, reports',
    url: 'https://mcp.mixpanel.com/mcp',
    authType: 'oauth',
    category: 'Analytics & Marketing',
  },
  {
    slug: 'hex',
    displayName: 'Hex',
    description: 'Collaborative data notebooks — SQL, Python, and analytics apps',
    url: 'https://app.hex.tech/mcp',
    authType: 'oauth',
    category: 'Analytics & Marketing',
  },
  {
    slug: 'statsig',
    displayName: 'Statsig',
    description: 'Experimentation and feature flags — A/B tests, gates, dynamic configs, metrics',
    url: 'https://api.statsig.com/v1/mcp',
    authType: 'oauth',
    category: 'Analytics & Marketing',
  },
  {
    slug: 'rudderstack',
    displayName: 'RudderStack',
    description: 'Customer data platform — event pipelines, sources, destinations, identity resolution',
    url: 'https://mcp.rudderstack.com/mcp',
    authType: 'oauth',
    category: 'Analytics & Marketing',
  },
  {
    slug: 'bigquery',
    displayName: 'BigQuery',
    description: 'Cloud data warehouse — run SQL queries, explore datasets, tables, and schemas',
    url: 'https://bigquery.googleapis.com/mcp',
    authType: 'none',
    category: 'Analytics & Marketing',
  },
  {
    slug: 'thoughtspot-spotter',
    displayName: 'ThoughtSpot Spotter',
    description: 'AI analytics agent — natural-language BI queries, liveboards, and data insights',
    url: 'https://agent.thoughtspot.app/mcp?api-version=latest',
    authType: 'oauth',
    category: 'Analytics & Marketing',
  },
  {
    slug: 'omni-analytics',
    displayName: 'Omni',
    description: 'Business intelligence — dashboards, models, and SQL-driven data exploration',
    url: 'https://callbacks.omniapp.co/callback/mcp',
    authType: 'oauth',
    category: 'Analytics & Marketing',
  },
  {
    slug: 'pendo',
    displayName: 'Pendo',
    description: 'Product analytics — usage data, feature adoption, guides, and user feedback',
    url: 'https://app.pendo.io/mcp/v0/shttp',
    authType: 'oauth',
    category: 'Analytics & Marketing',
  },
  {
    slug: 'klaviyo',
    displayName: 'Klaviyo',
    description: 'Email & SMS marketing — campaigns, flows, segments, profiles, and events',
    url: 'https://mcp.klaviyo.com/mcp',
    authType: 'oauth',
    category: 'Analytics & Marketing',
  },
  {
    slug: 'customer-io',
    displayName: 'Customer.io',
    description: 'Customer engagement — messaging campaigns, journeys, segments, and broadcasts',
    url: 'https://mcp.customer.io/mcp',
    authType: 'oauth',
    category: 'Analytics & Marketing',
  },
  {
    slug: 'brevo',
    displayName: 'Brevo',
    description: 'Email marketing & CRM — campaigns, contacts, transactional email, automation',
    url: 'https://mcp.brevo.com/v1/brevo/mcp',
    authType: 'oauth',
    category: 'Analytics & Marketing',
  },
  {
    slug: 'mailerlite',
    displayName: 'MailerLite',
    description: 'Email marketing — campaigns, subscribers, automations, landing pages',
    url: 'https://mcp.mailerlite.com/mcp',
    authType: 'oauth',
    category: 'Analytics & Marketing',
  },
  {
    slug: 'marketo',
    displayName: 'Adobe Marketo Engage',
    description: 'B2B marketing automation — leads, campaigns, nurture programs, scoring',
    url: 'https://marketo-mcp.adobe.io/mcp',
    authType: 'bearer',
    category: 'Analytics & Marketing',
  },
  {
    slug: 'ahrefs',
    displayName: 'Ahrefs',
    description: 'SEO toolkit — backlinks, keywords, rank tracking, site audits',
    url: 'https://api.ahrefs.com/mcp/mcp',
    authType: 'bearer',
    category: 'Analytics & Marketing',
  },
  {
    slug: 'semrush',
    displayName: 'Semrush',
    description: 'SEO & competitive intelligence — keywords, domain analytics, rank tracking',
    url: 'https://mcp.semrush.com/v1/mcp',
    authType: 'oauth',
    category: 'Analytics & Marketing',
  },
  {
    slug: 'se-ranking',
    displayName: 'SE Ranking',
    description: 'SEO platform — keyword research, rank tracking, competitor & backlink analysis',
    url: 'https://api.seranking.com/mcp',
    authType: 'oauth',
    category: 'Analytics & Marketing',
  },
  {
    slug: 'dataforseo',
    displayName: 'DataForSEO',
    description: 'SEO data API — SERPs, keywords, backlinks, on-page and competitor data',
    url: 'https://mcp.dataforseo.com/mcp',
    authType: 'bearer',
    category: 'Analytics & Marketing',
  },
  {
    slug: 'optimizely',
    displayName: 'Optimizely Experimentation',
    description: 'A/B testing & feature flags — experiments, rollouts, results',
    url: 'https://exp.mcp.opal.optimizely.com/mcp',
    authType: 'oauth',
    category: 'Analytics & Marketing',
  },
  {
    slug: 'apollo',
    displayName: 'Apollo.io',
    description: 'Sales intelligence — prospecting, contact enrichment, and sales engagement',
    url: 'https://mcp.apollo.io/mcp',
    authType: 'oauth',
    category: 'CRM & Sales',
  },
  {
    slug: 'zoominfo',
    displayName: 'ZoomInfo',
    description: 'B2B sales intelligence — company and contact data enrichment',
    url: 'https://mcp.zoominfo.com/mcp',
    authType: 'oauth',
    category: 'CRM & Sales',
  },
  {
    slug: 'lusha',
    displayName: 'Lusha',
    description: 'B2B contact data — emails, phone numbers, and lead enrichment',
    url: 'https://mcp.lusha.com',
    authType: 'oauth',
    category: 'CRM & Sales',
  },
  {
    slug: 'fellow',
    displayName: 'Fellow',
    description: 'AI meeting assistant — agendas, notes, transcripts, action items',
    url: 'https://fellow.app/mcp',
    authType: 'oauth',
    category: 'Communication',
  },
  {
    slug: 'supernormal',
    displayName: 'Supernormal',
    description: 'AI meeting notetaker — transcripts, summaries, and action items across calls',
    url: 'https://api.supernormal.com/mcp',
    authType: 'oauth',
    category: 'Communication',
  },
  {
    slug: 'vapi',
    displayName: 'Vapi',
    description: 'Voice AI platform — build, deploy, and manage phone call agents and assistants',
    url: 'https://mcp.vapi.ai/mcp',
    authType: 'bearer',
    category: 'Communication',
  },
  {
    slug: 'cal-com',
    displayName: 'Cal.com',
    description: 'Scheduling automation — bookings, event types, availability, and calendar links',
    url: 'https://mcp.cal.com/mcp',
    authType: 'oauth',
    category: 'Communication',
  },
  {
    slug: 'webex',
    displayName: 'Cisco Webex',
    description: 'Video meetings, team messaging, and Vidcast recordings',
    url: 'https://mcp.webexapis.com/mcp/webex-meeting',
    authType: 'oauth',
    category: 'Communication',
  },
  {
    slug: 'fireflies-ai',
    displayName: 'Fireflies.ai',
    description: 'AI meeting notetaker — transcripts, summaries, and conversation search',
    url: 'https://api.fireflies.ai/mcp',
    authType: 'oauth',
    category: 'Communication',
  },
  {
    slug: 'otter-ai',
    displayName: 'Otter.ai',
    description: 'AI meeting transcription — live notes, summaries, and speaker-labeled transcripts',
    url: 'https://mcp.otter.ai/mcp',
    authType: 'oauth',
    category: 'Communication',
  },
  {
    slug: 'grain',
    displayName: 'Grain',
    description: 'Meeting intelligence — recordings, transcripts, highlights, and notes',
    url: 'https://api.grain.com/_/mcp',
    authType: 'oauth',
    category: 'Communication',
  },
  {
    slug: 'avoma',
    displayName: 'Avoma',
    description: 'Meeting intelligence — transcripts, summaries, and conversation insights',
    url: 'https://mcp.avoma.com/mcp',
    authType: 'oauth',
    category: 'Communication',
  },
  {
    slug: 'circleback',
    displayName: 'Circleback',
    description: 'AI meeting notes — summaries, action items, and automated follow-ups',
    url: 'https://circleback.ai/api/mcp',
    authType: 'oauth',
    category: 'Communication',
  },
  {
    slug: 'mailersend',
    displayName: 'MailerSend',
    description: 'Transactional email API — send, templates, domains, delivery analytics',
    url: 'https://mcp.mailersend.com/mcp',
    authType: 'oauth',
    category: 'Communication',
  },
  {
    slug: 'beehiiv',
    displayName: 'beehiiv',
    description: 'Newsletter platform — posts, subscribers, segments, automations, analytics',
    url: 'https://mcp.beehiiv.com/mcp',
    authType: 'oauth',
    category: 'Communication',
  },
  {
    slug: 'gorgias',
    displayName: 'Gorgias',
    description: 'E-commerce helpdesk — tickets, customer support and conversations',
    url: 'https://mcp.gorgias.com/mcp',
    authType: 'oauth',
    category: 'Communication',
  },
  {
    slug: 'plain',
    displayName: 'Plain',
    description: 'Customer support — tickets, threads, conversations, customer timelines',
    url: 'https://mcp.plain.com/mcp',
    authType: 'oauth',
    category: 'Communication',
  },
  {
    slug: 'netlify',
    displayName: 'Netlify',
    description: 'Web hosting & deploy platform — sites, deploys, builds, env vars, functions',
    url: 'https://netlify-mcp.netlify.app/mcp',
    authType: 'oauth',
    category: 'Developer Tools',
  },
  {
    slug: 'railway',
    displayName: 'Railway',
    description: 'App hosting & deploy platform — projects, services, deployments, env vars',
    url: 'https://mcp.railway.com',
    authType: 'oauth',
    category: 'Developer Tools',
  },
  {
    slug: 'render',
    displayName: 'Render',
    description: 'Cloud hosting platform — services, deploys, databases, logs, metrics',
    url: 'https://mcp.render.com/mcp',
    authType: 'bearer',
    category: 'Developer Tools',
  },
  {
    slug: 'heroku',
    displayName: 'Heroku',
    description: 'PaaS hosting — apps, dynos, add-ons, config vars, releases, logs',
    url: 'https://mcp.heroku.com/mcp',
    authType: 'oauth',
    category: 'Developer Tools',
  },
  {
    slug: 'digitalocean',
    displayName: 'DigitalOcean',
    description: 'Cloud infrastructure — App Platform apps, deployments, logs, components',
    url: 'https://apps.mcp.digitalocean.com/mcp',
    authType: 'bearer',
    category: 'Developer Tools',
  },
  {
    slug: 'postman',
    displayName: 'Postman',
    description: 'API platform — collections, requests, environments, workspaces, specs',
    url: 'https://mcp.postman.com/mcp',
    authType: 'oauth',
    category: 'Developer Tools',
  },
  {
    slug: 'pulumi',
    displayName: 'Pulumi',
    description: 'Infrastructure as code — stacks, deployments, resources, cloud provisioning',
    url: 'https://mcp.ai.pulumi.com/mcp',
    authType: 'oauth',
    category: 'Developer Tools',
  },
  {
    slug: 'aws',
    displayName: 'AWS',
    description: 'Amazon Web Services — query and operate cloud resources across services',
    url: 'https://aws-mcp.us-east-1.api.aws/mcp',
    authType: 'none',
    category: 'Developer Tools',
  },
  {
    slug: 'honeycomb',
    displayName: 'Honeycomb',
    description: 'Observability for distributed systems — query traces, events, and SLOs',
    url: 'https://mcp.honeycomb.io/mcp',
    authType: 'oauth',
    category: 'Developer Tools',
  },
  {
    slug: 'launchdarkly',
    displayName: 'LaunchDarkly',
    description: 'Feature flags and experimentation — manage flags, targeting, and rollouts',
    url: 'https://mcp.launchdarkly.com/mcp/launchdarkly',
    authType: 'oauth',
    category: 'Developer Tools',
  },
  {
    slug: 'planetscale',
    displayName: 'PlanetScale',
    description: 'Serverless MySQL platform — databases, branches, schema, and queries',
    url: 'https://mcp.pscale.dev/mcp/planetscale',
    authType: 'oauth',
    category: 'Developer Tools',
  },
  {
    slug: 'clickhouse',
    displayName: 'ClickHouse',
    description: 'Columnar analytics database — run SQL queries across ClickHouse Cloud',
    url: 'https://mcp.clickhouse.cloud/mcp',
    authType: 'oauth',
    category: 'Developer Tools',
  },
  {
    slug: 'motherduck',
    displayName: 'MotherDuck',
    description: 'DuckDB-powered cloud data warehouse — run SQL queries and analytics',
    url: 'https://api.motherduck.com/mcp',
    authType: 'bearer',
    category: 'Developer Tools',
  },
  {
    slug: 'tinybird',
    displayName: 'Tinybird',
    description: 'Real-time analytics platform — build data APIs and query streaming data with SQL',
    url: 'https://mcp.tinybird.co',
    authType: 'bearer',
    category: 'Developer Tools',
  },
  {
    slug: 'dbt',
    displayName: 'dbt',
    description: 'Analytics engineering — transform, test, and document data models with SQL',
    url: 'https://cloud.getdbt.com/api/ai/v1/mcp/',
    authType: 'bearer',
    category: 'Developer Tools',
  },
  {
    slug: 'airbyte',
    displayName: 'Airbyte',
    description: 'Data integration — ELT connectors, sources, destinations, sync pipelines',
    url: 'https://mcp.airbyte.ai/mcp',
    authType: 'oauth',
    category: 'Developer Tools',
  },
  {
    slug: 'vanta',
    displayName: 'Vanta',
    description: 'Compliance automation — SOC 2, ISO 27001, controls, evidence, risk monitoring',
    url: 'https://mcp.vanta.com/mcp',
    authType: 'oauth',
    category: 'Developer Tools',
  },
  {
    slug: 'mapbox',
    displayName: 'Mapbox',
    description: 'Maps & geospatial — geocoding, directions, navigation, places',
    url: 'https://mcp.mapbox.com/mcp',
    authType: 'oauth',
    category: 'Developer Tools',
  },
  {
    slug: 'pagerduty',
    displayName: 'PagerDuty',
    description: 'Incident response & on-call — alerts, schedules, escalations',
    url: 'https://mcp.pagerduty.com/mcp',
    authType: 'oauth',
    category: 'Developer Tools',
  },
  {
    slug: 'incident-io',
    displayName: 'incident.io',
    description: 'Incident management — on-call, alerts, response, and post-incident reviews',
    url: 'https://mcp.incident.io/mcp',
    authType: 'oauth',
    category: 'Developer Tools',
  },
  {
    slug: 'socket',
    displayName: 'Socket',
    description: 'Software supply chain security — scan dependencies for risks and malware',
    url: 'https://mcp.socket.dev/',
    authType: 'none',
    category: 'Developer Tools',
  },
  {
    slug: 'harness',
    displayName: 'Harness',
    description: 'AI-native software delivery — CI/CD pipelines, deployments, feature flags, chaos',
    url: 'https://mcp.harness.io/mcp',
    authType: 'bearer',
    category: 'Developer Tools',
  },
  {
    slug: 'port',
    displayName: 'Port',
    description: 'Internal developer portal — service catalog, scorecards, self-service actions',
    url: 'https://mcp.port.io/v1',
    authType: 'oauth',
    category: 'Developer Tools',
  },
  {
    slug: 'replit',
    displayName: 'Replit',
    description: 'Cloud IDE and AI app builder — create, run, and deploy projects',
    url: 'https://replit-mcp.com/server/mcp',
    authType: 'oauth',
    category: 'Developer Tools',
  },
  {
    slug: 'lovable',
    displayName: 'Lovable',
    description: 'AI app builder — generate, edit, and ship full-stack web apps from prompts',
    url: 'https://mcp.lovable.dev',
    authType: 'oauth',
    category: 'Developer Tools',
  },
  {
    slug: 'guru',
    displayName: 'Guru',
    description: 'Enterprise knowledge base — AI search, verified answers, wiki, intranet',
    url: 'https://mcp.api.getguru.com/mcp',
    authType: 'oauth',
    category: 'Documents & Content',
  },
  {
    slug: 'nuclino',
    displayName: 'Nuclino',
    description: 'Team wiki and knowledge base — docs, notes, and projects in one workspace',
    url: 'https://api.nuclino.com/mcp',
    authType: 'oauth',
    category: 'Documents & Content',
  },
  {
    slug: 'contentful',
    displayName: 'Contentful',
    description: 'Headless CMS — entries, content types, assets, spaces, environments',
    url: 'https://mcp.contentful.com/mcp',
    authType: 'oauth',
    category: 'Documents & Content',
  },
  {
    slug: 'sanity',
    displayName: 'Sanity',
    description: 'Headless CMS — documents, datasets, GROQ queries, schemas, releases',
    url: 'https://mcp.sanity.io',
    authType: 'oauth',
    category: 'Documents & Content',
  },
  {
    slug: 'storyblok',
    displayName: 'Storyblok',
    description: 'Headless CMS — stories, components, spaces, assets, content blocks',
    url: 'https://mcp.labs.storyblok.com/mcp',
    authType: 'bearer',
    category: 'Documents & Content',
  },
  {
    slug: 'datocms',
    displayName: 'DatoCMS',
    description: 'Headless CMS — records, models, fields, uploads, environments',
    url: 'https://mcp.datocms.com',
    authType: 'oauth',
    category: 'Documents & Content',
  },
  {
    slug: 'prismic',
    displayName: 'Prismic',
    description: 'Headless CMS — documents, custom types, slices, releases, media',
    url: 'https://mcp.prismic.io/mcp',
    authType: 'oauth',
    category: 'Documents & Content',
  },
  {
    slug: 'builder-io',
    displayName: 'Builder.io',
    description: 'Visual CMS — pages, content models, sections, publish to production',
    url: 'https://mcp.builder.io/mcp/publish',
    authType: 'oauth',
    category: 'Documents & Content',
  },
  {
    slug: 'wordpress',
    displayName: 'WordPress',
    description: 'CMS — posts, pages, media, comments, categories, tags',
    url: 'https://public-api.wordpress.com/wpcom/v2/mcp/v1',
    authType: 'oauth',
    category: 'Documents & Content',
  },
  {
    slug: 'sitecore',
    displayName: 'Sitecore',
    description: 'Digital experience platform — content, campaigns, personalization, marketing analytics',
    url: 'https://marketer.sitecorecloud.io/mcp/marketer-mcp-prod',
    authType: 'oauth',
    category: 'Documents & Content',
  },
  {
    slug: 'heygen',
    displayName: 'HeyGen',
    description: 'AI video generation with avatars, voices and translation',
    url: 'https://mcp.heygen.com/mcp/v1/',
    authType: 'oauth',
    category: 'Documents & Content',
  },
  {
    slug: 'runway',
    displayName: 'Runway',
    description: 'AI video and image generation from text and prompts',
    url: 'https://mcp.runwayml.com/mcp',
    authType: 'oauth',
    category: 'Documents & Content',
  },
  {
    slug: 'pandadoc',
    displayName: 'PandaDoc',
    description: 'eSignature & documents — proposals, contracts, quotes, signing workflows',
    url: 'https://mcp.pandadoc.com/v1/mcp',
    authType: 'oauth',
    category: 'Documents & Content',
  },
  {
    slug: 'readwise',
    displayName: 'Readwise',
    description: 'Reading highlights & knowledge sync — articles, books, notes',
    url: 'https://mcp2.readwise.io/mcp',
    authType: 'oauth',
    category: 'Documents & Content',
  },
  {
    slug: 'mintlify',
    displayName: 'Mintlify',
    description: 'Documentation platform — author, search, and publish developer docs',
    url: 'https://mcp.mintlify.com',
    authType: 'oauth',
    category: 'Documents & Content',
  },
  {
    slug: 'gamma',
    displayName: 'Gamma',
    description: 'AI presentations — generate decks, docs, and webpages from prompts',
    url: 'https://mcp.gamma.app/mcp',
    authType: 'oauth',
    category: 'Documents & Content',
  },
  {
    slug: 'descript',
    displayName: 'Descript',
    description: 'Audio and video editing — transcribe, edit by text, and produce media',
    url: 'https://api.descript.com/v2/mcp',
    authType: 'bearer',
    category: 'Documents & Content',
  },
  {
    slug: 'gusto',
    displayName: 'Gusto',
    description: 'Payroll, benefits, and HR — employees, contractors, pay runs, time tracking',
    url: 'https://mcp.api.gusto.com',
    authType: 'bearer',
    category: 'Other',
  },
  {
    slug: 'shipbob',
    displayName: 'ShipBob',
    description: 'Ecommerce fulfillment — orders, inventory and shipments',
    url: 'https://api.shipbob.com/developer-api/mcp',
    authType: 'oauth',
    category: 'Other',
  },
  {
    slug: 'shippo',
    displayName: 'Shippo',
    description: 'Multi-carrier shipping — rates, labels and tracking',
    url: 'https://mcp.shippo.com',
    authType: 'bearer',
    category: 'Other',
  },
  {
    slug: 'deel',
    displayName: 'Deel',
    description: 'Global payroll & EOR — contracts, hiring, payments, compliance across countries',
    url: 'https://api.letsdeel.com/mcp',
    authType: 'none',
    category: 'Other',
  },
  {
    slug: 'remote',
    displayName: 'Remote',
    description: 'Global employment & payroll — EOR hiring, contractors, benefits, payments',
    url: 'https://mcp.remote.com/mcp',
    authType: 'oauth',
    category: 'Other',
  },
  {
    slug: 'ironclad',
    displayName: 'Ironclad',
    description: 'Contract lifecycle management — drafting, approvals, signing, repository',
    url: 'https://mcp.na1.ironcladapp.com/mcp',
    authType: 'oauth',
    category: 'Other',
  },
  {
    slug: 'strava',
    displayName: 'Strava',
    description: 'Fitness & activity tracking — runs, rides, segments, stats',
    url: 'https://mcp.strava.com/mcp',
    authType: 'oauth',
    category: 'Other',
  },
  {
    slug: 'tourradar',
    displayName: 'TourRadar',
    description: 'Travel marketplace — search and book tours, trips, activities',
    url: 'https://ai.tourradar.com/mcp/main',
    authType: 'none',
    category: 'Other',
  },
  {
    slug: 'mercury',
    displayName: 'Mercury',
    description: 'Business banking — accounts, balances, transactions, and payments',
    url: 'https://mcp.mercury.com/mcp',
    authType: 'oauth',
    category: 'Payments & Finance',
  },
  {
    slug: 'brex',
    displayName: 'Brex',
    description: 'Corporate cards and spend management — expenses, budgets, and transactions',
    url: 'https://api.brex.com/mcp',
    authType: 'oauth',
    category: 'Payments & Finance',
  },
  {
    slug: 'robinhood',
    displayName: 'Robinhood',
    description: 'Brokerage — accounts, portfolio, quotes, watchlists, place equity trades',
    url: 'https://agent.robinhood.com/mcp/trading',
    authType: 'oauth',
    category: 'Payments & Finance',
  },
  {
    slug: 'polar',
    displayName: 'Polar',
    description: 'Merchant-of-record billing — products, subscriptions, checkout, customer payments',
    url: 'https://mcp.polar.sh/mcp/polar-mcp',
    authType: 'bearer',
    category: 'Payments & Finance',
  },
  {
    slug: 'carta',
    displayName: 'Carta',
    description: 'Cap table & equity management — ownership, fundraising, fund administration',
    url: 'https://mcp.app.carta.com/mcp',
    authType: 'oauth',
    category: 'Payments & Finance',
  },
  {
    slug: 'finix',
    displayName: 'Finix',
    description: 'Payments platform — process transactions, manage merchants and payouts',
    url: 'https://docs.finix.com/mcp',
    authType: 'none',
    category: 'Payments & Finance',
  },
  {
    slug: 'smartsheet',
    displayName: 'Smartsheet',
    description: 'Work management — sheets, projects, tasks, and reports',
    url: 'https://mcp.smartsheet.com',
    authType: 'oauth',
    category: 'Project Management',
  },
  {
    slug: 'coda',
    displayName: 'Coda',
    description: 'All-in-one docs — tables, pages, and collaborative workspaces',
    url: 'https://coda.io/apis/mcp',
    authType: 'oauth',
    category: 'Project Management',
  },
  {
    slug: 'todoist',
    displayName: 'Todoist',
    description: 'Task management — tasks, projects, labels, and due dates',
    url: 'https://ai.todoist.net/mcp',
    authType: 'oauth',
    category: 'Project Management',
  },
  {
    slug: 'shortcut',
    displayName: 'Shortcut',
    description: 'Software project management — stories, epics, iterations, and workflows',
    url: 'https://mcp.shortcut.com/mcp',
    authType: 'oauth',
    category: 'Project Management',
  },
  {
    slug: 'wrike',
    displayName: 'Wrike',
    description: 'Project management — tasks, folders, projects, and team workflows',
    url: 'https://mcp.wrike.com/app/mcp/stream',
    authType: 'bearer',
    category: 'Project Management',
  },
  {
    slug: 'teamwork',
    displayName: 'Teamwork.com',
    description: 'Client work management — projects, tasks, time tracking, milestones, workloads',
    url: 'https://mcp.ai.teamwork.com',
    authType: 'none',
    category: 'Project Management',
  },
  {
    slug: 'miro',
    displayName: 'Miro',
    description: 'Visual collaboration whiteboard — boards, sticky notes, diagrams, frames',
    url: 'https://mcp.miro.com/',
    authType: 'oauth',
    category: 'Project Management',
  },
  {
    slug: 'sunsama',
    displayName: 'Sunsama',
    description: 'Daily planner — time-block tasks, calendar, and to-dos into a focused day',
    url: 'https://api.sunsama.com/mcp',
    authType: 'oauth',
    category: 'Project Management',
  },
  {
    slug: 'plane',
    displayName: 'Plane',
    description: 'Open-source project tracking — issues, cycles, modules, roadmaps',
    url: 'https://mcp.plane.so/http/mcp',
    authType: 'oauth',
    category: 'Project Management',
  },
  {
    slug: 'tavily',
    displayName: 'Tavily',
    description: 'AI search API — web search, content extract, and crawl for agents',
    url: 'https://mcp.tavily.com/mcp/',
    authType: 'oauth',
    category: 'Search & AI',
  },
  {
    slug: 'firecrawl',
    displayName: 'Firecrawl',
    description: 'Web scraping API — crawl, scrape, map, and search sites into clean markdown',
    url: 'https://mcp.firecrawl.dev/v2/mcp',
    authType: 'none',
    category: 'Search & AI',
  },
  {
    slug: 'browserbase',
    displayName: 'Browserbase',
    description: 'Cloud browser automation — headless sessions, navigation, and web agents',
    url: 'https://mcp.browserbase.com/mcp',
    authType: 'bearer',
    category: 'Search & AI',
  },
  {
    slug: 'zenrows',
    displayName: 'ZenRows',
    description: 'Web scraping API — anti-bot bypass, proxies, and structured extraction',
    url: 'https://mcp.zenrows.com/mcp',
    authType: 'bearer',
    category: 'Search & AI',
  },
  {
    slug: 'scrapegraphai',
    displayName: 'ScrapeGraphAI',
    description: 'AI web scraping — prompt-driven extraction, crawling, and search',
    url: 'https://mcp.scrapegraphai.com/mcp',
    authType: 'bearer',
    category: 'Search & AI',
  },
  {
    slug: 'olostep',
    displayName: 'Olostep',
    description: 'Web scraping and search infrastructure — fast page parsing and crawls at scale',
    url: 'https://mcp.olostep.com/mcp',
    authType: 'bearer',
    category: 'Search & AI',
  },
  {
    slug: 'decodo',
    displayName: 'Decodo',
    description: 'Proxy and web scraping platform — residential proxies and data collection',
    url: 'https://mcp.decodo.com/mcp',
    authType: 'bearer',
    category: 'Search & AI',
  },
  {
    slug: 'llamacloud',
    displayName: 'LlamaCloud',
    description: 'Document parsing, extraction and RAG indexing over your knowledge base',
    url: 'https://mcp.llamaindex.ai/mcp',
    authType: 'none',
    category: 'Search & AI',
  },
  {
    slug: 'reducto',
    displayName: 'Reducto',
    description: 'Parse and extract structured data from PDFs, tables and documents',
    url: 'https://mcp.reducto.ai/mcp',
    authType: 'bearer',
    category: 'Search & AI',
  },
  {
    slug: 'fal',
    displayName: 'Fal',
    description: 'Generative media inference — run image, video and audio models',
    url: 'https://mcp.fal.ai/mcp',
    authType: 'oauth',
    category: 'Search & AI',
  },
  {
    slug: 'mem0',
    displayName: 'Mem0',
    description: 'Persistent agent memory — store, search, recall context',
    url: 'https://mcp.mem0.ai/mcp',
    authType: 'oauth',
    category: 'Search & AI',
  },
  {
    slug: 'supermemory',
    displayName: 'Supermemory',
    description: 'Agent memory & knowledge graph — store, retrieve, connect facts',
    url: 'https://mcp.supermemory.ai/mcp',
    authType: 'oauth',
    category: 'Search & AI',
  },
  {
    slug: 'wolfram',
    displayName: 'Wolfram',
    description: 'Computational knowledge engine — math, data, science, and curated facts',
    url: 'https://services.wolfram.com/api/mcp',
    authType: 'bearer',
    category: 'Search & AI',
  },
]

export function getCommonMcpServer(slug: string): CommonMcpServer | undefined {
  return COMMON_MCP_SERVERS.find((s) => s.slug === slug)
}

export function getAllCommonMcpServers(): CommonMcpServer[] {
  return COMMON_MCP_SERVERS
}

export function searchCommonMcpServers(query: string): CommonMcpServer[] {
  const term = query.toLowerCase()
  return COMMON_MCP_SERVERS.filter(
    (s) =>
      s.slug.includes(term) ||
      s.displayName.toLowerCase().includes(term) ||
      s.category.toLowerCase().includes(term) ||
      s.description.toLowerCase().includes(term)
  )
}
