/**
 * Write `src/shared/lib/db/migrations/bundle.ts` from the SQL files and
 * `meta/_journal.json` beside it, in the exact shape drizzle's folder
 * migrator would read at runtime. The app migrates from this bundle, so a
 * packaged build carries no migration files. `npm run db:generate` runs
 * this after drizzle-kit; `bundle.test.ts` fails when the two drift.
 *
 *   npm run db:bundle
 */
import fs from 'node:fs'
import path from 'node:path'
import { readMigrationFiles } from 'drizzle-orm/migrator'

// Run from the repo root (`npm run db:bundle`), like drizzle.config.ts.
const migrationsFolder = path.resolve(process.cwd(), 'src/shared/lib/db/migrations')
const bundlePath = path.join(migrationsFolder, 'bundle.ts')

const migrations = readMigrationFiles({ migrationsFolder })

const header = `/* eslint-disable */
// Generated by \`npm run db:bundle\` from the SQL files and meta/_journal.json in
// this folder, in the shape drizzle's folder migrator reads. Do not edit: run
// \`npm run db:generate\` (or \`npm run db:bundle\`) after changing a migration.
import type { MigrationMeta } from 'drizzle-orm/migrator'

export const migrationBundle: readonly MigrationMeta[] = `

fs.writeFileSync(bundlePath, `${header}${JSON.stringify(migrations, null, 2)}\n`)
console.log(`Bundled ${migrations.length} migrations into ${path.relative(process.cwd(), bundlePath)}`)
