#!/usr/bin/env npx tsx
/**
 * Resolve WHITELIST_SOURCE into a committed whitelist-data.ts snapshot. The only thing
 * asked of the vendor is each model's `official` flag, which decides the create path an
 * agent must use. Manual run; output is committed.
 *
 * Run: REPLICATE_API_TOKEN=… npx tsx scripts/fetch-replicate-whitelist.ts
 */
import { writeFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'
import { WHITELIST_SOURCE } from '../src/shared/lib/replicate/whitelist-source'
import {
  generatedFileSchema,
  type GeneratedEntry,
} from '../src/shared/lib/replicate/replicate-schema'

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUTPUT_PATH = resolve(__dirname, '../src/shared/lib/replicate/whitelist-data.ts')
const API_BASE = 'https://api.replicate.com'

interface ModelResponse {
  is_official?: boolean
}

async function main() {
  const token = process.env.REPLICATE_API_TOKEN
  if (!token) {
    throw new Error('REPLICATE_API_TOKEN is required')
  }

  const entries: GeneratedEntry[] = []
  for (const entry of WHITELIST_SOURCE) {
    // A 404 here means the seed names a model that does not exist — fail rather than
    // ship a catalog entry the agent cannot run.
    const res = await fetch(`${API_BASE}/v1/models/${entry.model}`, {
      headers: { Authorization: `Bearer ${token}`, Accept: 'application/json' },
    })
    if (!res.ok) {
      throw new Error(`GET /v1/models/${entry.model} failed: ${res.status} ${res.statusText}`)
    }
    const data = (await res.json()) as ModelResponse
    entries.push({ model: entry.model, category: entry.category, official: data.is_official === true })
  }

  entries.sort((a, b) => a.category.localeCompare(b.category) || a.model.localeCompare(b.model))
  const validated = generatedFileSchema.parse(entries)

  const quote = (value: string) => `'${value.replace(/'/g, "\\'")}'`
  const body = validated
    .map(
      (e) => `  { model: ${quote(e.model)}, category: ${quote(e.category)}, official: ${e.official} },`,
    )
    .join('\n')

  const file = `// GENERATED by scripts/fetch-replicate-whitelist.ts — do not hand-edit
import type { GeneratedEntry } from './replicate-schema'

export const WHITELIST_ENTRIES: GeneratedEntry[] = [
${body}
]
`

  writeFileSync(OUTPUT_PATH, file)
  console.log(`Wrote ${validated.length} models to ${OUTPUT_PATH}`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
