/**
 * Codemod: merge curated scope descriptions + workflow-produced risk labels into
 * a single generated module, src/shared/lib/proxy/scope-metadata.ts.
 *
 * Deterministic — no LLM. Run AFTER scripts/audit-scope-labels.ts passes.
 *
 * Reads:
 *   - descriptions from the current src/shared/lib/proxy/scope-metadata.ts
 *     (the source of truth — edit descriptions there, then re-run this)
 *   - scripts/.scope-labels.json  ({ [provider]: { [scope]: 'read'|'write'|'destructive' } })
 * Writes:
 *   - src/shared/lib/proxy/scope-metadata.ts  (overwrites in place; idempotent)
 *
 * Enforces description↔label parity: every described scope must have a label and
 * vice-versa, so the generated file is exhaustive (the big-bang invariant).
 *
 * Usage: tsx scripts/merge-scope-metadata.ts
 *   then: npx eslint --fix src/shared/lib/proxy/scope-metadata.ts
 */
import { readFileSync, writeFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'
import { z } from 'zod'
import { SCOPE_METADATA } from '../src/shared/lib/proxy/scope-metadata'

const __dirname = dirname(fileURLToPath(import.meta.url))

// Descriptions now live in scope-metadata.ts; project to the legacy
// { [provider]: { [scope]: description } } shape the merge logic below expects.
const SCOPE_DESCRIPTIONS: Record<string, Record<string, string>> = {}
for (const [provider, scopes] of Object.entries(SCOPE_METADATA)) {
  SCOPE_DESCRIPTIONS[provider] = {}
  for (const [scope, meta] of Object.entries(scopes)) {
    SCOPE_DESCRIPTIONS[provider][scope] = meta.description
  }
}

const labelsSchema = z.record(
  z.string(),
  z.record(z.string(), z.enum(['read', 'write', 'destructive'])),
)

const labels = labelsSchema.parse(
  JSON.parse(readFileSync(resolve(__dirname, '.scope-labels.json'), 'utf8')),
)

// ── Parity check: descriptions ↔ labels must cover exactly the same scopes ────
const problems: string[] = []
const allProviders = new Set([
  ...Object.keys(SCOPE_DESCRIPTIONS),
  ...Object.keys(labels),
])
for (const provider of allProviders) {
  const descs = SCOPE_DESCRIPTIONS[provider] ?? {}
  const provLabels = labels[provider] ?? {}
  for (const scope of Object.keys(descs)) {
    if (!provLabels[scope]) problems.push(`missing label: ${provider}.${scope}`)
  }
  for (const scope of Object.keys(provLabels)) {
    if (!descs[scope]) problems.push(`label without description: ${provider}.${scope}`)
  }
}
if (problems.length > 0) {
  console.error(`Parity check failed (${problems.length}):`)
  for (const p of problems.slice(0, 50)) console.error(`  ${p}`)
  if (problems.length > 50) console.error(`  …and ${problems.length - 50} more`)
  process.exit(1)
}

// ── Emit ──────────────────────────────────────────────────────────────────────
const header = `/**
 * Per-provider OAuth scope metadata: human description + risk label.
 *
 * GENERATED by scripts/merge-scope-metadata.ts — do not edit by hand.
 * Source: curated descriptions (formerly scope-descriptions.ts) + the
 * label-scopes workflow's classification. Descriptions are end-user-facing
 * consent text; labels (read | write | destructive) classify each scope by the
 * MOST DANGEROUS capability it grants and drive default API access policies.
 *
 * Used by scope-matcher (proxy review prompts), scope-policy-editor (settings
 * grouping), and the policy resolver (label-default tier).
 */

export type ScopeLabel = 'read' | 'write' | 'destructive'

export interface ScopeMeta {
  description: string
  label?: ScopeLabel
}

export const SCOPE_METADATA: Record<string, Record<string, ScopeMeta>> = {
`

let body = ''
const counts = { read: 0, write: 0, destructive: 0 }
for (const provider of Object.keys(SCOPE_DESCRIPTIONS).sort()) {
  const descs = SCOPE_DESCRIPTIONS[provider]
  body += `  ${JSON.stringify(provider)}: {\n`
  for (const scope of Object.keys(descs).sort()) {
    const description = descs[scope]
    const label = labels[provider][scope]
    counts[label]++
    body += `    ${JSON.stringify(scope)}: { description: ${JSON.stringify(
      description,
    )}, label: ${JSON.stringify(label)} },\n`
  }
  body += `  },\n`
}

const footer = `}

export function getScopeDescription(provider: string, scope: string): string | undefined {
  return SCOPE_METADATA[provider]?.[scope]?.description
}

export function getScopeLabel(provider: string, scope: string): ScopeLabel | undefined {
  return SCOPE_METADATA[provider]?.[scope]?.label
}
`

const out = resolve(__dirname, '../src/shared/lib/proxy/scope-metadata.ts')
writeFileSync(out, header + body + footer)

const total = counts.read + counts.write + counts.destructive
console.log(`Wrote ${out}`)
console.log(`  ${total} scopes: read=${counts.read} write=${counts.write} destructive=${counts.destructive}`)
console.log(`\nNext: npx eslint --fix ${out.replace(resolve(__dirname, '..') + '/', '')}`)
