/* eslint-disable */
// Generated by `npm run db:bundle` from the SQL files and meta/_journal.json in
// this folder, in the shape drizzle's folder migrator reads. Do not edit: run
// `npm run db:generate` (or `npm run db:bundle`) after changing a migration.
import type { MigrationMeta } from 'drizzle-orm/migrator'

export const migrationBundle: readonly MigrationMeta[] = [
  {
    "sql": [
      "CREATE TABLE `agent_connected_accounts` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`agent_slug` text NOT NULL,\n\t`connected_account_id` text NOT NULL,\n\t`created_at` integer NOT NULL,\n\tFOREIGN KEY (`connected_account_id`) REFERENCES `connected_accounts`(`id`) ON UPDATE no action ON DELETE cascade\n);\n",
      "\nCREATE TABLE `connected_accounts` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`composio_connection_id` text NOT NULL,\n\t`toolkit_slug` text NOT NULL,\n\t`display_name` text NOT NULL,\n\t`status` text DEFAULT 'active' NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL\n);\n",
      "\nCREATE UNIQUE INDEX `agent_connected_accounts_unique` ON `agent_connected_accounts` (`agent_slug`,`connected_account_id`);",
      "\nCREATE UNIQUE INDEX `connected_accounts_composio_connection_id_unique` ON `connected_accounts` (`composio_connection_id`);"
    ],
    "bps": true,
    "folderMillis": 1769216154038,
    "hash": "ec2bb285eaae6f33d8af1bcda5d346ad3efd7fd667825ab9cc9d5cef1c9a74e1"
  },
  {
    "sql": [
      "CREATE TABLE `scheduled_tasks` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`agent_slug` text NOT NULL,\n\t`schedule_type` text NOT NULL,\n\t`schedule_expression` text NOT NULL,\n\t`prompt` text NOT NULL,\n\t`name` text,\n\t`status` text DEFAULT 'pending' NOT NULL,\n\t`next_execution_at` integer NOT NULL,\n\t`last_executed_at` integer,\n\t`is_recurring` integer DEFAULT false NOT NULL,\n\t`execution_count` integer DEFAULT 0 NOT NULL,\n\t`last_session_id` text,\n\t`created_by_session_id` text,\n\t`created_at` integer NOT NULL,\n\t`cancelled_at` integer\n);\n"
    ],
    "bps": true,
    "folderMillis": 1769481336403,
    "hash": "c6f52c81fb585cfa041fe8aa0fa09a2352e4b2addb3f258030e746188877787f"
  },
  {
    "sql": [
      "CREATE TABLE `notifications` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`type` text NOT NULL,\n\t`session_id` text NOT NULL,\n\t`agent_slug` text NOT NULL,\n\t`title` text NOT NULL,\n\t`body` text NOT NULL,\n\t`is_read` integer DEFAULT false NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`read_at` integer\n);\n"
    ],
    "bps": true,
    "folderMillis": 1769547980288,
    "hash": "3ada1ea1b5e497f81dcb8563222d0159274e68cb48e17bb9ce6c4c99df48f7fb"
  },
  {
    "sql": [
      "CREATE TABLE `proxy_audit_log` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`agent_slug` text NOT NULL,\n\t`account_id` text NOT NULL,\n\t`toolkit` text NOT NULL,\n\t`target_host` text NOT NULL,\n\t`target_path` text NOT NULL,\n\t`method` text NOT NULL,\n\t`status_code` integer,\n\t`error_message` text,\n\t`created_at` integer NOT NULL\n);\n",
      "\nCREATE TABLE `proxy_tokens` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`agent_slug` text NOT NULL,\n\t`token` text NOT NULL,\n\t`created_at` integer NOT NULL\n);\n",
      "\nCREATE UNIQUE INDEX `proxy_tokens_agent_slug_unique` ON `proxy_tokens` (`agent_slug`);",
      "\nCREATE UNIQUE INDEX `proxy_tokens_token_unique` ON `proxy_tokens` (`token`);"
    ],
    "bps": true,
    "folderMillis": 1769658411861,
    "hash": "b34a3f4134c1753e81202d853c57f314552700825a5141f44b8473acee439939"
  },
  {
    "sql": [
      "CREATE TABLE `agent_remote_mcps` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`agent_slug` text NOT NULL,\n\t`remote_mcp_id` text NOT NULL,\n\t`created_at` integer NOT NULL,\n\tFOREIGN KEY (`remote_mcp_id`) REFERENCES `remote_mcp_servers`(`id`) ON UPDATE no action ON DELETE cascade\n);\n",
      "\nCREATE TABLE `mcp_audit_log` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`agent_slug` text NOT NULL,\n\t`remote_mcp_id` text NOT NULL,\n\t`remote_mcp_name` text NOT NULL,\n\t`method` text NOT NULL,\n\t`request_path` text NOT NULL,\n\t`status_code` integer,\n\t`error_message` text,\n\t`duration_ms` integer,\n\t`created_at` integer NOT NULL\n);\n",
      "\nCREATE TABLE `remote_mcp_servers` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`url` text NOT NULL,\n\t`auth_type` text DEFAULT 'none' NOT NULL,\n\t`access_token` text,\n\t`refresh_token` text,\n\t`token_expires_at` integer,\n\t`oauth_token_endpoint` text,\n\t`oauth_client_id` text,\n\t`oauth_client_secret` text,\n\t`oauth_resource` text,\n\t`tools_json` text,\n\t`tools_discovered_at` integer,\n\t`status` text DEFAULT 'active' NOT NULL,\n\t`error_message` text,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL\n);\n",
      "\nCREATE UNIQUE INDEX `agent_remote_mcps_unique` ON `agent_remote_mcps` (`agent_slug`,`remote_mcp_id`);",
      "\nCREATE UNIQUE INDEX `remote_mcp_servers_url_unique` ON `remote_mcp_servers` (`url`);"
    ],
    "bps": true,
    "folderMillis": 1771364939625,
    "hash": "def89ff01f7c1bff8f53cdd3527639dd5d34ce73b8f13be35650fa5daee5a974"
  },
  {
    "sql": [
      "DROP INDEX IF EXISTS `remote_mcp_servers_url_unique`;"
    ],
    "bps": true,
    "folderMillis": 1771383823463,
    "hash": "443826b2e4abd6c73a35c5eccfbaa7fafccf27f03062af0d3f77e7d5522d9c70"
  },
  {
    "sql": [
      "CREATE TABLE `agent_acl` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`agent_slug` text NOT NULL,\n\t`role` text NOT NULL,\n\t`created_at` integer NOT NULL\n);\n",
      "\nCREATE TABLE `account` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`account_id` text NOT NULL,\n\t`provider_id` text NOT NULL,\n\t`user_id` text NOT NULL,\n\t`access_token` text,\n\t`refresh_token` text,\n\t`id_token` text,\n\t`access_token_expires_at` integer,\n\t`refresh_token_expires_at` integer,\n\t`scope` text,\n\t`password` text,\n\t`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,\n\t`updated_at` integer NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade\n);\n",
      "\nCREATE TABLE `session` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`expires_at` integer NOT NULL,\n\t`token` text NOT NULL,\n\t`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,\n\t`updated_at` integer NOT NULL,\n\t`ip_address` text,\n\t`user_agent` text,\n\t`user_id` text NOT NULL,\n\t`impersonated_by` text,\n\tFOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade\n);\n",
      "\nCREATE TABLE `user` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`email` text NOT NULL,\n\t`email_verified` integer DEFAULT false NOT NULL,\n\t`image` text,\n\t`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,\n\t`updated_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,\n\t`role` text,\n\t`banned` integer DEFAULT false,\n\t`ban_reason` text,\n\t`ban_expires` integer\n);\n",
      "\nCREATE TABLE `user_settings` (\n\t`user_id` text PRIMARY KEY NOT NULL,\n\t`settings` text NOT NULL,\n\t`updated_at` integer NOT NULL\n);\n",
      "\nCREATE TABLE `verification` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`identifier` text NOT NULL,\n\t`value` text NOT NULL,\n\t`expires_at` integer NOT NULL,\n\t`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,\n\t`updated_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL\n);\n",
      "\nALTER TABLE `connected_accounts` ADD `user_id` text;",
      "\nALTER TABLE `notifications` ADD `user_id` text;",
      "\nALTER TABLE `remote_mcp_servers` ADD `user_id` text;",
      "\nALTER TABLE `scheduled_tasks` ADD `created_by_user_id` text;",
      "\nCREATE UNIQUE INDEX `agent_acl_user_agent_unique` ON `agent_acl` (`user_id`,`agent_slug`);",
      "\nCREATE INDEX `agent_acl_agent_slug_idx` ON `agent_acl` (`agent_slug`);",
      "\nCREATE INDEX `account_userId_idx` ON `account` (`user_id`);",
      "\nCREATE UNIQUE INDEX `session_token_unique` ON `session` (`token`);",
      "\nCREATE INDEX `session_userId_idx` ON `session` (`user_id`);",
      "\nCREATE UNIQUE INDEX `user_email_unique` ON `user` (`email`);",
      "\nCREATE INDEX `verification_identifier_idx` ON `verification` (`identifier`);"
    ],
    "bps": true,
    "folderMillis": 1772153570664,
    "hash": "e04d532a033a799eb0393d01927dab56965576810ab4ee1a466ec7f09e5d062c"
  },
  {
    "sql": [
      "-- Convert existing timestamp columns from seconds to milliseconds\n-- The WHERE clause prevents double-conversion (values already in ms are > 10 billion)\nUPDATE \"connected_accounts\" SET \"created_at\" = \"created_at\" * 1000 WHERE \"created_at\" IS NOT NULL AND \"created_at\" < 10000000000;",
      "\nUPDATE \"connected_accounts\" SET \"updated_at\" = \"updated_at\" * 1000 WHERE \"updated_at\" IS NOT NULL AND \"updated_at\" < 10000000000;",
      "\nUPDATE \"scheduled_tasks\" SET \"created_at\" = \"created_at\" * 1000 WHERE \"created_at\" IS NOT NULL AND \"created_at\" < 10000000000;",
      "\nUPDATE \"scheduled_tasks\" SET \"next_execution_at\" = \"next_execution_at\" * 1000 WHERE \"next_execution_at\" IS NOT NULL AND \"next_execution_at\" < 10000000000;",
      "\nUPDATE \"scheduled_tasks\" SET \"last_executed_at\" = \"last_executed_at\" * 1000 WHERE \"last_executed_at\" IS NOT NULL AND \"last_executed_at\" < 10000000000;",
      "\nUPDATE \"scheduled_tasks\" SET \"cancelled_at\" = \"cancelled_at\" * 1000 WHERE \"cancelled_at\" IS NOT NULL AND \"cancelled_at\" < 10000000000;",
      "\nUPDATE \"notifications\" SET \"created_at\" = \"created_at\" * 1000 WHERE \"created_at\" IS NOT NULL AND \"created_at\" < 10000000000;",
      "\nUPDATE \"remote_mcp_servers\" SET \"created_at\" = \"created_at\" * 1000 WHERE \"created_at\" IS NOT NULL AND \"created_at\" < 10000000000;",
      "\nUPDATE \"remote_mcp_servers\" SET \"updated_at\" = \"updated_at\" * 1000 WHERE \"updated_at\" IS NOT NULL AND \"updated_at\" < 10000000000;",
      "\nUPDATE \"remote_mcp_servers\" SET \"tools_discovered_at\" = \"tools_discovered_at\" * 1000 WHERE \"tools_discovered_at\" IS NOT NULL AND \"tools_discovered_at\" < 10000000000;",
      "\nUPDATE \"remote_mcp_servers\" SET \"token_expires_at\" = \"token_expires_at\" * 1000 WHERE \"token_expires_at\" IS NOT NULL AND \"token_expires_at\" < 10000000000;",
      "\nUPDATE \"agent_connected_accounts\" SET \"created_at\" = \"created_at\" * 1000 WHERE \"created_at\" IS NOT NULL AND \"created_at\" < 10000000000;",
      "\nUPDATE \"agent_remote_mcps\" SET \"created_at\" = \"created_at\" * 1000 WHERE \"created_at\" IS NOT NULL AND \"created_at\" < 10000000000;",
      "\nUPDATE \"agent_acl\" SET \"created_at\" = \"created_at\" * 1000 WHERE \"created_at\" IS NOT NULL AND \"created_at\" < 10000000000;",
      "\nUPDATE \"notifications\" SET \"read_at\" = \"read_at\" * 1000 WHERE \"read_at\" IS NOT NULL AND \"read_at\" < 10000000000;",
      "\nUPDATE \"proxy_tokens\" SET \"created_at\" = \"created_at\" * 1000 WHERE \"created_at\" IS NOT NULL AND \"created_at\" < 10000000000;",
      "\nUPDATE \"proxy_audit_log\" SET \"created_at\" = \"created_at\" * 1000 WHERE \"created_at\" IS NOT NULL AND \"created_at\" < 10000000000;",
      "\nUPDATE \"mcp_audit_log\" SET \"created_at\" = \"created_at\" * 1000 WHERE \"created_at\" IS NOT NULL AND \"created_at\" < 10000000000;",
      "\nUPDATE \"user_settings\" SET \"updated_at\" = \"updated_at\" * 1000 WHERE \"updated_at\" IS NOT NULL AND \"updated_at\" < 10000000000;",
      "\nCREATE INDEX `connected_accounts_userId_idx` ON `connected_accounts` (`user_id`);",
      "\nCREATE INDEX `notifications_agent_slug_is_read_idx` ON `notifications` (`agent_slug`,`is_read`);",
      "\nCREATE INDEX `notifications_session_id_idx` ON `notifications` (`session_id`);",
      "\nCREATE INDEX `notifications_created_at_idx` ON `notifications` (`created_at`);\n"
    ],
    "bps": true,
    "folderMillis": 1772330637298,
    "hash": "e87bd154644a2d4c8f89e9b9d0a1c2a236839fb77878a901ca7eebbcc05f2fcd"
  },
  {
    "sql": [
      "ALTER TABLE `user` ADD `must_change_password` integer DEFAULT false;"
    ],
    "bps": true,
    "folderMillis": 1772490382333,
    "hash": "c5507d385a0a37607be391b0b9c27e92b922be2637c114688022ac792a700b14"
  },
  {
    "sql": [
      "ALTER TABLE `scheduled_tasks` ADD `timezone` text;"
    ],
    "bps": true,
    "folderMillis": 1772824655203,
    "hash": "621732cb755b07fdbbbbb01dac98732497547e8a49165d4d2ded6679104474b0"
  },
  {
    "sql": [
      "CREATE TABLE `message_author` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`session_id` text NOT NULL,\n\t`agent_slug` text NOT NULL,\n\t`user_id` text NOT NULL,\n\t`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade\n);\n",
      "\nCREATE INDEX `message_author_session_idx` ON `message_author` (`session_id`);"
    ],
    "bps": true,
    "folderMillis": 1773801909114,
    "hash": "7ef7a09b14358d990559d15fd5f5fc3d42e5339baf2130444a4e9b1984d099a4"
  },
  {
    "sql": [
      "CREATE TABLE `api_scope_policies` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`account_id` text NOT NULL,\n\t`scope` text NOT NULL,\n\t`decision` text NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL,\n\tFOREIGN KEY (`account_id`) REFERENCES `connected_accounts`(`id`) ON UPDATE no action ON DELETE cascade\n);\n",
      "\nCREATE UNIQUE INDEX `api_scope_policies_unique` ON `api_scope_policies` (`account_id`,`scope`);",
      "\nCREATE TABLE `mcp_tool_policies` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`mcp_id` text NOT NULL,\n\t`tool_name` text NOT NULL,\n\t`decision` text NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL,\n\tFOREIGN KEY (`mcp_id`) REFERENCES `remote_mcp_servers`(`id`) ON UPDATE no action ON DELETE cascade\n);\n",
      "\nCREATE UNIQUE INDEX `mcp_tool_policies_unique` ON `mcp_tool_policies` (`mcp_id`,`tool_name`);",
      "\nALTER TABLE `mcp_audit_log` ADD `policy_decision` text;",
      "\nALTER TABLE `mcp_audit_log` ADD `matched_tool` text;",
      "\nALTER TABLE `proxy_audit_log` ADD `policy_decision` text;",
      "\nALTER TABLE `proxy_audit_log` ADD `matched_scopes` text;"
    ],
    "bps": true,
    "folderMillis": 1773868062138,
    "hash": "d76bece6c7ff3c26e4b90b075e14be5eccb1f9b91c6337318aa7bbe8b0b9a816"
  },
  {
    "sql": [
      "CREATE TABLE `webhook_triggers` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`agent_slug` text NOT NULL,\n\t`composio_trigger_id` text,\n\t`connected_account_id` text NOT NULL,\n\t`trigger_type` text NOT NULL,\n\t`trigger_config` text,\n\t`prompt` text NOT NULL,\n\t`name` text,\n\t`status` text DEFAULT 'active' NOT NULL,\n\t`last_fired_at` integer,\n\t`fire_count` integer DEFAULT 0 NOT NULL,\n\t`last_session_id` text,\n\t`created_by_session_id` text,\n\t`created_by_user_id` text,\n\t`created_at` integer NOT NULL,\n\t`cancelled_at` integer\n);\n",
      "\nCREATE INDEX `webhook_triggers_agent_slug_idx` ON `webhook_triggers` (`agent_slug`);",
      "\nCREATE INDEX `webhook_triggers_status_idx` ON `webhook_triggers` (`status`);",
      "\nCREATE INDEX `webhook_triggers_composio_idx` ON `webhook_triggers` (`composio_trigger_id`);"
    ],
    "bps": true,
    "folderMillis": 1775185686077,
    "hash": "d466f0c53d5710d736cddb41a53ca06afb94586a618c9b54761826907a77aa62"
  },
  {
    "sql": [
      "CREATE TABLE `chat_integration_sessions` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`integration_id` text NOT NULL,\n\t`external_chat_id` text NOT NULL,\n\t`session_id` text NOT NULL,\n\t`display_name` text,\n\t`archived_at` integer,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL,\n\tFOREIGN KEY (`integration_id`) REFERENCES `chat_integrations`(`id`) ON UPDATE no action ON DELETE cascade\n);\n",
      "\nCREATE INDEX `chat_integration_sessions_integration_id_idx` ON `chat_integration_sessions` (`integration_id`);",
      "\nCREATE TABLE `chat_integrations` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`agent_slug` text NOT NULL,\n\t`provider` text NOT NULL,\n\t`name` text,\n\t`config` text NOT NULL,\n\t`show_tool_calls` integer DEFAULT false NOT NULL,\n\t`status` text DEFAULT 'active' NOT NULL,\n\t`error_message` text,\n\t`created_by_user_id` text,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL\n);\n",
      "\nCREATE INDEX `chat_integrations_agent_slug_idx` ON `chat_integrations` (`agent_slug`);",
      "\nCREATE INDEX `chat_integrations_status_idx` ON `chat_integrations` (`status`);"
    ],
    "bps": true,
    "folderMillis": 1776185147813,
    "hash": "6c51e55ef21c173b088e0d959bf9e6d2863a93962d394bf8758984f8b91f9100"
  },
  {
    "sql": [
      "CREATE TABLE `x_agent_policies` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`caller_agent_slug` text NOT NULL,\n\t`target_agent_slug` text,\n\t`operation` text NOT NULL,\n\t`decision` text NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL\n);\n",
      "\nCREATE UNIQUE INDEX `x_agent_policies_unique` ON `x_agent_policies` (`caller_agent_slug`,`target_agent_slug`,`operation`);",
      "\nCREATE INDEX `x_agent_policies_caller_idx` ON `x_agent_policies` (`caller_agent_slug`);\n"
    ],
    "bps": true,
    "folderMillis": 1776819603595,
    "hash": "7e9008c73691e23b833e5280cb91d327dd196d0cc584997d0a801e6ff808580b"
  },
  {
    "sql": [
      "ALTER TABLE `scheduled_tasks` ADD `paused_at` integer;"
    ],
    "bps": true,
    "folderMillis": 1776888109070,
    "hash": "5aafafcb748bb93c2423784dfbc2b0045183ff5cdba784cd05f588fc6e7b8641"
  },
  {
    "sql": [
      "ALTER TABLE `webhook_triggers` ADD `paused_at` integer;"
    ],
    "bps": true,
    "folderMillis": 1776889177663,
    "hash": "f6609db17d538141054fe8cf8e5f5c5beb9a735f7652bf0d40f7820268acc958"
  },
  {
    "sql": [
      "ALTER TABLE `scheduled_tasks` ADD `model` text;",
      "\nALTER TABLE `scheduled_tasks` ADD `effort` text;",
      "\nALTER TABLE `webhook_triggers` ADD `model` text;",
      "\nALTER TABLE `webhook_triggers` ADD `effort` text;"
    ],
    "bps": true,
    "folderMillis": 1778195676649,
    "hash": "94d7a16c5e553ab9f1f14d61a343498223eaecf4559ada5a511bfdf154caf9a1"
  },
  {
    "sql": [
      "ALTER TABLE `chat_integrations` ADD `session_timeout` integer;"
    ],
    "bps": true,
    "folderMillis": 1779329136558,
    "hash": "7d412b97cf23106b2b301228fd85254c806b0edbdda4dd5c3c7230053bcb5272"
  },
  {
    "sql": [
      "ALTER TABLE `chat_integrations` ADD `model` text;",
      "\nALTER TABLE `chat_integrations` ADD `effort` text;"
    ],
    "bps": true,
    "folderMillis": 1779381234820,
    "hash": "3c8cdc0313a9481c423cdd376dbecd6adc245d8b69b1754f945f69bb23aa33ef"
  },
  {
    "sql": [
      "CREATE TABLE `audit_log` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,\n\t`user_id` text,\n\t`object` text NOT NULL,\n\t`object_id` text NOT NULL,\n\t`action` text NOT NULL,\n\t`details` text\n);\n",
      "\nCREATE INDEX `audit_log_created_at_idx` ON `audit_log` (`created_at`);",
      "\nCREATE INDEX `audit_log_object_idx` ON `audit_log` (`object`);",
      "\nCREATE INDEX `audit_log_user_id_idx` ON `audit_log` (`user_id`);"
    ],
    "bps": true,
    "folderMillis": 1779412209444,
    "hash": "9d90efcd9b561ec76cb8205d14afae672979abc046ffe467ba4f8c236a4a3f56"
  },
  {
    "sql": [
      "ALTER TABLE `connected_accounts` RENAME COLUMN `composio_connection_id` TO `provider_connection_id`;",
      "\nALTER TABLE `connected_accounts` ADD `provider_name` text DEFAULT 'composio' NOT NULL;"
    ],
    "bps": true,
    "folderMillis": 1779754545446,
    "hash": "fc581dc5c194392cd655b935c9fd6708d348fda1dde57486eec56749acd0c227"
  },
  {
    "sql": [
      "PRAGMA foreign_keys=OFF;",
      "\nCREATE TABLE `__new_notifications` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`type` text NOT NULL,\n\t`session_id` text NOT NULL,\n\t`agent_slug` text NOT NULL,\n\t`title` text NOT NULL,\n\t`body` text NOT NULL,\n\t`is_read` integer DEFAULT false NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`read_at` integer\n);\n",
      "\nINSERT INTO `__new_notifications`(\"id\", \"type\", \"session_id\", \"agent_slug\", \"title\", \"body\", \"is_read\", \"created_at\", \"read_at\") SELECT \"id\", \"type\", \"session_id\", \"agent_slug\", \"title\", \"body\", \"is_read\", \"created_at\", \"read_at\" FROM `notifications`;",
      "\nDROP TABLE `notifications`;",
      "\nALTER TABLE `__new_notifications` RENAME TO `notifications`;",
      "\nPRAGMA foreign_keys=ON;",
      "\nCREATE INDEX `notifications_agent_slug_is_read_idx` ON `notifications` (`agent_slug`,`is_read`);",
      "\nCREATE INDEX `notifications_session_id_idx` ON `notifications` (`session_id`);",
      "\nCREATE INDEX `notifications_created_at_idx` ON `notifications` (`created_at`);"
    ],
    "bps": true,
    "folderMillis": 1780949981346,
    "hash": "a71474207b23d56a154257fbe3196e55d75f43402d4b778d8b1e5c9279283278"
  },
  {
    "sql": [
      "CREATE TABLE `chat_integration_access` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`integration_id` text NOT NULL,\n\t`external_chat_id` text NOT NULL,\n\t`chat_type` text,\n\t`status` text DEFAULT 'pending' NOT NULL,\n\t`approval_source` text,\n\t`title` text,\n\t`first_user_id` text,\n\t`first_user_name` text,\n\t`first_message_preview` text,\n\t`request_notice_sent_at` integer,\n\t`requested_at` integer NOT NULL,\n\t`decided_at` integer,\n\t`decided_by_user_id` text,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL,\n\tFOREIGN KEY (`integration_id`) REFERENCES `chat_integrations`(`id`) ON UPDATE no action ON DELETE cascade,\n\tCONSTRAINT \"chat_integration_access_status_check\" CHECK(\"chat_integration_access\".\"status\" in ('pending','allowed','denied')),\n\tCONSTRAINT \"chat_integration_access_chat_type_check\" CHECK(\"chat_integration_access\".\"chat_type\" is null or \"chat_integration_access\".\"chat_type\" in ('private','group','supergroup')),\n\tCONSTRAINT \"chat_integration_access_source_check\" CHECK(\"chat_integration_access\".\"approval_source\" is null or \"chat_integration_access\".\"approval_source\" in ('auto_first_contact','owner','migration'))\n);\n",
      "\nCREATE UNIQUE INDEX `chat_integration_access_unique` ON `chat_integration_access` (`integration_id`,`external_chat_id`);",
      "\nCREATE INDEX `chat_integration_access_status_idx` ON `chat_integration_access` (`integration_id`,`status`);",
      "\nALTER TABLE `chat_integrations` ADD `require_approval` integer DEFAULT true NOT NULL;"
    ],
    "bps": true,
    "folderMillis": 1781748623026,
    "hash": "ba565169f4fb5f0ab0746d43b6de2c3fbe90bd12071bb8040c86d20de6086acf"
  },
  {
    "sql": [
      "INSERT OR IGNORE INTO chat_integration_access\n  (id, integration_id, external_chat_id, chat_type, status, approval_source, requested_at, created_at, updated_at)\nSELECT\n  lower(hex(randomblob(16))), s.integration_id, s.external_chat_id, NULL, 'allowed', 'migration',\n  (strftime('%s','now') * 1000), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)\nFROM (\n  SELECT DISTINCT integration_id, external_chat_id\n  FROM chat_integration_sessions\n  WHERE archived_at IS NULL\n) s\nJOIN chat_integrations ci ON ci.id = s.integration_id\nWHERE ci.provider = 'telegram';\n"
    ],
    "bps": true,
    "folderMillis": 1781000000000,
    "hash": "698b2c37c44b20a1c77dee865617f415c2f73e2c2d7d5505bcd1ed451e5c8c4e"
  },
  {
    "sql": [
      "ALTER TABLE `proxy_audit_log` ADD `duration_ms` integer;"
    ],
    "bps": true,
    "folderMillis": 1782496663785,
    "hash": "22d2203281b88e3b5f625ea845efb5667a295d9e6d01e7be809fdb3b3de822f6"
  },
  {
    "sql": [
      "PRAGMA foreign_keys=OFF;",
      "\nCREATE TABLE `__new_webhook_triggers` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`agent_slug` text NOT NULL,\n\t`kind` text DEFAULT 'composio' NOT NULL,\n\t`composio_trigger_id` text,\n\t`connected_account_id` text,\n\t`trigger_type` text NOT NULL,\n\t`trigger_config` text,\n\t`prompt` text NOT NULL,\n\t`name` text,\n\t`status` text DEFAULT 'active' NOT NULL,\n\t`last_fired_at` integer,\n\t`fire_count` integer DEFAULT 0 NOT NULL,\n\t`last_session_id` text,\n\t`created_by_session_id` text,\n\t`created_by_user_id` text,\n\t`model` text,\n\t`effort` text,\n\t`created_at` integer NOT NULL,\n\t`cancelled_at` integer,\n\t`paused_at` integer\n);\n",
      "\nINSERT INTO `__new_webhook_triggers`(\"id\", \"agent_slug\", \"kind\", \"composio_trigger_id\", \"connected_account_id\", \"trigger_type\", \"trigger_config\", \"prompt\", \"name\", \"status\", \"last_fired_at\", \"fire_count\", \"last_session_id\", \"created_by_session_id\", \"created_by_user_id\", \"model\", \"effort\", \"created_at\", \"cancelled_at\", \"paused_at\") SELECT \"id\", \"agent_slug\", 'composio', \"composio_trigger_id\", \"connected_account_id\", \"trigger_type\", \"trigger_config\", \"prompt\", \"name\", \"status\", \"last_fired_at\", \"fire_count\", \"last_session_id\", \"created_by_session_id\", \"created_by_user_id\", \"model\", \"effort\", \"created_at\", \"cancelled_at\", \"paused_at\" FROM `webhook_triggers`;",
      "\nDROP TABLE `webhook_triggers`;",
      "\nALTER TABLE `__new_webhook_triggers` RENAME TO `webhook_triggers`;",
      "\nPRAGMA foreign_keys=ON;",
      "\nCREATE INDEX `webhook_triggers_agent_slug_idx` ON `webhook_triggers` (`agent_slug`);",
      "\nCREATE INDEX `webhook_triggers_status_idx` ON `webhook_triggers` (`status`);",
      "\nCREATE INDEX `webhook_triggers_composio_idx` ON `webhook_triggers` (`composio_trigger_id`);"
    ],
    "bps": true,
    "folderMillis": 1783372063408,
    "hash": "073cb0753c5a3964b54aeeced5f4c318b6cd522935c29c1361bd29f034b359a1"
  },
  {
    "sql": [
      "CREATE INDEX `mcp_audit_log_agent_slug_created_at_idx` ON `mcp_audit_log` (`agent_slug`,`created_at`);",
      "\nCREATE INDEX `mcp_audit_log_remote_mcp_id_created_at_idx` ON `mcp_audit_log` (`remote_mcp_id`,`created_at`);",
      "\nCREATE INDEX `proxy_audit_log_agent_slug_created_at_idx` ON `proxy_audit_log` (`agent_slug`,`created_at`);",
      "\nCREATE INDEX `proxy_audit_log_account_id_created_at_idx` ON `proxy_audit_log` (`account_id`,`created_at`);"
    ],
    "bps": true,
    "folderMillis": 1783649401734,
    "hash": "2d7efbf751906478e95698a7b130a81f33e237e2bbd61e871ef794cf8021bdfc"
  },
  {
    "sql": [
      "ALTER TABLE `scheduled_tasks` ADD `resume_session_id` text;"
    ],
    "bps": true,
    "folderMillis": 1784043298646,
    "hash": "d38026ae235f862938112aab21a140243539b6573c6da0eb3e324ed67a18e5e9"
  },
  {
    "sql": [
      "CREATE UNIQUE INDEX `scheduled_tasks_pending_wake_unique` ON `scheduled_tasks` (`resume_session_id`) WHERE status = 'pending' AND resume_session_id IS NOT NULL;"
    ],
    "bps": true,
    "folderMillis": 1784054072546,
    "hash": "625a118d2d095e1a86e06692ae550c89824d89ac669beb90a32067708a300d9b"
  },
  {
    "sql": [
      "ALTER TABLE `chat_integrations` ADD `speed` text;",
      "\nALTER TABLE `scheduled_tasks` ADD `speed` text;",
      "\nALTER TABLE `webhook_triggers` ADD `speed` text;"
    ],
    "bps": true,
    "folderMillis": 1784149867035,
    "hash": "457d5a3101d7071d87cf553aae1f86d817ce3c077dd37aedd6b202b4ce209a11"
  },
  {
    "sql": [
      "CREATE INDEX IF NOT EXISTS `mcp_audit_log_mcp_agent_idx` ON `mcp_audit_log` (`remote_mcp_id`,`agent_slug`);",
      "\nCREATE INDEX IF NOT EXISTS `proxy_audit_log_account_agent_idx` ON `proxy_audit_log` (`account_id`,`agent_slug`);"
    ],
    "bps": true,
    "folderMillis": 1784233277152,
    "hash": "c147740081c25cbf482257c163e575ccc317c93c787fdb4db9b7ab577aa6bfc1"
  },
  {
    "sql": [
      "CREATE TABLE `token_exchange_jti` (\n\t`jti` text PRIMARY KEY NOT NULL,\n\t`expires_at` integer NOT NULL\n);\n",
      "\nCREATE INDEX `token_exchange_jti_expires_at_idx` ON `token_exchange_jti` (`expires_at`);",
      "\nDELETE FROM `account` WHERE `rowid` NOT IN (SELECT MIN(`rowid`) FROM `account` GROUP BY `provider_id`, `account_id`);",
      "\nCREATE UNIQUE INDEX `account_provider_account_unique` ON `account` (`provider_id`,`account_id`);"
    ],
    "bps": true,
    "folderMillis": 1784841760603,
    "hash": "039f46411d19d07e0115890e66ab5fc95a1746c0d9f35f67fa59f338daf4cf55"
  },
  {
    "sql": [
      "ALTER TABLE `session` ADD `creation_method` text;"
    ],
    "bps": true,
    "folderMillis": 1785019349876,
    "hash": "7d409a144239543b71732635accc903f285b8b46cafde6e3f760ef81ef843518"
  },
  {
    "sql": [
      "CREATE TABLE `mobile_device` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`refresh_token_hash` text NOT NULL,\n\t`device_name` text,\n\t`platform` text,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL,\n\t`expires_at` integer NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade\n);\n",
      "\nCREATE UNIQUE INDEX `mobile_device_refresh_token_hash_unique` ON `mobile_device` (`refresh_token_hash`);",
      "\nCREATE INDEX `mobile_device_user_id_idx` ON `mobile_device` (`user_id`);",
      "\nCREATE INDEX `mobile_device_expires_at_idx` ON `mobile_device` (`expires_at`);",
      "\nCREATE TABLE `mobile_pairing_token` (\n\t`token_hash` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`expires_at` integer NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade\n);\n",
      "\nCREATE INDEX `mobile_pairing_token_expires_at_idx` ON `mobile_pairing_token` (`expires_at`);",
      "\nALTER TABLE `session` ADD `device_id` text REFERENCES mobile_device(id) ON DELETE cascade;",
      "\nCREATE INDEX `session_device_id_idx` ON `session` (`device_id`);\n"
    ],
    "bps": true,
    "folderMillis": 1785783356768,
    "hash": "6d501111acab181e6d2506de3c76070b16bb9012d9d00544aec390c8d76cc478"
  },
  {
    "sql": [
      "CREATE TABLE `push_subscriptions` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`endpoint` text NOT NULL,\n\t`keys_p256dh` text NOT NULL,\n\t`keys_auth` text NOT NULL,\n\t`origin` text NOT NULL,\n\t`user_id` text,\n\t`device_name` text,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL\n);\n",
      "\nCREATE UNIQUE INDEX `push_subscriptions_endpoint_unique` ON `push_subscriptions` (`endpoint`);",
      "\nCREATE INDEX `push_subscriptions_user_id_idx` ON `push_subscriptions` (`user_id`);",
      "\nCREATE TABLE `push_vapid_keys` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`public_key` text NOT NULL,\n\t`private_key` text NOT NULL,\n\t`created_at` integer NOT NULL\n);\n"
    ],
    "bps": true,
    "folderMillis": 1786055590568,
    "hash": "23ff2423774a497a14467f6bdc4b79d237b1c2ab16f83a6d000c44ad66ee4379"
  },
  {
    "sql": [
      "CREATE TABLE `apns_devices` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`token` text NOT NULL,\n\t`environment` text DEFAULT 'production' NOT NULL,\n\t`user_id` text,\n\t`mobile_device_id` text,\n\t`workspace_tag` text,\n\t`device_name` text,\n\t`platform` text DEFAULT 'ios' NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL,\n\tFOREIGN KEY (`mobile_device_id`) REFERENCES `mobile_device`(`id`) ON UPDATE no action ON DELETE cascade\n);\n",
      "\nCREATE UNIQUE INDEX `apns_devices_token_unique` ON `apns_devices` (`token`);",
      "\nCREATE INDEX `apns_devices_user_id_idx` ON `apns_devices` (`user_id`);",
      "\nCREATE INDEX `apns_devices_mobile_device_id_idx` ON `apns_devices` (`mobile_device_id`);"
    ],
    "bps": true,
    "folderMillis": 1786728485469,
    "hash": "cf53ad3ac38156b66f53d5f024ebf38612b6a123e926fbec4fafd17aca2a3da6"
  },
  {
    "sql": [
      "CREATE TABLE `session_unread_marks` (\n\t`session_id` text NOT NULL,\n\t`user_id` text NOT NULL,\n\t`agent_slug` text NOT NULL,\n\t`marked_at` integer NOT NULL,\n\tPRIMARY KEY(`session_id`, `user_id`)\n);\n",
      "\nCREATE INDEX `session_unread_marks_agent_slug_user_idx` ON `session_unread_marks` (`agent_slug`,`user_id`);\n"
    ],
    "bps": true,
    "folderMillis": 1787774911000,
    "hash": "e375f06ec49f65864f3266ac9b57c49ed7159601ea4a8b37e07c1237fcfb51d1"
  },
  {
    "sql": [
      "-- Session ids are unique only WITHIN an agent (import/clone gives two agents\n-- the same id), so the mark's identity is (agent, session, user), not\n-- (session, user). Under the old PK a second agent's mark for a shared id was\n-- swallowed by the INSERT ... ON CONFLICT DO NOTHING, and a clear/delete on the\n-- bare id crossed agents. SQLite cannot alter a primary key in place, so\n-- rebuild the table. agent_slug is already NOT NULL, so every existing row\n-- carries into the wider key unchanged.\nCREATE TABLE `session_unread_marks_new` (\n\t`session_id` text NOT NULL,\n\t`user_id` text NOT NULL,\n\t`agent_slug` text NOT NULL,\n\t`marked_at` integer NOT NULL,\n\tPRIMARY KEY(`agent_slug`, `session_id`, `user_id`)\n);\n",
      "\nINSERT OR IGNORE INTO `session_unread_marks_new` (`session_id`, `user_id`, `agent_slug`, `marked_at`)\n\tSELECT `session_id`, `user_id`, `agent_slug`, `marked_at` FROM `session_unread_marks`;\n",
      "\nDROP TABLE `session_unread_marks`;\n",
      "\nALTER TABLE `session_unread_marks_new` RENAME TO `session_unread_marks`;\n",
      "\nCREATE INDEX `session_unread_marks_agent_slug_user_idx` ON `session_unread_marks` (`agent_slug`,`user_id`);\n"
    ],
    "bps": true,
    "folderMillis": 1787774912000,
    "hash": "4f5ca9f90c1013d2454c11b5941efec3802b62a898881ae37b764244f0cd4ca7"
  },
  {
    "sql": [
      "ALTER TABLE `webhook_triggers` ADD `minted_by_member_id` text;\n"
    ],
    "bps": true,
    "folderMillis": 1788396615359,
    "hash": "4262731343c7ccb1258a4a93ae65581b02b95a9eb4707c0ad601439ef45d93c9"
  },
  {
    "sql": [
      "ALTER TABLE `user` ADD `avatar_override` text;"
    ],
    "bps": true,
    "folderMillis": 1789059097911,
    "hash": "256ba8e0b57b424926780ab72ce1c477f62011211a92a834d92d2a29a552cab5"
  },
  {
    "sql": [
      "CREATE INDEX `user_avatar_override_idx` ON `user` (`avatar_override`);"
    ],
    "bps": true,
    "folderMillis": 1789080776897,
    "hash": "d8c9be1bb76ee027dcccd56196e5d7ac1a277802f6ff6558f599b9cb8aa448a5"
  },
  {
    "sql": [
      "CREATE TABLE `agents` (\n\t`slug` text PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`description` text,\n\t`created_at` integer NOT NULL,\n\t`runtime` text DEFAULT 'local' NOT NULL,\n\t`workspace_handle` text\n);\n"
    ],
    "bps": true,
    "folderMillis": 1789438768720,
    "hash": "fbf6a9d43eb88deb2fa0597eec0f8f87fd06f30508db5201af9e170d734f2d8c"
  },
  {
    "sql": [
      "CREATE TABLE `data_migrations` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`applied_at` integer NOT NULL\n);\n"
    ],
    "bps": true,
    "folderMillis": 1789495471204,
    "hash": "e55e2884b15ce1917f3b940087b4d948529f40ae6a31eb01cf3ec733cc5916ba"
  },
  {
    "sql": [
      "-- A plain unique index treats NULL as distinct, so global (null-target)\n-- policies could be duplicated by concurrent writes before setPolicy became a\n-- single upsert. Keep the most recently updated global row per (caller,\n-- operation), then add the NULL-folded unique key the upsert conflicts on.\nDELETE FROM `x_agent_policies` WHERE `target_agent_slug` IS NULL AND `id` NOT IN (\n\tSELECT `id` FROM (\n\t\tSELECT `id`, max(`updated_at`) AS `latest` FROM `x_agent_policies`\n\t\tWHERE `target_agent_slug` IS NULL GROUP BY `caller_agent_slug`, `operation`\n\t)\n);",
      "\nCREATE UNIQUE INDEX `x_agent_policies_null_safe_unique` ON `x_agent_policies` (`caller_agent_slug`,coalesce(`target_agent_slug`, ''),`operation`);\n"
    ],
    "bps": true,
    "folderMillis": 1789518638375,
    "hash": "6906152608f597f14f944a084192ab955682842dd8244813398b250388a3df3c"
  },
  {
    "sql": [
      "CREATE TABLE `slack_thread_state` (\n\t`integration_id` text PRIMARY KEY NOT NULL,\n\t`bot_user_id` text NOT NULL,\n\t`active_threads` text NOT NULL,\n\tFOREIGN KEY (`integration_id`) REFERENCES `chat_integrations`(`id`) ON UPDATE no action ON DELETE cascade\n);\n"
    ],
    "bps": true,
    "folderMillis": 1789574400000,
    "hash": "0d2efc5a8980924af6cee3527d6a3271144086f77256dff2907f499b7e61e02c"
  },
  {
    "sql": [
      "ALTER TABLE `scheduled_tasks` ADD `consecutive_skips` integer DEFAULT 0 NOT NULL;",
      "\nALTER TABLE `scheduled_tasks` ADD `last_skipped_at` integer;"
    ],
    "bps": true,
    "folderMillis": 1790040447107,
    "hash": "841f5d556872c1e923410a1264069897e55c42f194983f8fee8531fe566b267c"
  },
  {
    "sql": [
      "CREATE TABLE `integration_deliveries` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`integration_id` text NOT NULL,\n\t`external_id` text NOT NULL,\n\t`event_id` text NOT NULL,\n\t`envelope` text,\n\t`session_id` text,\n\t`state` text DEFAULT 'pending' NOT NULL,\n\t`attempts` integer DEFAULT 0 NOT NULL,\n\t`owner` text,\n\t`next_attempt_at` integer NOT NULL,\n\t`notice_state` text DEFAULT 'none' NOT NULL,\n\t`notice_attempts` integer DEFAULT 0 NOT NULL,\n\t`error` text,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL,\n\tFOREIGN KEY (`integration_id`) REFERENCES `chat_integrations`(`id`) ON UPDATE no action ON DELETE cascade\n);\n",
      "\nCREATE UNIQUE INDEX `integration_deliveries_event_idx` ON `integration_deliveries` (`integration_id`,`external_id`,`event_id`);",
      "\nCREATE INDEX `integration_deliveries_due_idx` ON `integration_deliveries` (`state`,`next_attempt_at`);",
      "\nCREATE INDEX `integration_deliveries_notice_idx` ON `integration_deliveries` (`notice_state`,`next_attempt_at`);"
    ],
    "bps": true,
    "folderMillis": 1790107007902,
    "hash": "97d1ee90bc2cb982ac039fffb71ed61f7ce3afdd3e44d0c597b0f5c4ddab9c9e"
  },
  {
    "sql": [
      "CREATE TABLE `llm_connections` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text,\n\t`name` text NOT NULL,\n\t`provider` text NOT NULL,\n\t`managed` integer DEFAULT false NOT NULL,\n\t`config` text NOT NULL,\n\t`model_overrides` text DEFAULT '[]' NOT NULL,\n\t`browser_model` text,\n\t`dashboard_model` text,\n\t`generation` integer DEFAULT 0 NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade\n);\n",
      "\nCREATE INDEX `llm_connections_owner_idx` ON `llm_connections` (`user_id`);",
      "\nCREATE UNIQUE INDEX `llm_connections_platform_unique` ON `llm_connections` (`provider`) WHERE provider = 'platform';",
      "\nALTER TABLE `chat_integrations` ADD `llm_provider_id` text REFERENCES llm_connections(id) ON DELETE SET NULL;",
      "\nALTER TABLE `scheduled_tasks` ADD `llm_provider_id` text REFERENCES llm_connections(id) ON DELETE SET NULL;",
      "\nALTER TABLE `webhook_triggers` ADD `llm_provider_id` text REFERENCES llm_connections(id) ON DELETE SET NULL;"
    ],
    "bps": true,
    "folderMillis": 1790107007903,
    "hash": "83e4baf8856c8602ade2f60a396a13ac628d626f761765398eea9e7d4d25951a"
  },
  {
    "sql": [
      "-- A message's author is either a person in the app or an agent integration.\n-- Integration rows carry no user, so user_id becomes nullable, and they hold\n-- the card the app draws for the message (display, JSON). SQLite cannot drop\n-- NOT NULL in place, so rebuild the table; every existing row is a user row\n-- and carries over unchanged. Nothing references message_author.\nCREATE TABLE `message_author_new` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`session_id` text NOT NULL,\n\t`agent_slug` text NOT NULL,\n\t`user_id` text,\n\t`integration_id` text,\n\t`display` text,\n\t`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade,\n\tCONSTRAINT \"message_author_author_check\" CHECK((\"user_id\" is null) <> (\"integration_id\" is null) and (\"integration_id\" is null) = (\"display\" is null))\n);\n",
      "\nINSERT INTO `message_author_new` (`id`, `session_id`, `agent_slug`, `user_id`, `created_at`)\n\tSELECT `id`, `session_id`, `agent_slug`, `user_id`, `created_at` FROM `message_author`;\n",
      "\nDROP TABLE `message_author`;\n",
      "\nALTER TABLE `message_author_new` RENAME TO `message_author`;\n",
      "\nCREATE INDEX `message_author_session_idx` ON `message_author` (`session_id`);\n"
    ],
    "bps": true,
    "folderMillis": 1790125000109,
    "hash": "2a55801aa6124e98dfa6d1ced402a9b81c60bf21237bbf2eb2c6ca3abe8eace9"
  }
]
