import * as fs from 'fs'
import * as path from 'path'
import pLimit from 'p-limit'

export interface ModelBreakdown {
  modelName: string
  inputTokens: number
  outputTokens: number
  cacheCreationTokens: number
  cacheReadTokens: number
  cost: number
}

export interface DailyUsageData {
  date: string
  inputTokens: number
  outputTokens: number
  cacheCreationTokens: number
  cacheReadTokens: number
  totalCost: number
  modelBreakdowns: ModelBreakdown[]
}

interface UsageEntry {
  timestamp: string
  message?: {
    id?: string
    model?: string
    usage?: {
      input_tokens?: number
      output_tokens?: number
      cache_creation_input_tokens?: number
      cache_read_input_tokens?: number
    }
  }
  requestId?: string
  costUSD?: number
}

interface LoadOptions {
  claudePath: string
  since?: string
  concurrency?: number
}

// Per-million-token pricing for known Claude models.
// Generated by: npx tsx scripts/fetch-model-pricing.ts
// When costUSD is present in the JSONL entry, it takes precedence over this table.
import MODEL_PRICING from './model-pricing.json'

/**
 * Calculate cost from token counts using hardcoded pricing.
 * Returns 0 for unknown models.
 */
function calculateCost(
  model: string,
  inputTokens: number,
  outputTokens: number,
  cacheCreationTokens: number,
  cacheReadTokens: number,
): number {
  const pricing = (MODEL_PRICING as Record<string, { input: number; output: number; cacheCreation: number; cacheRead: number }>)[model]
  if (!pricing) return 0

  return (
    (inputTokens * pricing.input +
      outputTokens * pricing.output +
      cacheCreationTokens * pricing.cacheCreation +
      cacheReadTokens * pricing.cacheRead) /
    1_000_000
  )
}

async function findJsonlFiles(dir: string): Promise<string[]> {
  const results: string[] = []
  const entries = await fs.promises.readdir(dir, { withFileTypes: true })
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      results.push(...(await findJsonlFiles(fullPath)))
    } else if (entry.name.endsWith('.jsonl')) {
      results.push(fullPath)
    }
  }
  return results
}

/**
 * Lightweight replacement for ccusage's loadDailyUsageData.
 * - Pre-filters files by mtime when `since` is set
 * - Limits concurrent file reads via pLimit
 * - Deduplicates entries by messageId:requestId
 * - Uses costUSD field when available
 */
export async function loadDailyUsageData(options: LoadOptions): Promise<DailyUsageData[]> {
  const { claudePath, since, concurrency = 10 } = options

  const projectsDir = path.join(claudePath, 'projects')
  try {
    await fs.promises.access(projectsDir)
  } catch {
    return []
  }

  // Recursively find all JSONL files
  let files: string[]
  try {
    files = await findJsonlFiles(projectsDir)
  } catch {
    return []
  }

  if (files.length === 0) return []

  // Parse the since date for filtering
  let sinceDate: Date | null = null
  if (since) {
    // since format: "YYYYMMDD"
    const y = parseInt(since.substring(0, 4), 10)
    const m = parseInt(since.substring(4, 6), 10) - 1
    const d = parseInt(since.substring(6, 8), 10)
    sinceDate = new Date(y, m, d)
  }

  // Pre-filter files by mtime when since is set
  if (sinceDate) {
    const sinceMs = sinceDate.getTime()
    const limit = pLimit(concurrency)
    const statResults = await Promise.all(
      files.map((file) =>
        limit(async () => {
          try {
            const stat = await fs.promises.stat(file)
            return stat.mtimeMs >= sinceMs ? file : null
          } catch {
            return null
          }
        })
      )
    )
    files = statResults.filter((f): f is string => f !== null)
  }

  if (files.length === 0) return []

  // Stream-read files with concurrency limit.
  // Pre-filter lines with a cheap string check before JSON.parse — most lines
  // in session JSONL files are user/assistant messages without usage data.
  const limit = pLimit(concurrency)
  const seen = new Set<string>()
  const dateMap = new Map<
    string,
    {
      inputTokens: number
      outputTokens: number
      cacheCreationTokens: number
      cacheReadTokens: number
      totalCost: number
      models: Map<
        string,
        {
          inputTokens: number
          outputTokens: number
          cacheCreationTokens: number
          cacheReadTokens: number
          cost: number
        }
      >
    }
  >()

  await Promise.all(
    files.map((file) =>
      limit(async () => {
        let fh: fs.promises.FileHandle | null = null
        try {
          fh = await fs.promises.open(file, 'r')
          const stream = fh.createReadStream({ encoding: 'utf-8' })
          let buffer = ''

          for await (const chunk of stream) {
            buffer += chunk
            const lines = buffer.split('\n')
            // Keep last (potentially incomplete) line in buffer
            buffer = lines.pop() || ''

            for (const line of lines) {
              processLine(line, seen, sinceDate, dateMap)
            }
          }
          // Process any remaining content
          if (buffer.trim()) {
            processLine(buffer, seen, sinceDate, dateMap)
          }
        } catch {
          // Skip unreadable files
        } finally {
          await fh?.close()
        }
      })
    )
  )

  function processLine(
    line: string,
    seenSet: Set<string>,
    sinceDateFilter: Date | null,
    map: typeof dateMap,
  ) {
    // Cheap pre-filter: skip lines that can't contain usage data
    if (!line.includes('"input_tokens"')) return

    let entry: UsageEntry
    try {
      entry = JSON.parse(line)
    } catch {
      return
    }

    if (!entry.message?.usage?.input_tokens && !entry.message?.usage?.output_tokens) return
    if (!entry.timestamp) return

    // Deduplicate by messageId:requestId
    const msgId = entry.message?.id || ''
    const reqId = entry.requestId || ''
    if (msgId && reqId) {
      const key = `${msgId}:${reqId}`
      if (seenSet.has(key)) return
      seenSet.add(key)
    }

    // Filter by date if since is set
    if (sinceDateFilter && new Date(entry.timestamp) < sinceDateFilter) return

    // Use local timezone for date grouping (matches ccusage behavior)
    const ts = new Date(entry.timestamp)
    const date = `${ts.getFullYear()}-${String(ts.getMonth() + 1).padStart(2, '0')}-${String(ts.getDate()).padStart(2, '0')}`
    const model = entry.message?.model || 'unknown'
    const usage = entry.message!.usage!

    const inputTokens = usage.input_tokens || 0
    const outputTokens = usage.output_tokens || 0
    const cacheCreationTokens = usage.cache_creation_input_tokens || 0
    const cacheReadTokens = usage.cache_read_input_tokens || 0
    const cost = entry.costUSD ??
      calculateCost(model, inputTokens, outputTokens, cacheCreationTokens, cacheReadTokens)

    let day = map.get(date)
    if (!day) {
      day = {
        inputTokens: 0,
        outputTokens: 0,
        cacheCreationTokens: 0,
        cacheReadTokens: 0,
        totalCost: 0,
        models: new Map(),
      }
      map.set(date, day)
    }

    day.inputTokens += inputTokens
    day.outputTokens += outputTokens
    day.cacheCreationTokens += cacheCreationTokens
    day.cacheReadTokens += cacheReadTokens
    day.totalCost += cost

    let modelData = day.models.get(model)
    if (!modelData) {
      modelData = {
        inputTokens: 0,
        outputTokens: 0,
        cacheCreationTokens: 0,
        cacheReadTokens: 0,
        cost: 0,
      }
      day.models.set(model, modelData)
    }

    modelData.inputTokens += inputTokens
    modelData.outputTokens += outputTokens
    modelData.cacheCreationTokens += cacheCreationTokens
    modelData.cacheReadTokens += cacheReadTokens
    modelData.cost += cost
  }

  // Convert to output format
  const results: DailyUsageData[] = []
  for (const [date, day] of dateMap) {
    const modelBreakdowns: ModelBreakdown[] = []
    for (const [modelName, data] of day.models) {
      modelBreakdowns.push({ modelName, ...data })
    }

    results.push({
      date,
      inputTokens: day.inputTokens,
      outputTokens: day.outputTokens,
      cacheCreationTokens: day.cacheCreationTokens,
      cacheReadTokens: day.cacheReadTokens,
      totalCost: day.totalCost,
      modelBreakdowns,
    })
  }

  // Sort by date descending (newest first, matching ccusage)
  results.sort((a, b) => b.date.localeCompare(a.date))
  return results
}
