import * as fs from 'fs'
import * as path from 'path'
import pLimit from 'p-limit'
import {
  getEffectiveCatalog,
  getProviderCatalog,
  type LlmProviderId,
  type ModelDefinition,
} from '../llm-provider'
import type { SessionUsageTotals } from '../types/usage'

export interface ModelBreakdown {
  modelName: string
  inputTokens: number
  outputTokens: number
  cacheCreationTokens: number
  cacheReadTokens: number
  cost: number
}

export interface DailyUsageData {
  date: string
  inputTokens: number
  outputTokens: number
  cacheCreationTokens: number
  cacheReadTokens: number
  totalCost: number
  priceMissing: boolean
  modelBreakdowns: ModelBreakdown[]
}

interface CacheCreationUsage {
  ephemeral_5m_input_tokens?: number
  ephemeral_1h_input_tokens?: number
}

interface TokenUsage {
  input_tokens?: number
  output_tokens?: number
  cache_creation_input_tokens?: number
  cache_read_input_tokens?: number
  /**
   * Newer transcripts split cache writes by TTL. When present, this breakdown
   * is authoritative over the legacy aggregate above.
   */
  cache_creation?: CacheCreationUsage | null
  // Served speed tier echoed into the transcript ('slow'/'fast'; natively by
  // Anthropic fast mode, by the platform proxy for translated OpenAI/xAI
  // usage). Absent or 'standard' means standard-tier billing.
  speed?: string | null
}

interface UsageIteration extends TokenUsage {
  type?: string
  model?: string
}

interface MessageUsage extends TokenUsage {
  iterations?: UsageIteration[] | null
}

interface UsageEntry {
  timestamp: string
  requestId?: string
  isSidechain?: boolean
  advisorModel?: string
  message?: {
    id?: string
    model?: string
    usage?: MessageUsage
  }
  costUSD?: number
}

interface CommonLoadOptions {
  since?: string
  concurrency?: number
  providerId?: LlmProviderId
  loadStatus?: UsageLoadStatus
}

interface UsageLoadStatus {
  incomplete: boolean
}

interface LoadOptions extends CommonLoadOptions {
  claudePath: string
}

interface SessionLoadOptions extends CommonLoadOptions {
  sessionPath: string
}

interface CountedUsage {
  date: string
  model: string
  inputTokens: number
  outputTokens: number
  cacheCreationTokens: number
  cacheReadTokens: number
  cost: number
  priceMissing: boolean
  requestId?: string
  isSidechain: boolean
  hasSpeedMetadata: boolean
}

interface ParsedTokenUsage {
  inputTokens: number
  outputTokens: number
  cacheCreation5mTokens: number
  cacheCreation1hTokens: number
  cacheReadTokens: number
  speed?: keyof SpeedMultipliers
  hasSpeedMetadata: boolean
}

type CountedUsageBuckets = Map<string, CountedUsage[]>

// Per-million-token pricing for known Claude models.
// Generated by: npx tsx scripts/fetch-model-pricing.ts
// When costUSD is present in the JSONL entry, it takes precedence over this table.
import MODEL_PRICING from './model-pricing.json'

interface RateCard {
  input: number
  output: number
  cacheCreation: number
  /** One-hour cache writes. Older cards omit this; Anthropic's default is 2x input. */
  cacheCreation1h?: number
  cacheRead: number
}

interface SpeedMultipliers {
  slow?: number
  fast?: number
}

interface PricingEntry extends RateCard {
  // Context tier cards are not independently effective-dated; no current
  // model combines either context card with historicalRates.
  // OpenAI GPT-5.x 272K cliff: above `thresholdTokens` of prompt input the whole
  // request reprices at these rates. Mirror of the proxy's pricing table.
  longContext?: RateCard & { thresholdTokens: number }
  // Anthropic's long-context premium is marginal: each token category gets
  // its own allowance at the base rate before the remainder uses this card.
  marginalLongContext?: RateCard & { thresholdTokens: number }
  // Historical / scheduled rates apply to transcript rows before the cutoff.
  // The top-level card is the rate in force after every listed cutoff.
  historicalRates?: Array<RateCard & { before: string }>
  // Served-tier billing multipliers (flex/priority/fast mode). Applied on top
  // of whichever rate set (base or longContext) a request lands on; an absent
  // tier bills standard (1x). Mirror of the proxy's pricing table.
  speedMultipliers?: SpeedMultipliers
}

function cacheCreation1hRate(pricing: RateCard): number {
  return pricing.cacheCreation1h ?? pricing.input * 2
}

function ratesForTimestamp(pricing: PricingEntry, timestampMs?: number): RateCard {
  if (timestampMs === undefined || !Number.isFinite(timestampMs)) return pricing

  let selected: { cutoffMs: number; rates: RateCard } | undefined
  for (const historical of pricing.historicalRates ?? []) {
    const cutoffMs = Date.parse(historical.before)
    // With multiple historical eras, the earliest cutoff after the row is the
    // applicable one: <2025 chooses the <2025 card, not a later <2026 card.
    if (
      Number.isFinite(cutoffMs) &&
      timestampMs < cutoffMs &&
      (selected === undefined || cutoffMs < selected.cutoffMs)
    ) {
      selected = { cutoffMs, rates: historical }
    }
  }
  return selected?.rates ?? pricing
}

function deriveTierRate(tierRate: number, baseRate: number, replacementBaseRate: number): number {
  if (baseRate === 0) return tierRate === 0 ? 0 : tierRate
  return replacementBaseRate * (tierRate / baseRate)
}

function rebaseContextRateCard(
  tier: RateCard & { thresholdTokens: number },
  staticBase: PricingEntry,
  replacementBase: RateCard,
): RateCard & { thresholdTokens: number } {
  return {
    thresholdTokens: tier.thresholdTokens,
    input: deriveTierRate(tier.input, staticBase.input, replacementBase.input),
    output: deriveTierRate(tier.output, staticBase.output, replacementBase.output),
    cacheCreation: deriveTierRate(
      tier.cacheCreation,
      staticBase.cacheCreation,
      replacementBase.cacheCreation,
    ),
    cacheCreation1h: deriveTierRate(
      cacheCreation1hRate(tier),
      cacheCreation1hRate(staticBase),
      cacheCreation1hRate(replacementBase),
    ),
    cacheRead: deriveTierRate(tier.cacheRead, staticBase.cacheRead, replacementBase.cacheRead),
  }
}

function deriveInputRelatedRate(
  inputRate: number,
  staticPricing: PricingEntry | undefined,
  field: 'cacheCreation' | 'cacheCreation1h' | 'cacheRead',
): number {
  if (!staticPricing || staticPricing.input <= 0) {
    if (field === 'cacheRead') return inputRate * 0.1
    return field === 'cacheCreation1h' ? inputRate * 2 : inputRate
  }
  const staticRate =
    field === 'cacheCreation1h' ? cacheCreation1hRate(staticPricing) : staticPricing[field]
  return inputRate * (staticRate / staticPricing.input)
}

function sameCatalogTokenRates(
  left: ModelDefinition['pricing'],
  right: ModelDefinition['pricing'],
): boolean {
  if (left === undefined || right === undefined) return left === right
  return (
    left.inputPerMtok === right.inputPerMtok &&
    left.outputPerMtok === right.outputPerMtok &&
    left.cacheCreationPerMtok === right.cacheCreationPerMtok &&
    left.cacheCreation1hPerMtok === right.cacheCreation1hPerMtok &&
    left.cacheReadPerMtok === right.cacheReadPerMtok
  )
}

function rateCardFromCatalogModel(
  model: ModelDefinition,
  staticPricing: PricingEntry | undefined,
  preserveStaticSchedule: boolean,
): PricingEntry | null {
  if (!model.pricing) return null

  const catalogPricing = model.pricing
  const preservesStaticSchedule = preserveStaticSchedule && Boolean(staticPricing?.historicalRates)

  const input = preservesStaticSchedule ? staticPricing!.input : catalogPricing.inputPerMtok
  const output = preservesStaticSchedule ? staticPricing!.output : catalogPricing.outputPerMtok
  const cacheCreation = preservesStaticSchedule
    ? staticPricing!.cacheCreation
    : (catalogPricing.cacheCreationPerMtok ??
      deriveInputRelatedRate(input, staticPricing, 'cacheCreation'))
  const cacheCreation1h = preservesStaticSchedule
    ? cacheCreation1hRate(staticPricing!)
    : (catalogPricing.cacheCreation1hPerMtok ??
      deriveInputRelatedRate(input, staticPricing, 'cacheCreation1h'))
  const cacheRead = preservesStaticSchedule
    ? staticPricing!.cacheRead
    : (catalogPricing.cacheReadPerMtok ?? deriveInputRelatedRate(input, staticPricing, 'cacheRead'))
  const pricing: PricingEntry = {
    input,
    output,
    cacheCreation,
    cacheCreation1h,
    cacheRead,
  }

  if (preservesStaticSchedule) pricing.historicalRates = staticPricing!.historicalRates

  // Catalog-declared multipliers win; fall back to the static table's (same
  // pattern as the cache rates above) so a pricing patch that only overrides
  // the per-Mtok rates keeps billing speed tiers correctly.
  const speedMultipliers = catalogPricing.speedMultipliers ?? staticPricing?.speedMultipliers
  if (speedMultipliers) pricing.speedMultipliers = speedMultipliers

  if (model.longContextPriceCliff) {
    pricing.longContext = {
      thresholdTokens: model.longContextPriceCliff.thresholdTokens,
      input: input * model.longContextPriceCliff.inputMultiplier,
      output: output * model.longContextPriceCliff.outputMultiplier,
      cacheCreation: cacheCreation * model.longContextPriceCliff.inputMultiplier,
      cacheCreation1h: cacheCreation1h * model.longContextPriceCliff.inputMultiplier,
      cacheRead: cacheRead * model.longContextPriceCliff.inputMultiplier,
    }
  } else if (staticPricing?.longContext) {
    pricing.longContext = preservesStaticSchedule
      ? staticPricing.longContext
      : rebaseContextRateCard(staticPricing.longContext, staticPricing, pricing)
  }

  if (staticPricing?.marginalLongContext) {
    pricing.marginalLongContext = preservesStaticSchedule
      ? staticPricing.marginalLongContext
      : rebaseContextRateCard(staticPricing.marginalLongContext, staticPricing, pricing)
  }

  return pricing
}

/**
 * A provider's effective catalog flattened to a per-id rate card. Built ONCE per
 * usage load (see loadDailyUsageData) so the hot per-line cost path is a Map
 * lookup instead of a full catalog rebuild + zod re-validation each line.
 *
 * A `null` value means the model is in the catalog but has no pricing (cost 0);
 * a missing key means "not in catalog" → fall back to the static pricing table.
 */
type CatalogPricingMap = Map<string, PricingEntry | null>

const MODEL_SNAPSHOT_SUFFIX = /(?:-|@)(?:\d{8}|\d{4}-\d{2}-\d{2})$/
const BEDROCK_VERSION_SUFFIX = /-v\d+(?::\d+)?$/

/** Provider aliases whose billed canonical model is documented and stable. */
const MODEL_PRICING_ALIASES: Record<string, string> = {
  // OpenAI documents gpt-5.6 as the alias for the Sol tier.
  'gpt-5.6': 'gpt-5.6-sol',
  // xAI documents both aliases as pointers to Grok 4.5.
  'grok-4.5-latest': 'grok-4.5',
  'grok-build-latest': 'grok-4.5',
}

/**
 * Return every plausible pricing key for a runtime-reported model id.
 *
 * Provider proxies can report the concrete upstream deployment rather than the
 * configured catalog id, for example:
 *   anthropic/claude-sonnet-5-20260630 -> claude-sonnet-5
 *   anthropic/claude-4.6-opus-20260205 -> claude-opus-4-6
 *   openai/gpt-5.5-20260423            -> openai/gpt-5.5 / gpt-5.5
 *   anthropic/claude-sonnet-4.6         -> claude-sonnet-4-6
 *   claude-haiku-4-5@20251001           -> claude-haiku-4-5
 *
 * Build candidates instead of normalizing destructively so exact custom model
 * ids still win and historical dated ids already present in the static table
 * remain available.
 */
function modelPricingCandidates(model: string): string[] {
  const candidates: string[] = []
  const seen = new Set<string>()
  const queue: string[] = []

  const add = (candidate: string) => {
    if (!candidate || seen.has(candidate)) return
    seen.add(candidate)
    candidates.push(candidate)
    queue.push(candidate)
  }

  add(model)

  while (queue.length > 0) {
    const candidate = queue.shift()!

    add(candidate.replace(MODEL_SNAPSHOT_SUFFIX, ''))
    add(candidate.replace(BEDROCK_VERSION_SUFFIX, ''))
    add(MODEL_PRICING_ALIASES[candidate])

    if (candidate.includes('/')) {
      add(candidate.split('/').pop()!)
    }

    const bedrockMatch = candidate.match(/^(?:[\w-]+\.)?anthropic\.(.+)$/)
    if (bedrockMatch) add(bedrockMatch[1])

    // OpenRouter uses dots for Claude minor versions (for example,
    // anthropic/claude-sonnet-4.6), while Anthropic's rate-card ids use
    // hyphens. Limit this rewrite to Claude so GPT/Grok decimal versions stay
    // intact.
    if (candidate.startsWith('claude-')) {
      add(candidate.replace(/(\d+)\.(\d+)/g, '$1-$2'))
    }

    // Some proxy responses use Claude's version-family order while our catalog
    // uses family-version. Preserve an optional date so an exact dated static
    // key can still resolve before the undated fallback.
    const claudeVersionFirst = candidate.match(
      /^claude-(\d+(?:[.-]\d+)?)-(haiku|sonnet|opus|fable)(-\d{8})?$/,
    )
    if (claudeVersionFirst) {
      const [, version, family, date = ''] = claudeVersionFirst
      add(`claude-${family}-${version.replace('.', '-')}${date}`)
    }
  }

  return candidates
}

function buildCatalogPricingMap(providerId: LlmProviderId): CatalogPricingMap {
  const map: CatalogPricingMap = new Map()
  const builtinById = new Map(getProviderCatalog(providerId).map((model) => [model.id, model]))
  for (const model of getEffectiveCatalog(providerId)) {
    let staticPricing: PricingEntry | undefined
    for (const candidate of modelPricingCandidates(model.id)) {
      staticPricing = (MODEL_PRICING as Record<string, PricingEntry>)[candidate]
      if (staticPricing) break
    }
    // Built-in display rates are evaluated when their module is imported. Use
    // provenance rather than Date.now() to preserve a static schedule;
    // otherwise a process spanning a cutoff mistakes its frozen built-in card
    // for a user override and keeps the old price until restart.
    const preservesStaticSchedule = sameCatalogTokenRates(
      model.pricing,
      builtinById.get(model.id)?.pricing,
    )
    map.set(
      model.id,
      rateCardFromCatalogModel(model, staticPricing, preservesStaticSchedule),
    )
  }
  return map
}

/**
 * Resolve a model's rate card: a provider catalog entry (when supplied) wins
 * over the static pricing table; an in-catalog model with no pricing resolves to
 * `null` (cost 0). Returns null when nothing prices the model.
 */
function resolveRateCard(
  model: string,
  catalogPricing: CatalogPricingMap | undefined,
): PricingEntry | null {
  const candidates = modelPricingCandidates(model)

  // Catalog pricing (including user overrides) wins over every static alias.
  // An exact or canonical catalog entry with intentionally absent pricing must
  // remain free instead of falling through to an unrelated static fallback.
  if (catalogPricing) {
    for (const candidate of candidates) {
      if (catalogPricing.has(candidate)) return catalogPricing.get(candidate) ?? null
    }
  }

  for (const candidate of candidates) {
    const pricing = (MODEL_PRICING as Record<string, PricingEntry>)[candidate]
    if (pricing) return pricing
  }

  return null
}

/** Token counts → cost for an already-resolved rate card (null ⇒ 0). */
function costFromRateCard(
  pricing: PricingEntry | null,
  inputTokens: number,
  outputTokens: number,
  cacheCreation5mTokens: number,
  cacheCreation1hTokens: number,
  cacheReadTokens: number,
  speed?: keyof SpeedMultipliers,
  timestampMs?: number,
): number {
  if (!pricing) return 0

  const baseRates = ratesForTimestamp(pricing, timestampMs)
  const contextTokens =
    inputTokens + cacheCreation5mTokens + cacheCreation1hTokens + cacheReadTokens

  let tokenCost: number
  if (pricing.longContext && contextTokens > pricing.longContext.thresholdTokens) {
    // Whole-request cliffs reprice every category once the full prompt — fresh
    // input, both cache-write TTLs, and cache reads — crosses the threshold.
    const rates = pricing.longContext
    tokenCost =
      inputTokens * rates.input +
      outputTokens * rates.output +
      cacheCreation5mTokens * rates.cacheCreation +
      cacheCreation1hTokens * cacheCreation1hRate(rates) +
      cacheReadTokens * rates.cacheRead
  } else if (pricing.marginalLongContext) {
    const rates = pricing.marginalLongContext
    const marginalCost = (tokens: number, baseRate: number, marginalRate: number): number =>
      Math.min(tokens, rates.thresholdTokens) * baseRate +
      Math.max(0, tokens - rates.thresholdTokens) * marginalRate

    tokenCost =
      marginalCost(inputTokens, baseRates.input, rates.input) +
      marginalCost(outputTokens, baseRates.output, rates.output) +
      marginalCost(cacheCreation5mTokens, baseRates.cacheCreation, rates.cacheCreation) +
      marginalCost(
        cacheCreation1hTokens,
        cacheCreation1hRate(baseRates),
        cacheCreation1hRate(rates),
      ) +
      marginalCost(cacheReadTokens, baseRates.cacheRead, rates.cacheRead)
  } else {
    tokenCost =
      inputTokens * baseRates.input +
      outputTokens * baseRates.output +
      cacheCreation5mTokens * baseRates.cacheCreation +
      cacheCreation1hTokens * cacheCreation1hRate(baseRates) +
      cacheReadTokens * baseRates.cacheRead
  }

  // Served-tier multiplier scales every token rate ON TOP of the base-vs-cliff
  // selection above — same composition as the platform's computeCost. A tier
  // with no configured multiplier bills standard (1x).
  const multiplier = (speed !== undefined ? pricing.speedMultipliers?.[speed] : undefined) ?? 1

  return (multiplier * tokenCost) / 1_000_000
}

/**
 * Calculate cost from token counts.
 *
 * When `providerId` is supplied, pricing comes first from that provider's
 * effective catalog so user patches and custom models are honored. Legacy
 * static pricing remains as a fallback for transcript ids outside the catalog.
 * Returns 0 for unknown models.
 * `timestampMs` selects an effective-dated rate and defaults to the current
 * instant; transcript loads always pass each row's own timestamp.
 *
 * Passing `providerId` rebuilds the provider catalog, so this is for one-off
 * call sites. The hot per-line path in loadDailyUsageData builds the map once
 * and calls resolveRateCard/costFromRateCard directly.
 */
export function calculateCost(
  model: string,
  inputTokens: number,
  outputTokens: number,
  cacheCreationTokens: number,
  cacheReadTokens: number,
  providerId?: LlmProviderId,
  timestampMs: number = Date.now(),
): number {
  const catalogPricing = providerId ? buildCatalogPricingMap(providerId) : undefined
  return costFromRateCard(
    resolveRateCard(model, catalogPricing),
    inputTokens,
    outputTokens,
    cacheCreationTokens,
    0,
    cacheReadTokens,
    undefined,
    timestampMs,
  )
}

async function findJsonlFiles(dir: string): Promise<string[]> {
  const results: string[] = []
  const entries = await fs.promises.readdir(dir, { withFileTypes: true })
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      results.push(...(await findJsonlFiles(fullPath)))
    } else if (entry.name.endsWith('.jsonl')) {
      results.push(fullPath)
    }
  }
  return results
}

function isMissingPathError(error: unknown): boolean {
  return error instanceof Error && 'code' in error && error.code === 'ENOENT'
}

const NEWLINE_BYTE = 0x0a
const OPEN_BRACE_BYTE = 0x7b
const CLOSE_BRACE_BYTE = 0x7d
// Every `"…_tokens"` key processLine screens for ends in this sequence, so a
// line without it can be skipped without decoding.
const USAGE_MARKER = Buffer.from('_tokens"')

function isAsciiWhitespaceByte(byte: number): boolean {
  return byte === 0x20 || (byte >= 0x09 && byte <= 0x0d)
}

/**
 * Lightweight replacement for ccusage's loadDailyUsageData.
 * - Pre-filters files by mtime when `since` is set
 * - Limits concurrent file reads via pLimit
 * - Deduplicates streamed/replayed entries by message and request identity,
 *   retaining the richest total-token snapshot and preferring speed metadata
 * - Uses costUSD field when available
 */
export async function loadDailyUsageData(
  options: LoadOptions | SessionLoadOptions,
): Promise<DailyUsageData[]> {
  const { since, concurrency = 10, providerId, loadStatus } = options
  const markIncomplete = () => {
    if (loadStatus) loadStatus.incomplete = true
  }

  let files: string[]
  if ('sessionPath' in options) {
    // A session's primary transcript is <id>.jsonl. Current subagent/workflow
    // transcripts live below the adjacent <id>/ directory, so include those in
    // the session total without walking every other session for the agent.
    // Legacy Claude Code versions wrote unlinked agent-*.jsonl siblings; those
    // cannot be attributed safely, so exclude them and flag the result below.
    files = []
    let hasPrimaryTranscript = false
    try {
      const stat = await fs.promises.stat(options.sessionPath)
      if (stat.isFile()) {
        files.push(options.sessionPath)
        hasPrimaryTranscript = true
      }
      else markIncomplete()
    } catch (error) {
      // A newly-created session can exist before its transcript is written.
      if (!isMissingPathError(error)) markIncomplete()
    }

    const relatedDir = options.sessionPath.replace(/\.jsonl$/, '')
    try {
      files.push(...(await findJsonlFiles(relatedDir)))
    } catch (error) {
      // Most sessions have no nested transcripts.
      if (!isMissingPathError(error)) markIncomplete()
    }

    if (hasPrimaryTranscript) {
      try {
        const siblingEntries = await fs.promises.readdir(path.dirname(options.sessionPath), {
          withFileTypes: true,
        })
        const primaryFilename = path.basename(options.sessionPath)
        if (
          siblingEntries.some(
            (entry) =>
              entry.name !== primaryFilename &&
              entry.isFile() &&
              entry.name.startsWith('agent-') &&
              entry.name.endsWith('.jsonl'),
          )
        ) {
          markIncomplete()
        }
      } catch (error) {
        // Other failures mean we cannot rule out omitted data.
        if (!isMissingPathError(error)) markIncomplete()
      }
    }
  } else {
    const projectsDir = path.join(options.claudePath, 'projects')
    try {
      await fs.promises.access(projectsDir)
      files = await findJsonlFiles(projectsDir)
    } catch (error) {
      if (!isMissingPathError(error)) markIncomplete()
      return []
    }
  }

  if (files.length === 0) return []

  // Parse the since date for filtering
  let sinceDate: Date | null = null
  if (since) {
    // since format: "YYYYMMDD"
    const y = parseInt(since.substring(0, 4), 10)
    const m = parseInt(since.substring(4, 6), 10) - 1
    const d = parseInt(since.substring(6, 8), 10)
    sinceDate = new Date(y, m, d)
  }

  // Pre-filter files by mtime when since is set
  if (sinceDate) {
    const sinceMs = sinceDate.getTime()
    const limit = pLimit(concurrency)
    const statResults = await Promise.all(
      files.map((file) =>
        limit(async () => {
          try {
            const stat = await fs.promises.stat(file)
            return stat.mtimeMs >= sinceMs ? file : null
          } catch {
            markIncomplete()
            return null
          }
        })
      )
    )
    files = statResults.filter((f): f is string => f !== null)
  }

  if (files.length === 0) return []

  // Resolve the provider catalog pricing once, then cache the final rate card
  // per runtime model id. A load generally has many usage rows but only a
  // handful of distinct models, so candidate normalization stays off the hot
  // per-line path after the first occurrence.
  const catalogPricing = providerId ? buildCatalogPricingMap(providerId) : undefined
  const rateCardByModel = new Map<string, PricingEntry | null>()
  const resolveRateCardForLoad = (model: string): PricingEntry | null => {
    const cached = rateCardByModel.get(model)
    if (cached !== undefined) return cached
    const rateCard = resolveRateCard(model, catalogPricing)
    rateCardByModel.set(model, rateCard)
    return rateCard
  }

  // Stream-read files with concurrency limit.
  // Pre-filter lines with a cheap string check before JSON.parse — most lines
  // in session JSONL files are user/assistant messages without usage data.
  const limit = pLimit(concurrency)
  // One provider message id can legitimately appear under multiple request ids.
  // Keep a tiny bucket per logical message so normal distinct requests survive,
  // while request-less snapshots and sidechain replays can still be reconciled.
  const countedByKey: CountedUsageBuckets = new Map()
  const unkeyedUsages: CountedUsage[] = []
  const dateMap = new Map<
    string,
    {
      inputTokens: number
      outputTokens: number
      cacheCreationTokens: number
      cacheReadTokens: number
      totalCost: number
      priceMissing: boolean
      models: Map<
        string,
        {
          inputTokens: number
          outputTokens: number
          cacheCreationTokens: number
          cacheReadTokens: number
          cost: number
        }
      >
    }
  >()

  await Promise.all(
    files.map((file) =>
      limit(async () => {
        let fh: fs.promises.FileHandle | null = null
        try {
          fh = await fs.promises.open(file, 'r')
          const stream = fh.createReadStream()
          // Split on newlines in the raw bytes and decode only the lines that
          // could carry usage. Transcripts are dominated by large tool-result
          // rows; decoding every byte to a JS string costs multiples of the
          // actual work and is the bulk of the wall-clock on big sessions.
          let pending: Buffer[] = []

          for await (const chunk of stream) {
            let start = 0
            let idx = chunk.indexOf(NEWLINE_BYTE)
            while (idx !== -1) {
              let line: Buffer
              if (pending.length > 0) {
                pending.push(chunk.subarray(start, idx))
                line = Buffer.concat(pending)
                pending = []
              } else {
                line = chunk.subarray(start, idx)
              }
              processLineBytes(line, countedByKey, unkeyedUsages, sinceDate)
              start = idx + 1
              idx = chunk.indexOf(NEWLINE_BYTE, start)
            }
            // Keep the trailing (potentially incomplete) line for the next chunk
            if (start < chunk.length) pending.push(chunk.subarray(start))
          }
          // Process any remaining content
          if (pending.length > 0) {
            processLineBytes(Buffer.concat(pending), countedByKey, unkeyedUsages, sinceDate)
          }
        } catch {
          // Skip unreadable files
          markIncomplete()
        } finally {
          await fh?.close()
        }
      })
    )
  )

  /**
   * Byte-level gate in front of {@link processLine}: a line is decoded only
   * when it survives the same emptiness/shape/token checks the string path
   * applies, so behaviour is unchanged and non-usage rows are never decoded.
   */
  function processLineBytes(
    line: Buffer,
    countedEntries: CountedUsageBuckets,
    unkeyedEntries: CountedUsage[],
    sinceDateFilter: Date | null,
  ) {
    // Only ASCII whitespace is trimmed here; every such byte is < 0x80, so this
    // can never slice a multi-byte UTF-8 sequence.
    let start = 0
    let end = line.length
    while (start < end && isAsciiWhitespaceByte(line[start])) start++
    while (end > start && isAsciiWhitespaceByte(line[end - 1])) end--
    if (start === end) return

    // Malformed rows are rare and must go through the string path so the
    // incomplete-load reporting stays identical.
    if (line[start] !== OPEN_BRACE_BYTE || line[end - 1] !== CLOSE_BRACE_BYTE) {
      processLine(line.toString('utf-8'), countedEntries, unkeyedEntries, sinceDateFilter)
      return
    }

    // Superset of every `"…_tokens"` key processLine looks for.
    if (!line.includes(USAGE_MARKER, start)) return

    processLine(line.toString('utf-8'), countedEntries, unkeyedEntries, sinceDateFilter)
  }

  function processLine(
    line: string,
    countedEntries: CountedUsageBuckets,
    unkeyedEntries: CountedUsage[],
    sinceDateFilter: Date | null,
  ) {
    const trimmed = line.trim()
    if (!trimmed) return

    // JSONL entries are objects. Catch visibly truncated/corrupted rows without
    // paying JSON.parse cost for every valid non-usage event in large logs.
    if (!trimmed.startsWith('{') || !trimmed.endsWith('}')) {
      markIncomplete()
      return
    }

    // Cheap pre-filter: skip lines that can't contain token usage data.
    if (
      !line.includes('"input_tokens"') &&
      !line.includes('"output_tokens"') &&
      !line.includes('"cache_creation_input_tokens"') &&
      !line.includes('"cache_read_input_tokens"') &&
      !line.includes('"ephemeral_5m_input_tokens"') &&
      !line.includes('"ephemeral_1h_input_tokens"')
    ) {
      return
    }

    let entry: UsageEntry
    try {
      entry = JSON.parse(line)
    } catch {
      markIncomplete()
      return
    }

    const usage = entry.message?.usage
    if (!usage) return
    if (!entry.timestamp) return

    // Use local timezone for date grouping (matches ccusage behavior)
    const ts = new Date(entry.timestamp)
    if (Number.isNaN(ts.getTime())) {
      markIncomplete()
      return
    }
    // Filter by date if since is set
    if (sinceDateFilter && ts < sinceDateFilter) return

    const date = `${ts.getFullYear()}-${String(ts.getMonth() + 1).padStart(2, '0')}-${String(ts.getDate()).padStart(2, '0')}`
    const timestampMs = ts.getTime()
    if (
      (entry.requestId !== undefined &&
        (typeof entry.requestId !== 'string' || entry.requestId.length === 0)) ||
      (entry.message?.id !== undefined &&
        (typeof entry.message.id !== 'string' || entry.message.id.length === 0)) ||
      (entry.message?.model !== undefined &&
        (typeof entry.message.model !== 'string' || entry.message.model.length === 0))
    ) {
      markIncomplete()
      return
    }
    const requestId = entry.requestId
    const isSidechain = entry.isSidechain === true
    const msgId = entry.message?.id

    const mainUsage = parseTokenUsage(usage)
    if (mainUsage && hasAnyTokens(mainUsage)) {
      const model =
        typeof entry.message?.model === 'string' && entry.message.model.length > 0
          ? entry.message.model
          : 'unknown'
      const countedUsage = priceUsage({
        date,
        timestampMs,
        model,
        usage: mainUsage,
        requestId,
        isSidechain,
        recordedCost: entry.costUSD,
      })
      retainUsage(
        msgId ? `message:${msgId}` : undefined,
        countedUsage,
        countedEntries,
        unkeyedEntries,
      )
    }

    // Advisor calls are separately billed model invocations embedded in the
    // main response's iteration list. Ordinary `type: "message"` iterations
    // are already represented by the top-level aggregate and must not be added.
    if (usage.iterations !== undefined && usage.iterations !== null) {
      if (!Array.isArray(usage.iterations)) {
        markIncomplete()
        return
      }

      let advisorOrdinal = 0
      for (const iteration of usage.iterations) {
        if (!iteration || typeof iteration !== 'object') {
          markIncomplete()
          continue
        }
        if (iteration.type !== 'advisor_message') continue

        const advisorUsage = parseTokenUsage(iteration)
        const ordinal = advisorOrdinal++
        if (!advisorUsage || !hasAnyTokens(advisorUsage)) continue

        const model =
          typeof iteration.model === 'string' && iteration.model.length > 0
            ? iteration.model
            : typeof entry.advisorModel === 'string' && entry.advisorModel.length > 0
              ? entry.advisorModel
              : 'unknown'
        const countedUsage = priceUsage({
          date,
          timestampMs,
          model,
          usage: advisorUsage,
          requestId,
          isSidechain,
          // The parent costUSD covers only the main model call. Advisor usage
          // always needs its own local calculation.
        })
        retainUsage(
          msgId ? `advisor:${msgId}:${ordinal}` : undefined,
          countedUsage,
          countedEntries,
          unkeyedEntries,
        )
      }
    }
  }

  /** Validate and normalize one top-level or advisor usage object. */
  function parseTokenUsage(usage: TokenUsage): ParsedTokenUsage | null {
    const nested = usage.cache_creation
    if (
      nested !== undefined &&
      nested !== null &&
      (typeof nested !== 'object' || Array.isArray(nested))
    ) {
      markIncomplete()
      return null
    }

    const tokenValues = [
      usage.input_tokens,
      usage.output_tokens,
      usage.cache_creation_input_tokens,
      usage.cache_read_input_tokens,
      nested?.ephemeral_5m_input_tokens,
      nested?.ephemeral_1h_input_tokens,
    ]
    if (
      tokenValues.some(
        (value) => value !== undefined && (!Number.isSafeInteger(value) || value < 0),
      )
    ) {
      markIncomplete()
      return null
    }

    // The duration breakdown, when present, is the provider's authoritative
    // accounting. The flat field remains the compatibility fallback for older
    // transcripts that predate cache TTL reporting.
    const hasNestedCacheCreation = nested !== undefined && nested !== null
    const cacheCreation5mTokens = hasNestedCacheCreation
      ? (nested.ephemeral_5m_input_tokens ?? 0)
      : (usage.cache_creation_input_tokens ?? 0)
    const cacheCreation1hTokens = hasNestedCacheCreation
      ? (nested.ephemeral_1h_input_tokens ?? 0)
      : 0
    const hasSpeedMetadata =
      typeof usage.speed === 'string' && usage.speed.length > 0

    return {
      inputTokens: usage.input_tokens ?? 0,
      outputTokens: usage.output_tokens ?? 0,
      cacheCreation5mTokens,
      cacheCreation1hTokens,
      cacheReadTokens: usage.cache_read_input_tokens ?? 0,
      speed: usage.speed === 'slow' || usage.speed === 'fast' ? usage.speed : undefined,
      hasSpeedMetadata,
    }
  }

  function hasAnyTokens(usage: ParsedTokenUsage): boolean {
    return (
      usage.inputTokens !== 0 ||
      usage.outputTokens !== 0 ||
      usage.cacheCreation5mTokens !== 0 ||
      usage.cacheCreation1hTokens !== 0 ||
      usage.cacheReadTokens !== 0
    )
  }

  function priceUsage(options: {
    date: string
    timestampMs: number
    model: string
    usage: ParsedTokenUsage
    requestId?: string
    isSidechain: boolean
    recordedCost?: number
  }): CountedUsage {
    const { date, timestampMs, model, usage, requestId, isSidechain, recordedCost } = options
    const rateCard = resolveRateCardForLoad(model)
    const speedMultiplier =
      usage.speed !== undefined ? rateCard?.speedMultipliers?.[usage.speed] : undefined
    const computedCost = costFromRateCard(
      rateCard,
      usage.inputTokens,
      usage.outputTokens,
      usage.cacheCreation5mTokens,
      usage.cacheCreation1hTokens,
      usage.cacheReadTokens,
      usage.speed,
      timestampMs,
    )
    const hasRecordedCost = typeof recordedCost === 'number' && Number.isFinite(recordedCost)
    // A main-row costUSD is authoritative except when a known speed multiplier
    // makes the transcript estimate tier-blind. Advisor calls pass no recorded
    // cost and therefore always use their own model's rate card.
    const cost =
      speedMultiplier !== undefined
        ? computedCost
        : hasRecordedCost
          ? recordedCost
          : computedCost

    return {
      date,
      model,
      inputTokens: usage.inputTokens,
      outputTokens: usage.outputTokens,
      cacheCreationTokens:
        usage.cacheCreation5mTokens + usage.cacheCreation1hTokens,
      cacheReadTokens: usage.cacheReadTokens,
      cost,
      // A numeric recorded cost (including an intentional zero) is authoritative.
      // Otherwise a null rate card means the total is incomplete, not free.
      priceMissing: !hasRecordedCost && rateCard === null,
      requestId,
      isSidechain,
      hasSpeedMetadata: usage.hasSpeedMetadata,
    }
  }

  function retainUsage(
    messageKey: string | undefined,
    candidate: CountedUsage,
    countedEntries: CountedUsageBuckets,
    unkeyedEntries: CountedUsage[],
  ) {
    if (!messageKey) {
      unkeyedEntries.push(candidate)
      return
    }

    let bucket = countedEntries.get(messageKey)
    if (!bucket) {
      bucket = []
      countedEntries.set(messageKey, bucket)
    }

    // Exact request ids identify ordinary streamed snapshots. Request-less
    // snapshots reconcile after every file has been read, when all concrete
    // request ids are available and the association can be order-independent.
    // Sidechain rows reconcile cross-request immediately so a replay of a
    // parent response cannot be billed as a fresh model invocation.
    let existingIndex = bucket.findIndex((entry) => entry.requestId === candidate.requestId)
    if (existingIndex === -1) {
      existingIndex = bucket.findIndex((entry) => candidate.isSidechain || entry.isSidechain)
    }

    if (existingIndex === -1) {
      bucket.push(candidate)
      return
    }

    if (shouldReplaceUsage(candidate, bucket[existingIndex])) {
      bucket[existingIndex] = candidate
    }
  }

  function shouldReplaceUsage(candidate: CountedUsage, previous: CountedUsage): boolean {
    // A sidechain replay can contain an enormous cached parent prompt. The real
    // non-sidechain parent wins regardless of which snapshot has more tokens.
    if (candidate.isSidechain !== previous.isSidechain) return !candidate.isSidechain

    const candidateTokens = totalTokensForDedupe(candidate)
    const previousTokens = totalTokensForDedupe(previous)
    if (candidateTokens !== previousTokens) return candidateTokens > previousTokens

    // Match CCUsage's final richness tie-breaks: cost first, then the presence
    // of speed metadata when every token bucket and cost are equal.
    if (candidate.cost !== previous.cost) return candidate.cost > previous.cost

    if (candidate.hasSpeedMetadata !== previous.hasSpeedMetadata) {
      return candidate.hasSpeedMetadata
    }
    return false
  }

  function totalTokensForDedupe(usage: CountedUsage): number {
    return (
      usage.inputTokens +
      usage.outputTokens +
      usage.cacheCreationTokens +
      usage.cacheReadTokens
    )
  }

  function sameFallbackSnapshot(left: CountedUsage, right: CountedUsage): boolean {
    return (
      left.date === right.date &&
      left.model === right.model &&
      left.inputTokens === right.inputTokens &&
      left.outputTokens === right.outputTokens &&
      left.cacheCreationTokens === right.cacheCreationTokens &&
      left.cacheReadTokens === right.cacheReadTokens &&
      left.isSidechain === right.isSidechain
    )
  }

  function reconcileRequestlessUsage(bucket: CountedUsage[]): CountedUsage[] {
    const requestless = bucket.find((usage) => usage.requestId === undefined)
    const concrete = bucket.filter((usage) => usage.requestId !== undefined)
    if (!requestless || concrete.length === 0) return bucket

    // In translated streams the same snapshot can appear once with requestId
    // and once without it. Prefer an exact-equivalent partner; if the snapshots
    // differ (for example partial vs final), use a stable request-id fallback.
    // This preserves other distinct requests and makes file/read order irrelevant.
    concrete.sort((left, right) =>
      left.requestId! < right.requestId! ? -1 : left.requestId! > right.requestId! ? 1 : 0,
    )
    const targetIndex = concrete.findIndex((usage) => sameFallbackSnapshot(usage, requestless))
    const resolvedIndex = targetIndex === -1 ? 0 : targetIndex
    const target = concrete[resolvedIndex]
    const retained = shouldReplaceUsage(requestless, target) ? requestless : target
    retained.requestId = target.requestId
    concrete[resolvedIndex] = retained
    return concrete
  }

  function addUsage(map: typeof dateMap, usage: CountedUsage) {
    const {
      date,
      model,
      inputTokens,
      outputTokens,
      cacheCreationTokens,
      cacheReadTokens,
      cost,
      priceMissing,
    } = usage
    let day = map.get(date)
    if (!day) {
      day = {
        inputTokens: 0,
        outputTokens: 0,
        cacheCreationTokens: 0,
        cacheReadTokens: 0,
        totalCost: 0,
        priceMissing: false,
        models: new Map(),
      }
      map.set(date, day)
    }

    day.inputTokens += inputTokens
    day.outputTokens += outputTokens
    day.cacheCreationTokens += cacheCreationTokens
    day.cacheReadTokens += cacheReadTokens
    day.totalCost += cost
    day.priceMissing ||= priceMissing

    let modelData = day.models.get(model)
    if (!modelData) {
      modelData = {
        inputTokens: 0,
        outputTokens: 0,
        cacheCreationTokens: 0,
        cacheReadTokens: 0,
        cost: 0,
      }
      day.models.set(model, modelData)
    }

    modelData.inputTokens += inputTokens
    modelData.outputTokens += outputTokens
    modelData.cacheCreationTokens += cacheCreationTokens
    modelData.cacheReadTokens += cacheReadTokens
    modelData.cost += cost
  }

  for (const usage of unkeyedUsages) {
    addUsage(dateMap, usage)
  }
  for (const bucket of countedByKey.values()) {
    for (const usage of reconcileRequestlessUsage(bucket)) addUsage(dateMap, usage)
  }

  // Convert to output format
  const results: DailyUsageData[] = []
  for (const [date, day] of dateMap) {
    // Round cost values to 10 decimal places (sub-nanocent precision) at the
    // output boundary. Cost is summed by `+=` across files read concurrently;
    // floating-point addition is non-associative, so completion-order jitter
    // produces 1-ULP differences (10⁻¹⁵ scale) that break idempotence tests
    // and make displayed values jitter run-to-run. Rounding here is well below
    // any visible precision and makes the function deterministic.
    const round = (n: number) => Math.round(n * 1e10) / 1e10
    const modelBreakdowns: ModelBreakdown[] = []
    for (const [modelName, data] of day.models) {
      modelBreakdowns.push({ modelName, ...data, cost: round(data.cost) })
    }

    results.push({
      date,
      inputTokens: day.inputTokens,
      outputTokens: day.outputTokens,
      cacheCreationTokens: day.cacheCreationTokens,
      cacheReadTokens: day.cacheReadTokens,
      totalCost: round(day.totalCost),
      priceMissing: day.priceMissing,
      modelBreakdowns,
    })
  }

  // Sort by date descending (newest first, matching ccusage)
  results.sort((a, b) => b.date.localeCompare(a.date))
  return results
}

/**
 * Calculate all-time usage for one session on demand.
 *
 * This intentionally performs no caching: callers use it for ad-hoc views and
 * should receive a fresh total when a session is still accumulating messages.
 */
export async function loadSessionUsageTotals(options: {
  sessionPath: string
  providerId?: LlmProviderId
}): Promise<SessionUsageTotals> {
  const loadStatus: UsageLoadStatus = { incomplete: false }
  const daily = await loadDailyUsageData({ ...options, loadStatus })

  const totals = daily.reduce<SessionUsageTotals>(
    (sum, day) => ({
      totalCost: sum.totalCost + day.totalCost,
      totalTokens:
        sum.totalTokens +
        day.inputTokens +
        day.outputTokens +
        day.cacheCreationTokens +
        day.cacheReadTokens,
      priceMissing: sum.priceMissing || day.priceMissing,
      usageIncomplete: sum.usageIncomplete,
    }),
    { totalCost: 0, totalTokens: 0, priceMissing: false, usageIncomplete: false },
  )

  return {
    ...totals,
    totalCost: Math.round(totals.totalCost * 1e10) / 1e10,
    usageIncomplete: loadStatus.incomplete,
  }
}
