import * as fs from 'fs'
import * as path from 'path'
import pLimit from 'p-limit'
import { getEffectiveCatalog, type LlmProviderId, type ModelDefinition } from '../llm-provider'
import type { SessionUsageTotals } from '../types/usage'

export interface ModelBreakdown {
  modelName: string
  inputTokens: number
  outputTokens: number
  cacheCreationTokens: number
  cacheReadTokens: number
  cost: number
}

export interface DailyUsageData {
  date: string
  inputTokens: number
  outputTokens: number
  cacheCreationTokens: number
  cacheReadTokens: number
  totalCost: number
  priceMissing: boolean
  modelBreakdowns: ModelBreakdown[]
}

interface UsageEntry {
  timestamp: string
  message?: {
    id?: string
    model?: string
    usage?: {
      input_tokens?: number
      output_tokens?: number
      cache_creation_input_tokens?: number
      cache_read_input_tokens?: number
      // Served speed tier echoed into the transcript ('slow'/'fast'; natively
      // by Anthropic fast mode, by the platform proxy for translated OpenAI/xAI
      // usage). Absent ⇒ standard tier.
      speed?: string
    }
  }
  costUSD?: number
}

interface CommonLoadOptions {
  since?: string
  concurrency?: number
  providerId?: LlmProviderId
  loadStatus?: UsageLoadStatus
}

interface UsageLoadStatus {
  incomplete: boolean
}

interface LoadOptions extends CommonLoadOptions {
  claudePath: string
}

interface SessionLoadOptions extends CommonLoadOptions {
  sessionPath: string
}

interface CountedUsage {
  date: string
  model: string
  inputTokens: number
  outputTokens: number
  cacheCreationTokens: number
  cacheReadTokens: number
  cost: number
  priceMissing: boolean
}

// Per-million-token pricing for known Claude models.
// Generated by: npx tsx scripts/fetch-model-pricing.ts
// When costUSD is present in the JSONL entry, it takes precedence over this table.
import MODEL_PRICING from './model-pricing.json'

interface RateCard {
  input: number
  output: number
  cacheCreation: number
  cacheRead: number
}

interface SpeedMultipliers {
  slow?: number
  fast?: number
}

interface PricingEntry extends RateCard {
  // OpenAI GPT-5.x 272K cliff: above `thresholdTokens` of prompt input the whole
  // request reprices at these rates. Mirror of the proxy's pricing table.
  longContext?: RateCard & { thresholdTokens: number }
  // Served-tier billing multipliers (flex/priority/fast mode). Applied on top
  // of whichever rate set (base or longContext) a request lands on; an absent
  // tier bills standard (1x). Mirror of the proxy's pricing table.
  speedMultipliers?: SpeedMultipliers
}

function deriveInputRelatedRate(
  inputRate: number,
  staticPricing: PricingEntry | undefined,
  field: 'cacheCreation' | 'cacheRead',
): number {
  if (!staticPricing || staticPricing.input <= 0) {
    return field === 'cacheRead' ? inputRate * 0.1 : inputRate
  }
  return inputRate * (staticPricing[field] / staticPricing.input)
}

function rateCardFromCatalogModel(
  model: ModelDefinition,
  staticPricing: PricingEntry | undefined,
): PricingEntry | null {
  if (!model.pricing) return null

  const input = model.pricing.inputPerMtok
  const output = model.pricing.outputPerMtok
  const cacheCreation = deriveInputRelatedRate(input, staticPricing, 'cacheCreation')
  const cacheRead = deriveInputRelatedRate(input, staticPricing, 'cacheRead')
  const pricing: PricingEntry = { input, output, cacheCreation, cacheRead }

  // Catalog-declared multipliers win; fall back to the static table's (same
  // pattern as the cache rates above) so a pricing patch that only overrides
  // the per-Mtok rates keeps billing speed tiers correctly.
  const speedMultipliers = model.pricing.speedMultipliers ?? staticPricing?.speedMultipliers
  if (speedMultipliers) pricing.speedMultipliers = speedMultipliers

  if (model.longContextPriceCliff) {
    pricing.longContext = {
      thresholdTokens: model.longContextPriceCliff.thresholdTokens,
      input: input * model.longContextPriceCliff.inputMultiplier,
      output: output * model.longContextPriceCliff.outputMultiplier,
      cacheCreation: cacheCreation * model.longContextPriceCliff.inputMultiplier,
      cacheRead: cacheRead * model.longContextPriceCliff.inputMultiplier,
    }
  }

  return pricing
}

/**
 * A provider's effective catalog flattened to a per-id rate card. Built ONCE per
 * usage load (see loadDailyUsageData) so the hot per-line cost path is a Map
 * lookup instead of a full catalog rebuild + zod re-validation each line.
 *
 * A `null` value means the model is in the catalog but has no pricing (cost 0);
 * a missing key means "not in catalog" → fall back to the static pricing table.
 */
type CatalogPricingMap = Map<string, PricingEntry | null>

const MODEL_SNAPSHOT_SUFFIX = /(?:-|@)(?:\d{8}|\d{4}-\d{2}-\d{2})$/
const BEDROCK_VERSION_SUFFIX = /-v\d+(?::\d+)?$/

/** Provider aliases whose billed canonical model is documented and stable. */
const MODEL_PRICING_ALIASES: Record<string, string> = {
  // OpenAI documents gpt-5.6 as the alias for the Sol tier.
  'gpt-5.6': 'gpt-5.6-sol',
  // xAI documents both aliases as pointers to Grok 4.5.
  'grok-4.5-latest': 'grok-4.5',
  'grok-build-latest': 'grok-4.5',
}

/**
 * Return every plausible pricing key for a runtime-reported model id.
 *
 * Provider proxies can report the concrete upstream deployment rather than the
 * configured catalog id, for example:
 *   anthropic/claude-sonnet-5-20260630 -> claude-sonnet-5
 *   anthropic/claude-4.6-opus-20260205 -> claude-opus-4-6
 *   openai/gpt-5.5-20260423            -> openai/gpt-5.5 / gpt-5.5
 *   anthropic/claude-sonnet-4.6         -> claude-sonnet-4-6
 *   claude-haiku-4-5@20251001           -> claude-haiku-4-5
 *
 * Build candidates instead of normalizing destructively so exact custom model
 * ids still win and historical dated ids already present in the static table
 * remain available.
 */
function modelPricingCandidates(model: string): string[] {
  const candidates: string[] = []
  const seen = new Set<string>()
  const queue: string[] = []

  const add = (candidate: string) => {
    if (!candidate || seen.has(candidate)) return
    seen.add(candidate)
    candidates.push(candidate)
    queue.push(candidate)
  }

  add(model)

  while (queue.length > 0) {
    const candidate = queue.shift()!

    add(candidate.replace(MODEL_SNAPSHOT_SUFFIX, ''))
    add(candidate.replace(BEDROCK_VERSION_SUFFIX, ''))
    add(MODEL_PRICING_ALIASES[candidate])

    if (candidate.includes('/')) {
      add(candidate.split('/').pop()!)
    }

    const bedrockMatch = candidate.match(/^(?:[\w-]+\.)?anthropic\.(.+)$/)
    if (bedrockMatch) add(bedrockMatch[1])

    // OpenRouter uses dots for Claude minor versions (for example,
    // anthropic/claude-sonnet-4.6), while Anthropic's rate-card ids use
    // hyphens. Limit this rewrite to Claude so GPT/Grok decimal versions stay
    // intact.
    if (candidate.startsWith('claude-')) {
      add(candidate.replace(/(\d+)\.(\d+)/g, '$1-$2'))
    }

    // Some proxy responses use Claude's version-family order while our catalog
    // uses family-version. Preserve an optional date so an exact dated static
    // key can still resolve before the undated fallback.
    const claudeVersionFirst = candidate.match(
      /^claude-(\d+(?:[.-]\d+)?)-(haiku|sonnet|opus|fable)(-\d{8})?$/,
    )
    if (claudeVersionFirst) {
      const [, version, family, date = ''] = claudeVersionFirst
      add(`claude-${family}-${version.replace('.', '-')}${date}`)
    }
  }

  return candidates
}

function buildCatalogPricingMap(providerId: LlmProviderId): CatalogPricingMap {
  const map: CatalogPricingMap = new Map()
  for (const model of getEffectiveCatalog(providerId)) {
    const staticPricing = (MODEL_PRICING as Record<string, PricingEntry>)[model.id]
    map.set(model.id, rateCardFromCatalogModel(model, staticPricing))
  }
  return map
}

/**
 * Resolve a model's rate card: a provider catalog entry (when supplied) wins
 * over the static pricing table; an in-catalog model with no pricing resolves to
 * `null` (cost 0). Returns null when nothing prices the model.
 */
function resolveRateCard(
  model: string,
  catalogPricing: CatalogPricingMap | undefined,
): PricingEntry | null {
  const candidates = modelPricingCandidates(model)

  // Catalog pricing (including user overrides) wins over every static alias.
  // An exact or canonical catalog entry with intentionally absent pricing must
  // remain free instead of falling through to an unrelated static fallback.
  if (catalogPricing) {
    for (const candidate of candidates) {
      if (catalogPricing.has(candidate)) return catalogPricing.get(candidate) ?? null
    }
  }

  for (const candidate of candidates) {
    const pricing = (MODEL_PRICING as Record<string, PricingEntry>)[candidate]
    if (pricing) return pricing
  }

  return null
}

/** Token counts → cost for an already-resolved rate card (null ⇒ 0). */
function costFromRateCard(
  pricing: PricingEntry | null,
  inputTokens: number,
  outputTokens: number,
  cacheCreationTokens: number,
  cacheReadTokens: number,
  speed?: keyof SpeedMultipliers,
): number {
  if (!pricing) return 0

  // Cliff triggers on full prompt input (input excludes cache reads in this
  // shape, so add them back) and reprices the whole request once tripped.
  const rates =
    pricing.longContext && inputTokens + cacheReadTokens > pricing.longContext.thresholdTokens
      ? pricing.longContext
      : pricing

  // Served-tier multiplier scales all four rates ON TOP of the base-vs-cliff
  // selection above — same composition as the platform's computeCost. A tier
  // with no configured multiplier bills standard (1x).
  const multiplier = (speed !== undefined ? pricing.speedMultipliers?.[speed] : undefined) ?? 1

  return (
    (multiplier *
      (inputTokens * rates.input +
        outputTokens * rates.output +
        cacheCreationTokens * rates.cacheCreation +
        cacheReadTokens * rates.cacheRead)) /
    1_000_000
  )
}

/**
 * Calculate cost from token counts.
 *
 * When `providerId` is supplied, pricing comes first from that provider's
 * effective catalog so user patches and custom models are honored. Legacy
 * static pricing remains as a fallback for transcript ids outside the catalog.
 * Returns 0 for unknown models.
 *
 * Passing `providerId` rebuilds the provider catalog, so this is for one-off
 * call sites. The hot per-line path in loadDailyUsageData builds the map once
 * and calls resolveRateCard/costFromRateCard directly.
 */
export function calculateCost(
  model: string,
  inputTokens: number,
  outputTokens: number,
  cacheCreationTokens: number,
  cacheReadTokens: number,
  providerId?: LlmProviderId,
): number {
  const catalogPricing = providerId ? buildCatalogPricingMap(providerId) : undefined
  return costFromRateCard(
    resolveRateCard(model, catalogPricing),
    inputTokens,
    outputTokens,
    cacheCreationTokens,
    cacheReadTokens,
  )
}

async function findJsonlFiles(dir: string): Promise<string[]> {
  const results: string[] = []
  const entries = await fs.promises.readdir(dir, { withFileTypes: true })
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      results.push(...(await findJsonlFiles(fullPath)))
    } else if (entry.name.endsWith('.jsonl')) {
      results.push(fullPath)
    }
  }
  return results
}

function isMissingPathError(error: unknown): boolean {
  return error instanceof Error && 'code' in error && error.code === 'ENOENT'
}

/**
 * Lightweight replacement for ccusage's loadDailyUsageData.
 * - Pre-filters files by mtime when `since` is set
 * - Limits concurrent file reads via pLimit
 * - Deduplicates entries by messageId, including rows where requestId is absent,
 *   while keeping the highest output_tokens snapshot
 * - Uses costUSD field when available
 */
export async function loadDailyUsageData(
  options: LoadOptions | SessionLoadOptions,
): Promise<DailyUsageData[]> {
  const { since, concurrency = 10, providerId, loadStatus } = options
  const markIncomplete = () => {
    if (loadStatus) loadStatus.incomplete = true
  }

  let files: string[]
  if ('sessionPath' in options) {
    // A session's primary transcript is <id>.jsonl. Current subagent/workflow
    // transcripts live below the adjacent <id>/ directory, so include those in
    // the session total without walking every other session for the agent.
    // Legacy Claude Code versions wrote unlinked agent-*.jsonl siblings; those
    // cannot be attributed safely, so exclude them and flag the result below.
    files = []
    let hasPrimaryTranscript = false
    try {
      const stat = await fs.promises.stat(options.sessionPath)
      if (stat.isFile()) {
        files.push(options.sessionPath)
        hasPrimaryTranscript = true
      }
      else markIncomplete()
    } catch (error) {
      // A newly-created session can exist before its transcript is written.
      if (!isMissingPathError(error)) markIncomplete()
    }

    const relatedDir = options.sessionPath.replace(/\.jsonl$/, '')
    try {
      files.push(...(await findJsonlFiles(relatedDir)))
    } catch (error) {
      // Most sessions have no nested transcripts.
      if (!isMissingPathError(error)) markIncomplete()
    }

    if (hasPrimaryTranscript) {
      try {
        const siblingEntries = await fs.promises.readdir(path.dirname(options.sessionPath), {
          withFileTypes: true,
        })
        const primaryFilename = path.basename(options.sessionPath)
        if (
          siblingEntries.some(
            (entry) =>
              entry.name !== primaryFilename &&
              entry.isFile() &&
              entry.name.startsWith('agent-') &&
              entry.name.endsWith('.jsonl'),
          )
        ) {
          markIncomplete()
        }
      } catch (error) {
        // Other failures mean we cannot rule out omitted data.
        if (!isMissingPathError(error)) markIncomplete()
      }
    }
  } else {
    const projectsDir = path.join(options.claudePath, 'projects')
    try {
      await fs.promises.access(projectsDir)
      files = await findJsonlFiles(projectsDir)
    } catch (error) {
      if (!isMissingPathError(error)) markIncomplete()
      return []
    }
  }

  if (files.length === 0) return []

  // Parse the since date for filtering
  let sinceDate: Date | null = null
  if (since) {
    // since format: "YYYYMMDD"
    const y = parseInt(since.substring(0, 4), 10)
    const m = parseInt(since.substring(4, 6), 10) - 1
    const d = parseInt(since.substring(6, 8), 10)
    sinceDate = new Date(y, m, d)
  }

  // Pre-filter files by mtime when since is set
  if (sinceDate) {
    const sinceMs = sinceDate.getTime()
    const limit = pLimit(concurrency)
    const statResults = await Promise.all(
      files.map((file) =>
        limit(async () => {
          try {
            const stat = await fs.promises.stat(file)
            return stat.mtimeMs >= sinceMs ? file : null
          } catch {
            markIncomplete()
            return null
          }
        })
      )
    )
    files = statResults.filter((f): f is string => f !== null)
  }

  if (files.length === 0) return []

  // Resolve the provider catalog pricing once, then cache the final rate card
  // per runtime model id. A load generally has many usage rows but only a
  // handful of distinct models, so candidate normalization stays off the hot
  // per-line path after the first occurrence.
  const catalogPricing = providerId ? buildCatalogPricingMap(providerId) : undefined
  const rateCardByModel = new Map<string, PricingEntry | null>()
  const resolveRateCardForLoad = (model: string): PricingEntry | null => {
    const cached = rateCardByModel.get(model)
    if (cached !== undefined) return cached
    const rateCard = resolveRateCard(model, catalogPricing)
    rateCardByModel.set(model, rateCard)
    return rateCard
  }

  // Stream-read files with concurrency limit.
  // Pre-filter lines with a cheap string check before JSON.parse — most lines
  // in session JSONL files are user/assistant messages without usage data.
  const limit = pLimit(concurrency)
  const countedByKey = new Map<string, CountedUsage>()
  const unkeyedUsages: CountedUsage[] = []
  const dateMap = new Map<
    string,
    {
      inputTokens: number
      outputTokens: number
      cacheCreationTokens: number
      cacheReadTokens: number
      totalCost: number
      priceMissing: boolean
      models: Map<
        string,
        {
          inputTokens: number
          outputTokens: number
          cacheCreationTokens: number
          cacheReadTokens: number
          cost: number
        }
      >
    }
  >()

  await Promise.all(
    files.map((file) =>
      limit(async () => {
        let fh: fs.promises.FileHandle | null = null
        try {
          fh = await fs.promises.open(file, 'r')
          const stream = fh.createReadStream({ encoding: 'utf-8' })
          let buffer = ''

          for await (const chunk of stream) {
            buffer += chunk
            const lines = buffer.split('\n')
            // Keep last (potentially incomplete) line in buffer
            buffer = lines.pop() || ''

            for (const line of lines) {
              processLine(line, countedByKey, unkeyedUsages, sinceDate)
            }
          }
          // Process any remaining content
          if (buffer.trim()) {
            processLine(buffer, countedByKey, unkeyedUsages, sinceDate)
          }
        } catch {
          // Skip unreadable files
          markIncomplete()
        } finally {
          await fh?.close()
        }
      })
    )
  )

  function processLine(
    line: string,
    countedEntries: Map<string, CountedUsage>,
    unkeyedEntries: CountedUsage[],
    sinceDateFilter: Date | null,
  ) {
    const trimmed = line.trim()
    if (!trimmed) return

    // JSONL entries are objects. Catch visibly truncated/corrupted rows without
    // paying JSON.parse cost for every valid non-usage event in large logs.
    if (!trimmed.startsWith('{') || !trimmed.endsWith('}')) {
      markIncomplete()
      return
    }

    // Cheap pre-filter: skip lines that can't contain token usage data.
    if (
      !line.includes('"input_tokens"') &&
      !line.includes('"output_tokens"') &&
      !line.includes('"cache_creation_input_tokens"') &&
      !line.includes('"cache_read_input_tokens"')
    ) {
      return
    }

    let entry: UsageEntry
    try {
      entry = JSON.parse(line)
    } catch {
      markIncomplete()
      return
    }

    const usage = entry.message?.usage
    if (!usage) return

    const tokenValues = [
      usage.input_tokens,
      usage.output_tokens,
      usage.cache_creation_input_tokens,
      usage.cache_read_input_tokens,
    ]
    if (
      tokenValues.some(
        (value) => value !== undefined && (typeof value !== 'number' || !Number.isFinite(value)),
      )
    ) {
      markIncomplete()
      return
    }
    if (!tokenValues.some((value) => typeof value === 'number' && value !== 0)) return
    if (!entry.timestamp) return

    // Filter by date if since is set
    if (sinceDateFilter && new Date(entry.timestamp) < sinceDateFilter) return

    // Use local timezone for date grouping (matches ccusage behavior)
    const ts = new Date(entry.timestamp)
    if (Number.isNaN(ts.getTime())) {
      markIncomplete()
      return
    }
    const date = `${ts.getFullYear()}-${String(ts.getMonth() + 1).padStart(2, '0')}-${String(ts.getDate()).padStart(2, '0')}`
    const model = entry.message?.model || 'unknown'

    const inputTokens = usage.input_tokens ?? 0
    const outputTokens = usage.output_tokens ?? 0
    const cacheCreationTokens = usage.cache_creation_input_tokens ?? 0
    const cacheReadTokens = usage.cache_read_input_tokens ?? 0

    // Only the exact tier strings select a multiplier; anything else (absent,
    // unknown future tiers) bills standard.
    const speed = usage.speed === 'slow' || usage.speed === 'fast' ? usage.speed : undefined
    const rateCard = resolveRateCardForLoad(model)
    const speedMultiplier = speed !== undefined ? rateCard?.speedMultipliers?.[speed] : undefined
    const computedCost = costFromRateCard(
      rateCard,
      inputTokens,
      outputTokens,
      cacheCreationTokens,
      cacheReadTokens,
      speed,
    )
    const hasRecordedCost = typeof entry.costUSD === 'number' && Number.isFinite(entry.costUSD)
    // entry.costUSD is the CLI's own estimate and is tier-blind, so a row
    // served on a tier we can price locally must not use it.
    const cost =
      speedMultiplier !== undefined
        ? computedCost
        : hasRecordedCost
          ? entry.costUSD!
          : computedCost

    const countedUsage: CountedUsage = {
      date,
      model,
      inputTokens,
      outputTokens,
      cacheCreationTokens,
      cacheReadTokens,
      cost,
      // A numeric recorded cost (including an intentional zero) is authoritative.
      // Otherwise a null rate card means the total is incomplete, not free.
      priceMissing: !hasRecordedCost && rateCard === null,
    }

    // Transcript snapshots for the same model response share the provider's
    // unique message id while output_tokens increases as content is appended.
    // requestId is not consistently present across translated snapshots, so
    // key solely on message id and keep the highest-output snapshot.
    const msgId = entry.message?.id || ''
    if (msgId) {
      const key = `message:${msgId}`
      const previous = countedEntries.get(key)
      if (previous && outputTokens <= previous.outputTokens) return
      countedEntries.set(key, countedUsage)
      return
    }

    unkeyedEntries.push(countedUsage)
  }

  function addUsage(map: typeof dateMap, usage: CountedUsage) {
    const {
      date,
      model,
      inputTokens,
      outputTokens,
      cacheCreationTokens,
      cacheReadTokens,
      cost,
      priceMissing,
    } = usage
    let day = map.get(date)
    if (!day) {
      day = {
        inputTokens: 0,
        outputTokens: 0,
        cacheCreationTokens: 0,
        cacheReadTokens: 0,
        totalCost: 0,
        priceMissing: false,
        models: new Map(),
      }
      map.set(date, day)
    }

    day.inputTokens += inputTokens
    day.outputTokens += outputTokens
    day.cacheCreationTokens += cacheCreationTokens
    day.cacheReadTokens += cacheReadTokens
    day.totalCost += cost
    day.priceMissing ||= priceMissing

    let modelData = day.models.get(model)
    if (!modelData) {
      modelData = {
        inputTokens: 0,
        outputTokens: 0,
        cacheCreationTokens: 0,
        cacheReadTokens: 0,
        cost: 0,
      }
      day.models.set(model, modelData)
    }

    modelData.inputTokens += inputTokens
    modelData.outputTokens += outputTokens
    modelData.cacheCreationTokens += cacheCreationTokens
    modelData.cacheReadTokens += cacheReadTokens
    modelData.cost += cost
  }

  for (const usage of unkeyedUsages) {
    addUsage(dateMap, usage)
  }
  for (const usage of countedByKey.values()) {
    addUsage(dateMap, usage)
  }

  // Convert to output format
  const results: DailyUsageData[] = []
  for (const [date, day] of dateMap) {
    // Round cost values to 10 decimal places (sub-nanocent precision) at the
    // output boundary. Cost is summed by `+=` across files read concurrently;
    // floating-point addition is non-associative, so completion-order jitter
    // produces 1-ULP differences (10⁻¹⁵ scale) that break idempotence tests
    // and make displayed values jitter run-to-run. Rounding here is well below
    // any visible precision and makes the function deterministic.
    const round = (n: number) => Math.round(n * 1e10) / 1e10
    const modelBreakdowns: ModelBreakdown[] = []
    for (const [modelName, data] of day.models) {
      modelBreakdowns.push({ modelName, ...data, cost: round(data.cost) })
    }

    results.push({
      date,
      inputTokens: day.inputTokens,
      outputTokens: day.outputTokens,
      cacheCreationTokens: day.cacheCreationTokens,
      cacheReadTokens: day.cacheReadTokens,
      totalCost: round(day.totalCost),
      priceMissing: day.priceMissing,
      modelBreakdowns,
    })
  }

  // Sort by date descending (newest first, matching ccusage)
  results.sort((a, b) => b.date.localeCompare(a.date))
  return results
}

/**
 * Calculate all-time usage for one session on demand.
 *
 * This intentionally performs no caching: callers use it for ad-hoc views and
 * should receive a fresh total when a session is still accumulating messages.
 */
export async function loadSessionUsageTotals(options: {
  sessionPath: string
  providerId?: LlmProviderId
}): Promise<SessionUsageTotals> {
  const loadStatus: UsageLoadStatus = { incomplete: false }
  const daily = await loadDailyUsageData({ ...options, loadStatus })

  const totals = daily.reduce<SessionUsageTotals>(
    (sum, day) => ({
      totalCost: sum.totalCost + day.totalCost,
      totalTokens:
        sum.totalTokens +
        day.inputTokens +
        day.outputTokens +
        day.cacheCreationTokens +
        day.cacheReadTokens,
      priceMissing: sum.priceMissing || day.priceMissing,
      usageIncomplete: sum.usageIncomplete,
    }),
    { totalCost: 0, totalTokens: 0, priceMissing: false, usageIncomplete: false },
  )

  return {
    ...totals,
    totalCost: Math.round(totals.totalCost * 1e10) / 1e10,
    usageIncomplete: loadStatus.incomplete,
  }
}
