import { sql } from 'drizzle-orm'
import { sqliteTable, text, integer, uniqueIndex, index, check } from 'drizzle-orm/sqlite-core'
import { CHAT_PROVIDERS } from '@shared/lib/chat-integrations/config-schema'

// =============================================================================
// Better Auth tables (user, session, account, verification)
// These are managed by Better Auth but defined here for type-safe Drizzle queries.
// Schema generated by: npx @better-auth/cli generate (with admin plugin)
// =============================================================================

export const user = sqliteTable('user', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  emailVerified: integer('email_verified', { mode: 'boolean' }).default(false).notNull(),
  image: text('image'),
  createdAt: integer('created_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .$onUpdate(() => new Date())
    .notNull(),
  // Admin plugin fields
  role: text('role'),
  banned: integer('banned', { mode: 'boolean' }).default(false),
  banReason: text('ban_reason'),
  banExpires: integer('ban_expires', { mode: 'timestamp_ms' }),
  mustChangePassword: integer('must_change_password', { mode: 'boolean' }).default(false),
})

export const authSession = sqliteTable('session', {
  id: text('id').primaryKey(),
  expiresAt: integer('expires_at', { mode: 'timestamp_ms' }).notNull(),
  token: text('token').notNull().unique(),
  createdAt: integer('created_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
    .$onUpdate(() => new Date())
    .notNull(),
  ipAddress: text('ip_address'),
  userAgent: text('user_agent'),
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  impersonatedBy: text('impersonated_by'),
}, (table) => ({
  userIdIdx: index('session_userId_idx').on(table.userId),
}))

export const authAccount = sqliteTable('account', {
  id: text('id').primaryKey(),
  accountId: text('account_id').notNull(),
  providerId: text('provider_id').notNull(),
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  accessToken: text('access_token'),
  refreshToken: text('refresh_token'),
  idToken: text('id_token'),
  accessTokenExpiresAt: integer('access_token_expires_at', { mode: 'timestamp_ms' }),
  refreshTokenExpiresAt: integer('refresh_token_expires_at', { mode: 'timestamp_ms' }),
  scope: text('scope'),
  password: text('password'),
  createdAt: integer('created_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
    .$onUpdate(() => new Date())
    .notNull(),
}, (table) => ({
  userIdIdx: index('account_userId_idx').on(table.userId),
}))

export const verification = sqliteTable('verification', {
  id: text('id').primaryKey(),
  identifier: text('identifier').notNull(),
  value: text('value').notNull(),
  expiresAt: integer('expires_at', { mode: 'timestamp_ms' }).notNull(),
  createdAt: integer('created_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .$onUpdate(() => new Date())
    .notNull(),
}, (table) => ({
  identifierIdx: index('verification_identifier_idx').on(table.identifier),
}))

// =============================================================================
// File-Based Refactor: Only connected accounts remain in DB
// Agents, sessions, messages, and secrets are now file-based
// =============================================================================

// Connected accounts - app-level OAuth connections via pluggable providers (Composio, Nango, …)
export const connectedAccounts = sqliteTable('connected_accounts', {
  id: text('id').primaryKey(),
  providerConnectionId: text('provider_connection_id').notNull().unique(),
  providerName: text('provider_name').notNull().default('composio'),
  toolkitSlug: text('toolkit_slug').notNull(), // e.g., 'gmail', 'slack', 'github'
  displayName: text('display_name').notNull(), // User-friendly label
  status: text('status', { enum: ['active', 'revoked', 'expired'] })
    .notNull()
    .default('active'),
  userId: text('user_id').references(() => user.id, { onDelete: 'cascade' }), // Owner in auth mode, null in non-auth mode
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
}, (table) => ({
  userIdIdx: index('connected_accounts_userId_idx').on(table.userId),
}))

// Agent connected accounts - junction table for agent-to-account mappings
// Note: agentSlug references the agent's directory name, not a DB foreign key
export const agentConnectedAccounts = sqliteTable(
  'agent_connected_accounts',
  {
    id: text('id').primaryKey(),
    agentSlug: text('agent_slug').notNull(), // References agent directory name
    connectedAccountId: text('connected_account_id')
      .notNull()
      .references(() => connectedAccounts.id, { onDelete: 'cascade' }),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
  },
  (table) => ({
    agentAccountUnique: uniqueIndex('agent_connected_accounts_unique').on(
      table.agentSlug,
      table.connectedAccountId
    ),
  })
)

// Scheduled tasks - tasks scheduled by agents for future execution
export const scheduledTasks = sqliteTable('scheduled_tasks', {
  id: text('id').primaryKey(),
  agentSlug: text('agent_slug').notNull(),

  // Schedule configuration
  scheduleType: text('schedule_type', { enum: ['at', 'cron'] }).notNull(),
  scheduleExpression: text('schedule_expression').notNull(),

  // Task details
  prompt: text('prompt').notNull(),
  name: text('name'),

  // Status: pending, paused, executed, cancelled, failed
  status: text('status', { enum: ['pending', 'paused', 'executed', 'cancelled', 'failed'] })
    .notNull()
    .default('pending'),

  // Timing
  nextExecutionAt: integer('next_execution_at', { mode: 'timestamp_ms' }).notNull(),
  lastExecutedAt: integer('last_executed_at', { mode: 'timestamp_ms' }),

  // Recurrence
  isRecurring: integer('is_recurring', { mode: 'boolean' }).notNull().default(false),
  executionCount: integer('execution_count').notNull().default(0),

  // Session tracking
  lastSessionId: text('last_session_id'),
  createdBySessionId: text('created_by_session_id'),
  createdByUserId: text('created_by_user_id'), // For ACL purposes in auth mode
  // When set, this task is a session "wake": firing resumes the referenced
  // existing session (sendMessage into it) instead of creating a new one.
  resumeSessionId: text('resume_session_id'),

  // Timezone (IANA identifier, e.g. 'America/New_York')
  timezone: text('timezone'),

  // Runtime options (override global defaults when set)
  model: text('model'),
  effort: text('effort'),
  speed: text('speed'),

  // Timestamps
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
  cancelledAt: integer('cancelled_at', { mode: 'timestamp_ms' }),
  pausedAt: integer('paused_at', { mode: 'timestamp_ms' }),
}, (table) => ({
  // One pending wake per session, enforced at the storage layer: the
  // replace-on-create logic in createSessionWake runs in a transaction, and
  // this partial index makes any interleaving that slips past it a hard
  // constraint error instead of a silent duplicate wake.
  pendingWakePerSession: uniqueIndex('scheduled_tasks_pending_wake_unique')
    .on(table.resumeSessionId)
    .where(sql`status = 'pending' AND resume_session_id IS NOT NULL`),
}))

// Notifications - user notifications for session events
export const notifications = sqliteTable('notifications', {
  id: text('id').primaryKey(),
  type: text('type', { enum: ['session_complete', 'session_waiting', 'session_scheduled', 'session_webhook', 'session_chat_integration'] }).notNull(),
  sessionId: text('session_id').notNull(),
  agentSlug: text('agent_slug').notNull(),
  title: text('title').notNull(),
  body: text('body').notNull(),
  isRead: integer('is_read', { mode: 'boolean' }).notNull().default(false),
  // NOTE: notifications are intentionally agent/session-scoped, NOT per-user.
  // Read state is shared across everyone with access to the agent (a teammate
  // acknowledging a "session waiting"/"session complete" item clears it for the
  // team). There is deliberately no per-user owner column here: cross-agent
  // isolation is enforced by getAccessibleAgentSlugs() in the service layer and
  // by HasNotificationAccess on the by-id routes. A previously-speculative
  // `user_id` column was dropped (SUP-227, never wired up — always NULL). Do not
  // re-add a per-user owner unless a *targeted* notification type lands (e.g. an
  // @-mention or per-approver request), which needs a recipient + split read
  // state, not a single shared isRead bit.
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
  readAt: integer('read_at', { mode: 'timestamp_ms' }),
}, (table) => ({
  agentSlugIsReadIdx: index('notifications_agent_slug_is_read_idx').on(table.agentSlug, table.isRead),
  sessionIdIdx: index('notifications_session_id_idx').on(table.sessionId),
  createdAtIdx: index('notifications_created_at_idx').on(table.createdAt),
}))

// Proxy tokens - synthetic tokens for agent-to-proxy authentication
export const proxyTokens = sqliteTable('proxy_tokens', {
  id: text('id').primaryKey(),
  agentSlug: text('agent_slug').notNull().unique(),
  token: text('token').notNull().unique(),
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
})

// Proxy audit log - structured log of all proxied requests
export const proxyAuditLog = sqliteTable('proxy_audit_log', {
  id: text('id').primaryKey(),
  agentSlug: text('agent_slug').notNull(),
  accountId: text('account_id').notNull(),
  toolkit: text('toolkit').notNull(),
  targetHost: text('target_host').notNull(),
  targetPath: text('target_path').notNull(),
  method: text('method').notNull(),
  statusCode: integer('status_code'),
  errorMessage: text('error_message'),
  durationMs: integer('duration_ms'),
  policyDecision: text('policy_decision'), // allow, block, review, denied_by_user, review_timeout
  matchedScopes: text('matched_scopes'), // JSON array string of matched scope names
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
}, (table) => ({
  agentSlugCreatedAtIdx: index('proxy_audit_log_agent_slug_created_at_idx').on(table.agentSlug, table.createdAt),
  accountIdCreatedAtIdx: index('proxy_audit_log_account_id_created_at_idx').on(table.accountId, table.createdAt),
  // Covers the home-graph usage aggregation (GROUP BY agent×account, with an
  // owner join on account_id) — the table grows with every proxied call, so
  // an unindexed scan degrades linearly forever.
  accountAgentIdx: index('proxy_audit_log_account_agent_idx').on(table.accountId, table.agentSlug),
}))

// Remote MCP servers registered at app level
export const remoteMcpServers = sqliteTable('remote_mcp_servers', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  url: text('url').notNull(),
  userId: text('user_id').references(() => user.id, { onDelete: 'cascade' }), // Owner in auth mode, null in non-auth mode
  authType: text('auth_type', { enum: ['none', 'oauth', 'bearer'] }).notNull().default('none'),

  // Auth tokens
  accessToken: text('access_token'),
  refreshToken: text('refresh_token'),
  tokenExpiresAt: integer('token_expires_at', { mode: 'timestamp_ms' }),

  // OAuth metadata (for token refresh)
  oauthTokenEndpoint: text('oauth_token_endpoint'),
  oauthClientId: text('oauth_client_id'),
  oauthClientSecret: text('oauth_client_secret'),
  oauthResource: text('oauth_resource'),

  // Server metadata (cached from discovery)
  toolsJson: text('tools_json'),
  toolsDiscoveredAt: integer('tools_discovered_at', { mode: 'timestamp_ms' }),

  status: text('status', { enum: ['active', 'error', 'auth_required'] }).notNull().default('active'),
  errorMessage: text('error_message'),
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
})

// Junction table: agent → remote MCP mappings
export const agentRemoteMcps = sqliteTable('agent_remote_mcps', {
  id: text('id').primaryKey(),
  agentSlug: text('agent_slug').notNull(),
  remoteMcpId: text('remote_mcp_id').notNull()
    .references(() => remoteMcpServers.id, { onDelete: 'cascade' }),
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
}, (table) => ({
  agentMcpUnique: uniqueIndex('agent_remote_mcps_unique').on(table.agentSlug, table.remoteMcpId),
}))

// MCP audit log
export const mcpAuditLog = sqliteTable('mcp_audit_log', {
  id: text('id').primaryKey(),
  agentSlug: text('agent_slug').notNull(),
  remoteMcpId: text('remote_mcp_id').notNull(),
  remoteMcpName: text('remote_mcp_name').notNull(),
  method: text('method').notNull(),
  requestPath: text('request_path').notNull(),
  statusCode: integer('status_code'),
  errorMessage: text('error_message'),
  durationMs: integer('duration_ms'),
  policyDecision: text('policy_decision'), // allow, block, review, denied_by_user, review_timeout
  matchedTool: text('matched_tool'), // tool name for tools/call requests
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
}, (table) => ({
  agentSlugCreatedAtIdx: index('mcp_audit_log_agent_slug_created_at_idx').on(table.agentSlug, table.createdAt),
  remoteMcpIdCreatedAtIdx: index('mcp_audit_log_remote_mcp_id_created_at_idx').on(table.remoteMcpId, table.createdAt),
  // Same rationale as proxy_audit_log_account_agent_idx: usage aggregation
  // over an append-only table.
  mcpAgentIdx: index('mcp_audit_log_mcp_agent_idx').on(table.remoteMcpId, table.agentSlug),
}))

// Agent ACLs - maps users to agents with roles (auth mode only)
export const agentAcl = sqliteTable('agent_acl', {
  id: text('id').primaryKey(),
  userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }),
  agentSlug: text('agent_slug').notNull(),
  role: text('role', { enum: ['owner', 'user', 'viewer'] }).notNull(),
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
}, (table) => ({
  userAgentUnique: uniqueIndex('agent_acl_user_agent_unique').on(table.userId, table.agentSlug),
  agentSlugIdx: index('agent_acl_agent_slug_idx').on(table.agentSlug),
}))

// User settings - per-user preferences (uses 'local' sentinel in non-auth mode)
export const userSettings = sqliteTable('user_settings', {
  userId: text('user_id').primaryKey().references(() => user.id, { onDelete: 'cascade' }),
  settings: text('settings').notNull(), // JSON blob validated by Zod
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
})

// Message author attribution - tracks who sent each user message (auth mode only)
export const messageAuthor = sqliteTable('message_author', {
  id: text('id').primaryKey(), // Same UUID passed to the SDK and written into JSONL
  sessionId: text('session_id').notNull(),
  agentSlug: text('agent_slug').notNull(),
  userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }),
  createdAt: integer('created_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
}, (table) => ({
  sessionIdx: index('message_author_session_idx').on(table.sessionId),
}))

// API scope policies - per-account scope-level access policies
export const apiScopePolicies = sqliteTable('api_scope_policies', {
  id: text('id').primaryKey(),
  accountId: text('account_id').notNull()
    .references(() => connectedAccounts.id, { onDelete: 'cascade' }),
  scope: text('scope').notNull(), // scope name, or '*' for account default
  decision: text('decision', { enum: ['allow', 'review', 'block'] }).notNull(),
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
}, (table) => ({
  accountScopeUnique: uniqueIndex('api_scope_policies_unique').on(table.accountId, table.scope),
}))

// Agent invoke policies - per-caller policies for x-agent operations
// callerAgentSlug → (operation, optional targetAgentSlug) → decision
//   operation 'list' uses targetAgentSlug = null (one row per caller)
//   operation 'read' / 'invoke' use targetAgentSlug = the other agent
//   create_agent is intentionally absent — spec requires manual approval, no memory
export const xAgentPolicies = sqliteTable('x_agent_policies', {
  id: text('id').primaryKey(),
  callerAgentSlug: text('caller_agent_slug').notNull(),
  targetAgentSlug: text('target_agent_slug'), // null = applies to all (used for 'list')
  operation: text('operation', { enum: ['list', 'read', 'invoke'] }).notNull(),
  decision: text('decision', { enum: ['allow', 'review', 'block'] }).notNull(),
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
}, (table) => ({
  // Unique per (caller, target, operation). NULL targetAgentSlug counts as a distinct value in SQLite.
  callerTargetOpUnique: uniqueIndex('x_agent_policies_unique')
    .on(table.callerAgentSlug, table.targetAgentSlug, table.operation),
  callerSlugIdx: index('x_agent_policies_caller_idx').on(table.callerAgentSlug),
}))

// MCP tool policies - per-MCP tool-level access policies
export const mcpToolPolicies = sqliteTable('mcp_tool_policies', {
  id: text('id').primaryKey(),
  mcpId: text('mcp_id').notNull()
    .references(() => remoteMcpServers.id, { onDelete: 'cascade' }),
  toolName: text('tool_name').notNull(), // tool name, or '*' for MCP default
  decision: text('decision', { enum: ['allow', 'review', 'block'] }).notNull(),
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
}, (table) => ({
  mcpToolUnique: uniqueIndex('mcp_tool_policies_unique').on(table.mcpId, table.toolName),
}))

// Webhook triggers - Composio trigger subscriptions and custom webhook
// endpoints (agent-minted public URLs on the platform proxy) for agents
export const webhookTriggers = sqliteTable('webhook_triggers', {
  id: text('id').primaryKey(),
  agentSlug: text('agent_slug').notNull(),

  // 'composio' = Composio trigger subscription; 'custom' = agent-minted public
  // webhook endpoint. Explicit column instead of inferring from the id prefix.
  kind: text('kind', { enum: ['composio', 'custom'] })
    .notNull()
    .default('composio'),

  // Composio details. For kind='custom', composioTriggerId carries the platform
  // webhook endpoint id ("whep_...") — events ride the same column both ways —
  // and connectedAccountId is null (no connected account involved).
  composioTriggerId: text('composio_trigger_id'), // set after Composio confirms (e.g. "ti_...")
  connectedAccountId: text('connected_account_id'),
  triggerType: text('trigger_type').notNull(), // slug e.g. 'GMAIL_NEW_EMAIL' or 'CUSTOM_WEBHOOK'
  triggerConfig: text('trigger_config'), // JSON string

  // What to do when triggered
  prompt: text('prompt').notNull(),
  name: text('name'),

  // Status
  status: text('status', { enum: ['active', 'paused', 'cancelled', 'failed'] })
    .notNull()
    .default('active'),

  // Execution tracking
  lastFiredAt: integer('last_fired_at', { mode: 'timestamp_ms' }),
  fireCount: integer('fire_count').notNull().default(0),
  lastSessionId: text('last_session_id'),

  // Ownership
  createdBySessionId: text('created_by_session_id'),
  createdByUserId: text('created_by_user_id'),

  // Runtime options (override global defaults when set)
  model: text('model'),
  effort: text('effort'),
  speed: text('speed'),

  // Timestamps
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
  cancelledAt: integer('cancelled_at', { mode: 'timestamp_ms' }),
  pausedAt: integer('paused_at', { mode: 'timestamp_ms' }),
}, (table) => ({
  agentSlugIdx: index('webhook_triggers_agent_slug_idx').on(table.agentSlug),
  statusIdx: index('webhook_triggers_status_idx').on(table.status),
  composioTriggerIdx: index('webhook_triggers_composio_idx').on(table.composioTriggerId),
}))

// Chat integrations - external messaging connections (Telegram, Slack, etc.)
export const chatIntegrations = sqliteTable('chat_integrations', {
  id: text('id').primaryKey(),
  agentSlug: text('agent_slug').notNull(),
  provider: text('provider', { enum: CHAT_PROVIDERS }).notNull(),
  name: text('name'), // User-defined label

  // Provider credentials (JSON: { botToken, chatId } | { botToken, appToken, channelId } | { gatewayUrl, phoneNumber, token })
  config: text('config').notNull(),

  // Behavior settings
  showToolCalls: integer('show_tool_calls', { mode: 'boolean' }).notNull().default(false),
  requireApproval: integer('require_approval', { mode: 'boolean' }).notNull().default(true),
  sessionTimeout: integer('session_timeout'), // Hours; null/0 = single persistent session
  model: text('model'), // Claude model override; null = use default
  effort: text('effort'), // Effort level override; null = use default
  speed: text('speed'), // Speed level override; null = use default

  // Status
  status: text('status', { enum: ['active', 'paused', 'error', 'disconnected'] })
    .notNull().default('active'),
  errorMessage: text('error_message'),

  // Ownership (auth mode)
  createdByUserId: text('created_by_user_id'),

  // Timestamps
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
}, (table) => ({
  agentSlugIdx: index('chat_integrations_agent_slug_idx').on(table.agentSlug),
  statusIdx: index('chat_integrations_status_idx').on(table.status),
}))

// Chat integration sessions - maps external chat IDs to agent sessions (supports multi-DM)
export const chatIntegrationSessions = sqliteTable('chat_integration_sessions', {
  id: text('id').primaryKey(),
  integrationId: text('integration_id').notNull()
    .references(() => chatIntegrations.id, { onDelete: 'cascade' }),
  externalChatId: text('external_chat_id').notNull(), // Telegram chat_id or Slack channel_id
  sessionId: text('session_id').notNull(),
  displayName: text('display_name'), // e.g. "John's DM", "#general"
  archivedAt: integer('archived_at', { mode: 'timestamp_ms' }), // Set when session is cleared; null = active
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
}, (table) => ({
  integrationIdIdx: index('chat_integration_sessions_integration_id_idx').on(table.integrationId),
}))

export const chatIntegrationAccess = sqliteTable('chat_integration_access', {
  id: text('id').primaryKey(),
  integrationId: text('integration_id').notNull()
    .references(() => chatIntegrations.id, { onDelete: 'cascade' }),
  externalChatId: text('external_chat_id').notNull(),
  chatType: text('chat_type', { enum: ['private', 'group', 'supergroup'] }), // nullable: seeded rows unknown
  status: text('status', { enum: ['pending', 'allowed', 'denied'] }).notNull().default('pending'),
  approvalSource: text('approval_source', { enum: ['auto_first_contact', 'owner', 'migration'] }),
  title: text('title'),
  firstUserId: text('first_user_id'),
  firstUserName: text('first_user_name'),
  firstMessagePreview: text('first_message_preview'),
  requestNoticeSentAt: integer('request_notice_sent_at', { mode: 'timestamp_ms' }),
  requestedAt: integer('requested_at', { mode: 'timestamp_ms' }).notNull(),
  decidedAt: integer('decided_at', { mode: 'timestamp_ms' }),
  decidedByUserId: text('decided_by_user_id'), // NOT an FK: non-auth mode stores sentinel "local"
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
}, (table) => ({
  chatUnique: uniqueIndex('chat_integration_access_unique').on(table.integrationId, table.externalChatId),
  statusIdx: index('chat_integration_access_status_idx').on(table.integrationId, table.status),
  statusCheck: check('chat_integration_access_status_check', sql`${table.status} in ('pending','allowed','denied')`),
  chatTypeCheck: check('chat_integration_access_chat_type_check', sql`${table.chatType} is null or ${table.chatType} in ('private','group','supergroup')`),
  sourceCheck: check('chat_integration_access_source_check', sql`${table.approvalSource} is null or ${table.approvalSource} in ('auto_first_contact','owner','migration')`),
}))

// Audit log - tracks key user actions across the app
export const auditLog = sqliteTable('audit_log', {
  id: text('id').primaryKey(),
  createdAt: integer('created_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  userId: text('user_id'),
  object: text('object').notNull(),
  objectId: text('object_id').notNull(),
  action: text('action').notNull(),
  details: text('details'), // JSON
}, (table) => ({
  createdAtIdx: index('audit_log_created_at_idx').on(table.createdAt),
  objectIdx: index('audit_log_object_idx').on(table.object),
  userIdIdx: index('audit_log_user_id_idx').on(table.userId),
}))

// Type exports for convenience
export type ConnectedAccount = typeof connectedAccounts.$inferSelect
export type NewConnectedAccount = typeof connectedAccounts.$inferInsert
export type AgentConnectedAccount = typeof agentConnectedAccounts.$inferSelect
export type NewAgentConnectedAccount = typeof agentConnectedAccounts.$inferInsert
export type ScheduledTask = typeof scheduledTasks.$inferSelect
export type NewScheduledTask = typeof scheduledTasks.$inferInsert
export type Notification = typeof notifications.$inferSelect
export type NewNotification = typeof notifications.$inferInsert
export type ProxyToken = typeof proxyTokens.$inferSelect
export type NewProxyToken = typeof proxyTokens.$inferInsert
export type ProxyAuditLogEntry = typeof proxyAuditLog.$inferSelect
export type NewProxyAuditLogEntry = typeof proxyAuditLog.$inferInsert
export type RemoteMcpServer = typeof remoteMcpServers.$inferSelect
export type NewRemoteMcpServer = typeof remoteMcpServers.$inferInsert
export type AgentRemoteMcp = typeof agentRemoteMcps.$inferSelect
export type NewAgentRemoteMcp = typeof agentRemoteMcps.$inferInsert
export type McpAuditLogEntry = typeof mcpAuditLog.$inferSelect
export type NewMcpAuditLogEntry = typeof mcpAuditLog.$inferInsert
export type AgentAcl = typeof agentAcl.$inferSelect
export type NewAgentAcl = typeof agentAcl.$inferInsert
export type UserSettingsRow = typeof userSettings.$inferSelect
export type NewUserSettingsRow = typeof userSettings.$inferInsert
export type User = typeof user.$inferSelect
export type AuthSession = typeof authSession.$inferSelect
export type AuthAccount = typeof authAccount.$inferSelect
export type Verification = typeof verification.$inferSelect
export type ApiScopePolicy = typeof apiScopePolicies.$inferSelect
export type NewApiScopePolicy = typeof apiScopePolicies.$inferInsert
export type McpToolPolicy = typeof mcpToolPolicies.$inferSelect
export type NewMcpToolPolicy = typeof mcpToolPolicies.$inferInsert
export type XAgentPolicy = typeof xAgentPolicies.$inferSelect
export type NewXAgentPolicy = typeof xAgentPolicies.$inferInsert
export type WebhookTrigger = typeof webhookTriggers.$inferSelect
export type NewWebhookTrigger = typeof webhookTriggers.$inferInsert
export type ChatIntegration = typeof chatIntegrations.$inferSelect
export type NewChatIntegration = typeof chatIntegrations.$inferInsert
export type ChatIntegrationSession = typeof chatIntegrationSessions.$inferSelect
export type NewChatIntegrationSession = typeof chatIntegrationSessions.$inferInsert
export type ChatIntegrationAccess = typeof chatIntegrationAccess.$inferSelect
export type NewChatIntegrationAccess = typeof chatIntegrationAccess.$inferInsert
export type AuditLogEntry = typeof auditLog.$inferSelect
export type NewAuditLogEntry = typeof auditLog.$inferInsert
